android/app/build.gradle
android/app/src/main/AndroidManifest.xml
android/app/src/main/java/com/reactnativenavigation/activities/BaseReactActivity.java
android/app/src/main/java/com/reactnativenavigation/activities/BottomTabActivity.java
android/app/src/main/java/com/reactnativenavigation/activities/TabActivity.java
android/app/src/main/java/com/reactnativenavigation/core/objects/Button.java
android/app/src/main/java/com/reactnativenavigation/core/objects/Screen.java
android/app/src/main/java/com/reactnativenavigation/modules/RctActivityModule.java
android/app/src/main/java/com/reactnativenavigation/utils/IconUtils.java
android/app/src/main/java/com/reactnativenavigation/views/RnnToolBar.java
android/app/src/main/res/layout/bottom_tab_activity.xml
example-redux/src/screens/FirstTabScreen.js
example-redux/src/screens/SecondTabScreen.js
src/platformSpecific.android.js

Adds BottomTabActivity which replaces TabActivity
Adds a dependency on `com.aurelhubert:ahbottomnavigation:1.2.3`
Uses iOS tabsStyle, with additional parameter that allows toggling of whether to show the titles of inactive tabs

Add support for bottom tabs in Android

---

android/app/src/main/java/com/reactnativenavigation/activities/BottomTabActivity.java
android/app/src/main/java/com/reactnativenavigation/activities/SingleScreenActivity.java
android/app/src/main/java/com/reactnativenavigation/activities/TabActivity.java
android/app/src/main/java/com/reactnativenavigation/core/objects/JsonObject.java
android/app/src/main/java/com/reactnativenavigation/core/objects/Screen.java
android/app/src/main/java/com/reactnativenavigation/modal/RnnModal.java
android/app/src/main/java/com/reactnativenavigation/views/RnnToolBar.java

This PR will ideally also make it a lot easier to support multiple Toolbar styles within a single app.
Most of the edge cases I could find were around multiple modals, but worth checking tab/single screen activity push/pop shows/hides the Toolbar correctly as well.
Haven't touched native Android code before, so really open to feedback and suggestions.

Add support for hiding the Toolbar on Android

---

android/app/src/main/java/com/reactnativenavigation/activities/BottomTabActivity.java
android/app/src/main/java/com/reactnativenavigation/activities/SingleScreenActivity.java
android/app/src/main/java/com/reactnativenavigation/activities/TabActivity.java
src/platformSpecific.android.js

This update ensures navigator styles are applied on screen changes.  It also merges the base styles with screen-specific styles as to allow default values that can be overridden.

Android style fixes

---

android/app/src/main/java/com/reactnativenavigation/activities/BaseReactActivity.java
android/app/src/main/java/com/reactnativenavigation/activities/BottomTabActivity.java
android/app/src/main/java/com/reactnativenavigation/activities/SingleScreenActivity.java
android/app/src/main/java/com/reactnativenavigation/core/objects/Drawer.java
android/app/src/main/java/com/reactnativenavigation/core/objects/Screen.java
android/app/src/main/java/com/reactnativenavigation/modules/RctActivityModule.java
android/app/src/main/java/com/reactnativenavigation/views/RnnToolBar.java
android/app/src/main/res/layout/bottom_tab_activity.xml
android/app/src/main/res/layout/single_screen_activity.xml
android/app/src/main/res/values/strings.xml
src/platformSpecific.android.js

This is a native drawer implementation that uses the animated arrow menu icon by default.  Currently only a left menu is implemented for SingleScreenActivity and BottomTabActivity.  I've been using this in a client application with SingleScreenActivity for the past few weeks and it's been working well.

Android drawer implementation

---

android/app/src/main/java/com/reactnativenavigation/controllers/Modal.java
android/app/src/main/java/com/reactnativenavigation/controllers/ModalController.java
android/app/src/main/java/com/reactnativenavigation/controllers/NavigationActivity.java
android/app/src/main/java/com/reactnativenavigation/params/parsers/TitleBarButtonParamsParser.java
src/deprecated/platformSpecificDeprecated.android.js

All stack actions routed through NavigationActivity are also forwarded to ModalController
TitleBarButtonParams field 'enabled' is read from 'disabled' to match iOS and existing API. (sorry)

Fixes to Modal and top buttons

---

src/deprecated/platformSpecificDeprecated.ios.js

Fixes https://github.com/wix/react-native-navigation/issues/284
`controllerID` was generated when used in `params.tabs.map(function(tab, index) {...`. Moving it before the `.map` fixes the issue as each screen has correct name reference for controllerID.

Generate controllerID before using it in tabs.map

---

android/app/build.gradle

Summary:
The old path only work for 'example-redux'

Fixed path of RN local Maven repo

---

android/app/src/main/java/com/reactnativenavigation/react/NavigationReactGateway.java

Retrieve current activity from reactInstanceManager in order to listen to onActivityResult interface change in RN33 or above. This also ensure result is passed back to React instance so other modules are able to get onActivityResult called.

[Android] Fix for RN33 onActivityResult interface change

---

android/app/src/main/java/com/reactnativenavigation/params/StyleParams.java
android/app/src/main/java/com/reactnativenavigation/params/parsers/StyleParamsParser.java
android/app/src/main/java/com/reactnativenavigation/screens/CollapsingViewPagerScreen.java
android/app/src/main/java/com/reactnativenavigation/screens/Screen.java
android/app/src/main/java/com/reactnativenavigation/screens/ViewPagerScreen.java
src/deprecated/platformSpecificDeprecated.android.js

This PR add support for `screenBackgroundColor` property in `navigatorStyle` and collapses ViewPager screen when TopTab is selected as well

Screen background color android

---

android/app/src/main/java/com/reactnativenavigation/views/SideMenu.java
src/deprecated/platformSpecificDeprecated.android.js

- Fixes crash if both menus aren't defined
- Allows disableOpenGesture to be defined on a per menu basis

Menu set style fix

---

android/app/src/main/java/com/reactnativenavigation/views/collapsingToolbar/CollapseCalculator.java

Take scaledTouchSlop into account when calculating CollapseAmount to
prevent the TopBar from translating after every touch event, even
when the users intent was not to scroll in Y direction.

Reduce collapsing TopBar sensitivity

---

android/app/src/main/java/com/reactnativenavigation/layouts/SingleScreenLayout.java

If the left drawer is not defined in startSingleScreenApp config then the right drawer doesn't work

Bug: Right drawer on Android doesn't work #297

---

src/deprecated/platformSpecificDeprecated.ios.js

Now the style parameter is used inside RCCDrawerController but it's not passed through startTabBasedApp/startSingleScreenApp. Passing the style parameter allows to disable sidebar shadow trough style.drawerShadow.

Pass the style parameter to DrawerControllerIOS

---

android/app/src/main/java/com/reactnativenavigation/bridge/NavigationReactModule.java
android/app/src/main/java/com/reactnativenavigation/layouts/BottomTabsLayout.java
android/app/src/main/java/com/reactnativenavigation/layouts/Layout.java
android/app/src/main/java/com/reactnativenavigation/layouts/SingleScreenLayout.java
android/app/src/main/java/com/reactnativenavigation/params/FabParams.java
android/app/src/main/java/com/reactnativenavigation/params/parsers/ButtonParser.java
android/app/src/main/java/com/reactnativenavigation/params/parsers/FabParamsParser.java
android/app/src/main/java/com/reactnativenavigation/params/parsers/ScreenParamsParser.java
android/app/src/main/java/com/reactnativenavigation/params/parsers/TopTabParamsParser.java
android/app/src/main/java/com/reactnativenavigation/utils/ViewUtils.java
android/app/src/main/java/com/reactnativenavigation/views/FloatingActionButtonAnimator.java
android/app/src/main/java/com/reactnativenavigation/views/FloatingActionButtonCoordinator.java
android/app/src/main/java/com/reactnativenavigation/views/SnackbarAndFabContainer.java

This commit also introduces a tempprary fix to an issue where fab is
displayed on wrong screen when switching between bottom tabs rapidly.

Fixes overlapping fab.

---

src/deprecated/platformSpecificDeprecated.android.js

Android: If the user has specified navigatorButtons on the showModal params use those instead of the default navigatorButtons of the registered screen.
If I don't add that if, the existing code erases the navigatorButtons I pass on my params object.

Allow the user to use his own navigatorButtons when calling showModal, push etc..

---

src/deprecated/platformSpecificDeprecated.android.js

Fixed an issue where rightButtons defined on the screen parameters were overwritten by parameters defined on the Screen component itself.

rightButtons not getting passed through to native code

---

src/Navigation.js

I struggeled quite a while debugging #485 "Cannot read property 'navigatorStyle' of undefined"  which originates from incorrectly registering the component. In order to save time for other users I suggest this small change to give a more verbose error when this happens.

Add error when trying to load a component which was badly registered

---

android/app/src/main/java/com/reactnativenavigation/params/CollapsingTopBarParams.java
android/app/src/main/java/com/reactnativenavigation/params/parsers/CollapsingTopBarParamsParser.java
android/app/src/main/java/com/reactnativenavigation/views/ContentView.java
android/app/src/main/java/com/reactnativenavigation/views/collapsingToolbar/CollapsingReactHeaderMeasurer.java
android/app/src/main/java/com/reactnativenavigation/views/collapsingToolbar/CollapsingTopBar.java
android/app/src/main/java/com/reactnativenavigation/views/collapsingToolbar/CollapsingTopBarReactHeader.java
src/deprecated/platformSpecificDeprecated.android.js

This commit deprecates collapsingToolBarComponentHeight style property

Dynamic height for CollapsingReactHeader

---

android/app/src/main/java/com/reactnativenavigation/controllers/IntentDataHandler.java

this prevents linking module from handling intents each time app is returned to foreground

Clear intent extras in onPause

---

android/app/src/main/AndroidManifest.xml

This is introduced in order to prevent our activity from getting destroyed if we launch a third party app, and that app changes orientation.

Ignore config changes in portrait and landscape activities

---

android/app/src/main/java/com/reactnativenavigation/params/CollapsingTopBarParams.java
android/app/src/main/java/com/reactnativenavigation/params/parsers/CollapsingTopBarParamsParser.java
android/app/src/main/java/com/reactnativenavigation/views/TitleBar.java
android/app/src/main/java/com/reactnativenavigation/views/TranslucentAndSolidTitleBarBackground.java
android/app/src/main/java/com/reactnativenavigation/views/collapsingToolbar/CollapsingTitleBar.java
src/deprecated/platformSpecificDeprecated.android.js

This commit adds ability to set the titleBar color when it’s in
collapsed state. This is useful when the buttons and title in the TitleBar are white
and the screen contains a bright header.
Note that this property is used only if navBarTranslucent is true:
```js
collapsingToolBarCollapsedColor: 'red',
navBarTranslucent: true
```

Animate between translucent and solid background in collapsed titlebar

---

src/deprecated/platformSpecificDeprecated.android.js

This commit changes the subtitle color property name on **Android** from `navBarTextSubtitleColor` to `navBarSubtitleColor`

Change subtitle color property name to navBarSubtitleColor

---

android/app/src/main/java/com/reactnativenavigation/views/collapsingToolbar/CollapseCalculator.java
android/app/src/main/java/com/reactnativenavigation/views/collapsingToolbar/behaviours/CollapseBehaviour.java
android/app/src/main/java/com/reactnativenavigation/views/collapsingToolbar/behaviours/CollapseTitleBarBehaviour.java
android/app/src/main/java/com/reactnativenavigation/views/collapsingToolbar/behaviours/CollapseTopBarBehaviour.java
android/app/src/main/java/com/reactnativenavigation/views/collapsingToolbar/behaviours/TitleBarHideOnScrollBehaviour.java

When a view with collapsing header was fully expended, scrolling down
and quickly releasing the finger would couse the list to "bounce back".
Since the view can collapse only if its scrollY amount is less then the
scaled touch slop - the view didn't collapse and instead, scroll was
enabled.

Fix collapse issue after list bounce back

---

android/app/src/main/java/com/reactnativenavigation/controllers/Modal.java
android/app/src/main/java/com/reactnativenavigation/controllers/ModalController.java
android/app/src/main/java/com/reactnativenavigation/controllers/NavigationActivity.java
android/app/src/main/java/com/reactnativenavigation/layouts/BottomTabsLayout.java
android/app/src/main/java/com/reactnativenavigation/layouts/SingleScreenLayout.java
android/app/src/main/java/com/reactnativenavigation/params/BaseScreenParams.java
android/app/src/main/java/com/reactnativenavigation/screens/ScreenStack.java
android/app/src/main/java/com/reactnativenavigation/screens/ViewPagerScreen.java

Since fab set dynamically wasn’t saved in screen params, when returning
to that screen the fab wasn't displayed.
This commit also enables setting fab dynamically in modals

Save dynamic fab in ScreenParams

---

ios/RCCTabBarController.m

Issue #542 caused an issue where setting the `tabBarButtonColor` would override the `tabBarSelectedButtonColor`. This fixes that.

Fixing issue #542

---

docs/styling-the-navigator.md

Reading the docs I couldn't see a way to simply change the color of the status bar on Android. Only via https://github.com/wix/react-native-navigation/issues/571#issuecomment-267255350 I saw there was a prop to do this.
(Assuming this is Android only since iOS only allows for light or dark).

Add statusBarColor to navigator props docs

---

android/app/src/main/java/com/reactnativenavigation/react/JsDevReloadListenerReplacer.java
package.json

The method uses generic object, so don't is necessary casting.
Tested on RN 0.42 and 0.43

Compatibility with RN 0.43 and lower

---

android/app/src/main/java/com/reactnativenavigation/controllers/Modal.java
android/app/src/main/java/com/reactnativenavigation/controllers/NavigationActivity.java
android/app/src/main/java/com/reactnativenavigation/react/JsDevReloadListenerReplacer.java

This is mostly a workaround to overcome faults in the simple event bus implementation,
also fixes crash when reloading while modal is displayed.

Minor fixes to reload flow

---

android/app/src/main/java/com/reactnativenavigation/bridge/EventEmitter.java
android/app/src/main/java/com/reactnativenavigation/controllers/Modal.java
android/app/src/main/java/com/reactnativenavigation/screens/Screen.java
android/app/src/main/java/com/reactnativenavigation/screens/ScreenStack.java

also report type as ScreenChangedEvent instead of navBarButtonPress.
closes #1144

Send willDisappear and didDisappear on modal dismiss

---

src/views/sharedElementTransition.ios.js

I encountered [this error](https://github.com/facebook/react-native/issues/8436) and identified the cause as an import in `src/views/sharedElementTransition.ios.js`.
My understanding is that the React Native API changed at some point – `View` should be imported from `react-native` and not from `react`.
I'm using React Native 0.43.1 and React 16.0.0-alpha.6, but it looks like the React Native API change  was made around v0.25.

Import View from react-native

---

android/app/src/main/java/com/reactnativenavigation/NavigationApplication.java
android/app/src/main/java/com/reactnativenavigation/controllers/NavigationCommandsHandler.java

[Android] make fade animation transition when passed `animationType: 'fade'` and called startSingleScreenApp or startTabBasedApp.
fixes #870

start activity with fade animation when animationType: 'fade' is passed

---

docs/installation-android.md

Since `react-native link` adds the new packages to `getPackages()` I added the method and return whatever it has from the `createAdditionalReactPackages()`
```java
protected List<ReactPackage> getPackages() {
return Arrays.<ReactPackage>asList(
// eg. new SvgPackage(),
);
}
@Override
public List<ReactPackage> createAdditionalReactPackages() {
return this.getPackages();
}
```

Add compatibility with react-native link

---

docs/styling-the-tab-bar.md
ios/RCCTabBarController.m

tabBarHideShadow: bool // iOS only. Control default tab bar top shadow (hairline)

[iOS] Added option to remove default tab bar shadow (hairline)

---

example/ios/example/AppDelegate.m

I ran into an issue trying to get push notifications to work on iOS when the user taps on a notification to launch the app from a "cold" state using react-native-navigation with react-native-notifications.  Without passing launchOptions to the bridge it is not possible to detect the push notification that launched the app.  The example AppDelegate.m and associated docs don't mention this scenario so this should help other users since I don't see a downside to passing launchOptions by default.
This fixes https://github.com/wix/react-native-notifications/issues/35

Update example AppDelegate to pass launchOptions to the bridge

---

android/app/src/main/java/com/reactnativenavigation/views/SideMenu.java

The existing screen events don't appear to encompass the left and right side menus. This change adds those events in.

Add screen events for side menus on Android

---

ios/RCCViewController.m

This `return self._disableBackGesture ? self._disableBackGesture : YES;` check is incorrect, it's the same as `true ? true : true;`.
Also `_disableBackGesture` was never set. We should just `return !disabledBackGestureBool` (bool value of the prop).

[iOS] Fix disabledBackGesture.

---

android/app/src/main/java/com/reactnativenavigation/bridge/NavigationReactModule.java
android/app/src/main/java/com/reactnativenavigation/controllers/NavigationActivity.java
android/app/src/main/java/com/reactnativenavigation/controllers/NavigationCommandsHandler.java
android/app/src/main/java/com/reactnativenavigation/layouts/BottomTabsLayout.java
android/app/src/main/java/com/reactnativenavigation/layouts/Layout.java
android/app/src/main/java/com/reactnativenavigation/layouts/SingleScreenLayout.java
android/app/src/main/java/com/reactnativenavigation/views/SideMenu.java
docs/screen-api.md
src/Screen.js
src/deprecated/platformSpecificDeprecated.android.js
src/platformSpecific.android.js

Fixes #326 for Android only - I looked at the props approach but I needed a bit more control than I could get with that.
Sidenote: I'll need to do similar for iOS, but that looks a bit tricker given the multiple different drawer implementations (and the first implementation I looked at didn't have a clean way to disable without removing the view completely).

Add a way to dynamically enable/disable a side menu for Android

---

docs/styling-the-tab-bar.md

I found it in this issue https://github.com/wix/react-native-navigation/issues/129#issuecomment-249433746 and it wasn't on the [official documentation](http://wix.github.io/react-native-navigation/#/styling-the-tab-bar)

Add tabBarHidden property to docs

---

docs/screen-api.md
ios/RCCNavigationController.m
src/deprecated/platformSpecificDeprecated.ios.js

Fade transition animation for:
- push
- pop
- popToRoot
- resetTo
for example
```javascript
this.props.navigator.push({ screen: 'example.ExampleScreen', animationType: 'fade' });
```
if you not specifying `animationType`, animation will be default.

[iOS] Added fade transition animation between screens

---

android/app/src/main/java/com/reactnativenavigation/params/BaseScreenParams.java
android/app/src/main/java/com/reactnativenavigation/params/parsers/ScreenParamsParser.java
android/app/src/main/java/com/reactnativenavigation/screens/ScreenAnimator.java
docs/screen-api.md

Fade & horizontal transition animation for:
- push
- pop
- popToRoot
- resetTo
for example
```javascript
this.props.navigator.push({
screen: 'example.ExampleScreen',
animationType: 'fade' // 'fade' / 'slide-horizontal'
}); 
```
if you not specifying `animationType`, animation will be default.

[Android] Added fade & horizontal transition animations between screens

---

example/src/components/Row.js
old-example-redux/src/screens/BottomTabsSideMenu.js
old-example-redux/src/screens/FirstTabScreen.js
old-example-redux/src/screens/ListScreen.js
old-example-redux/src/screens/LoginScreen.js
old-example-redux/src/screens/PushedScreen.js
old-example-redux/src/screens/SecondTabScreen.js
old-example-redux/src/screens/SideMenu.js
package.json
src/views/sharedElementTransition.ios.js
yarn.lock

Small update in using `"prop-types"` instead of `React.PropTypes` since it's using React 16.0.0-alpha.6.
For the old examples, I only removed `PropTypes`. It looks like its not actually being used on the files, but let me know if you want `prop-types` to be added anyway and I can do so. 
(Sorry if I missed any contribution guidelines! Can't seem to find any information on it...)

Replace React.PropTypes with prop-types

---

android/app/src/main/java/com/reactnativenavigation/views/LightBox.java
android/app/src/main/res/values/styles.xml

This PR fixes the black status bar on Android causing differences between iOS and Android for draw space

Fixed lightbox status bar color override on Android

---

android/app/src/main/java/com/reactnativenavigation/animation/VisibilityAnimator.java

Closes issue #1357 
setY should not be set on a view inside a RelativeLayout, this was setting the tab bar to the Y position of 0

Fixed bottom tab bar animation setting the wrong value

---

android/app/src/main/java/com/reactnativenavigation/views/BottomTabs.java

Fixes #1411
Each time a color attribute is set in AHBottomNavigation, all items in
the BottomTabs are recreated. If a badge is set, it is animated each
time items are recreated. This behaviour can even be seen in the gifs
in the repo https://github.com/aurelhubert/ahbottomnavigation

Set BottomTab colours only if needed

---

android/app/src/main/java/com/reactnativenavigation/views/BottomTabs.java

BottomTabs height is currently being calculated twice in Android making the hide animation not work in all cases

Fixed BottomTabs height being calculated twice

---

android/app/src/main/java/com/reactnativenavigation/screens/Screen.java

When rotating the screen the TitleBar centered text will become uncentered

Fix android TitleBar center on configuration change

---

ios/RCCLightBox.m

This allows for tapping the background without setting a color here, meaning this feature can be enabled with one less view in the view hierarchy. Additionally, this allows for taps on any background view, visual effect view, color tint view, etc, but not on the content.

[iOS] Allow lightbox tap to dismiss without background color

---

android/app/src/main/java/com/reactnativenavigation/bridge/EventEmitter.java
android/app/src/main/java/com/reactnativenavigation/bridge/NavigationReactModule.java
android/app/src/main/java/com/reactnativenavigation/controllers/NavigationCommandsHandler.java
android/app/src/main/java/com/reactnativenavigation/controllers/SplashActivity.java
src/NativeEventsReceiver.js
src/Navigation.js
src/deprecated/indexDeprecated.android.js
src/deprecated/indexDeprecated.ios.js
src/deprecated/platformSpecificDeprecated.android.js
src/platformSpecific.android.js

Currently startApp is called from global context which results in the
app being launched when headlessJs tasks run in the background.
In order to support this use case, while not breaking existing users,
this commit adds two mechanisms which should help users detrmine if
the native Activity is running and startApp can be called safely.
1. RNN.appLaunched event is emitted is SplashActivity starts and react
context has already been created. This is the use case of openeing
the app while headless js task was started or has just finished and
react context is in a "pasued" state.
2. Navigation.isAppLaunched() convenience method has been added.
It returns a promise which when resolved, indicates if the app
is launched and we should show the ui or not.
Usage
```js
import {Navigation, …
```

Support headlessJs

---

docs/styling-the-navigator.md
ios/RCCViewController.m

```
rootBackgroundImageName: '<name of image in Images.xcassets>',
```
Same as `screenBackgroundImageName` but it's static while you transition between screens.
You have to set `screenBackgroundColor: 'transparent',` and also transparent color for your root View.

[iOS] Added ability to set static(root) background image

---

ios/RCCManager.m

This uses the proper methods for instantiating the initial view on iOS.
By utilizing these methods, we can stand up the initial view controller
from the storyboard.
See also:
https://developer.apple.com/library/content/documentation/General/Reference/InfoPlistKeyReference/Articles/iPhoneOSKeys.html#//apple_ref/doc/uid/TP40009252-SW41

Use UIStoryboard methods for presenting a splash screen on iOS

---

ios/RCCManager.m

Reverts wix/react-native-navigation#1453,
This is a good feature, but it breaks all current projects. Please fix and add support for loading splash screens with support for `.xib`s

Revert "Use UIStoryboard methods for presenting a splash screen on iOS"

---

android/app/src/main/java/com/reactnativenavigation/views/TitleBar.java

When using appStyle and not setting the navBarTitleFontSize prop, it was defaulting to 0 and was therefore passing the return and setting a 0 font size title.
Closes #1515.

fixed blank nav bar titles on Android when title font size not set.

---

android/app/src/main/java/com/reactnativenavigation/bridge/NavigationReactModule.java
android/app/src/main/java/com/reactnativenavigation/controllers/Modal.java
android/app/src/main/java/com/reactnativenavigation/controllers/ModalController.java
android/app/src/main/java/com/reactnativenavigation/controllers/NavigationActivity.java
android/app/src/main/java/com/reactnativenavigation/controllers/NavigationCommandsHandler.java
android/app/src/main/java/com/reactnativenavigation/layouts/BottomTabsLayout.java
android/app/src/main/java/com/reactnativenavigation/layouts/Layout.java
android/app/src/main/java/com/reactnativenavigation/layouts/SingleScreenLayout.java
ios/RCCManager.h
ios/RCCManager.m
ios/RCCManagerModule.m
ios/RCCNavigationController.m
ios/RCCViewController.h
ios/RCCViewController.m
src/Navigation.js
src/Screen.js
src/deprecated/controllers/index.js
src/deprecated/platformSpecificDeprecated.android.js
src/deprecated/platformSpecificDeprecated.ios.js
src/platformSpecific.android.js

This PR adds api to get the currently visible screen.
Usage:
1. From a screen, using navigator instance: 
`const isVisible = await this.props.navigator.isCurrentlyVisibleScreen()`
2. Globally, using `Navigation` object:
`const visibleScreenInstanceId = await Navigation. getCurrentlyVisibleScreenId()`

Currently visible screen

---

docs/top-level-api.md

Added forgotten drawer style props.

Update top-level-api.md (Added forgotten styles)

---

ios/RCCViewController.m

https://github.com/wix/react-native-navigation/issues/1446

walk-around for React-Native bug with multiple RCTRootView

---

android/app/src/main/java/com/reactnativenavigation/bridge/NavigationReactPackage.java

[`createJSModules` is now not required on Android](https://github.com/facebook/react-native/commit/ce6fb337a146e6f261f2afb564aa19363774a7a8) from RN 0.47. This is backwards compatible according to my tests.

Remove createJSModules @override marker - RN 0.47 compatibility

---

src/Navigation.js
src/Screen.js
src/deprecated/indexDeprecated.android.js
src/deprecated/indexDeprecated.ios.js

When using ESLint rule `react/prop-types`, an error is show when using `this.props.navigator` if `navigator` is not specified in the components propTypes.
Changing this library to export the `Navigator` class allows users to use it in propTypes, i.e:
```JavaScript
import PropTypes from 'prop-types';
import { Navigator } from 'react-native-navigation';
...
Component.propTypes = {
navigator: PropTypes.instanceOf(Navigator),
};
```
Whereas before you had 2 options, either:
1. Use `PropTypes.object`, which is another ESLint error (`react/forbid-prop-types`),
or
2. create your own `PropTypes.shape()`, but that feels convoluted and error-prone.
Hope this all makes sense.

Export `Navigator` class for public use

---

ios/RCCCustomBarButtonItem.h
ios/RCCCustomBarButtonItem.m
ios/RCCNavigationController.m
ios/ReactNativeNavigation.xcodeproj/project.pbxproj

This allows for custom React Native views to be rendered as a bar button item in the navigation bar.
This can be used by registering the component, just like any screen, and then by specifying the `component` for the navigation item, either left or right, like so:
```js
const styles = StyleSheet.create({
button: {
overflow: 'hidden',
width: 34,
height: 34,
borderRadius: 34 / 2,
justifyContent: 'center',
alignItems: 'center',
},
});
// Our custom component we want as a button in the nav bar
const CustomButton = ({ text }) =>
<TouchableOpacity
style={[styles.button, { backgroundColor: 'tomato' }]}
onPress={() => console.log('pressed me!')}
>
<View style={styles.button}>
<Text style={{ color: 'white' }}>
{text}
</Text>
</View>
</TouchableOpacity>;
// Register the component …
```

[iOS] Add custom bar button item class

---

ios/RCCLightBox.m

Reverts wix/react-native-navigation#1461
#1461 caused LightBox to appear in upper right corner of the screen.

Revert "Fixed LightBox not updating overlay width/height on rotate"

---

docs/top-level-api.md

As the screen api document mentions that it can be done statically, it's best to mention it here as well.

Added HandleDeepLink to TopLevelApi documentation

---

docs/android-specific-use-cases.md

Taking the code from the docs for setting the softInputMode as is, it fails to build because the LifecycleCallbacks is an invalid symbol and is actually called ActivityLifecycleCallbacks.

Update android-specific-use-cases.md to Specify correct Lifecyclecallbacks

---

ios/RCCViewController.m

Change IF condition to make sure the originalInteractivePopGestureDelegate property contains value correctly.

Bugfix #930: iOS pop gesture not work correctly after performAction

---

ios/RCCCustomBarButtonItem.m

This converts from using a deprecated attribute.

Prefer use of intrinsicContentSize

---

android/app/src/main/java/com/reactnativenavigation/NavigationApplication.java
android/app/src/main/java/com/reactnativenavigation/controllers/NavigationActivity.java
android/app/src/main/java/com/reactnativenavigation/controllers/SplashActivity.java
android/app/src/main/java/com/reactnativenavigation/react/NavigationReactGateway.java
android/app/src/main/java/com/reactnativenavigation/react/ReactGateway.java

This is a breaking change and has to be opt-in. To prevent host.clear from being called,
Override `clearHostOnActivityDestroy` in MainApplication and return false:
```java
@Override
public boolean clearHostOnActivityDestroy() {
return false;
}
```
If host isn't cleared, the next time the app is opened react context might still be initialized.
In this case we emit appLaunched event which has to be handled in Js:
```js
Promise.resolve(Navigation.isAppLaunched())
.then((appLaunched) => {
if (appLaunched) {
startApp();
}
new NativeEventsReceiver().appLaunched(() => {
startApp();
});
})
```

Stop calling host.clear() when activity is destroyed

---

docs/top-level-api.md

This troubled me a lot before I finally realized that the tabStyle for andriod is actually in appStyle. The comment for selectedIcon made me think I should change tabBarSelectedButtonColor in tabStyle.
> selectedIcon: require('../img/one_selected.png'), // local image asset for the tab icon selected state (optional, iOS only. On Android, Use `tabBarSelectedButtonColor` instead)

Update the document for tabsStyle in Android

---

ios/RCCViewController.m

In ios `tabBarHidden` is not working and required bunch of js hack to getting the desire thing to work. Based on my observation `tabBarHidden` was never implemented for navigatorStyle and I simply added that functionality.

added tabBarHidden property to navigatorStyle

---

ios/RCCViewController.m

This only happens when you are using react-native@0.48.3, and build your APP by XCode9. When you run your APP in iOS10 or below, it will throw `unrecognized selector` error. The new iOS11 has new design on StatusBar which behaves weird on UIScrollView, so that the react-native team added this new selector to fix it. This PR will help to address this problem when you are also using the amazing `react-native-navigation`.
Here's the error details:
> Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[RCTCustomScrollView setContentInsetAdjustmentBehavior:]: unrecognized selector sent to instance 0x7ffab9891a00'
Reference:
https://github.com/facebook/react-native/issues/15957
https://github.com/wix/react-native-navigation/issues/1886

Bug fixed - the UIScrollView will break on iOS10 when building by XCode9

---

android/app/src/main/java/com/reactnativenavigation/react/NavigationReactGateway.java

This commit fixes two issues found in #1838. Fixes #1924
1. Keeps calling the deprecated reactInstanceManager methods when host is cleared
to not introduce undesired behavior when clearHostOnActivityDestroy return true (old and default behavior).
2. call onHostDestroy and onHostPause only if react context exists or is being created.

Backwards compatibility for clearHostOnActivityDestroy

---

docs/docs/usage.md

In the list of `LayoutTypes`, `tabs` is not defined, hence this throws an error. Replaced it with `bottomTabs`.

Documentation - tabs is not a valid LayoutType

---

docs/docs/installation-ios.md

Since the docs suggested we remove everything inside the `didFinishLaunchingWithOptions`, without the return statement there was an `Control reaches end of non-void function` error since the function expects a boolean return. After adding this, the error goes away.

Error in documentation - AppDelegate.m has no return statement.

---

android/app/src/main/java/com/reactnativenavigation/views/slidingOverlay/SlidingOverlaysQueue.java

Observed a few crashes due to NPE in sliding overlay support as mentioned in issue #2002

Safegards against NPE in sliding overlay to avoid crashes

---

android/app/src/main/java/com/reactnativenavigation/views/SideMenu.java

While working I got a situation in which I wanted to open the side drawer on a button click.
But I was not able to do that. So I made some changes and now I am able to achieve the required functionality.

Side Drawer Toggle Problem Resolved for Android

---

android/app/src/main/java/com/reactnativenavigation/params/StyleParams.java
android/app/src/main/java/com/reactnativenavigation/params/parsers/StyleParamsParser.java
android/app/src/main/java/com/reactnativenavigation/screens/Screen.java
android/app/src/main/java/com/reactnativenavigation/utils/ViewUtils.java
android/app/src/main/java/com/reactnativenavigation/views/TitleBar.java
android/app/src/main/java/com/reactnativenavigation/views/TopBar.java
docs/styling-the-navigator.md
src/deprecated/platformSpecificDeprecated.android.js

This commit adds support for `titleBarSubtitleFontSize` and `navBarSubtitleFontFamily` on Android.
Font family can be either a .ttf/.otf asset or one of the default font families:
* sans-serif (regular)
* sans-serif-light
* sans-serif-condensed
* sans-serif-thin
* sans-serif-medium
fixes #1180

Support subtitle FontFamily on size on Android

---

android/app/src/main/java/com/reactnativenavigation/controllers/NavigationActivity.java

Fix issues with Android BackHandler listeners not getting called, not allowing to override the back functionality from the JS side
relates to #1765

Fix issues with Android BackHandler

---

android/app/src/main/java/com/reactnativenavigation/controllers/Modal.java
android/app/src/main/java/com/reactnativenavigation/screens/Screen.java
android/app/src/main/java/com/reactnativenavigation/utils/StatusBar.java

Since status bar style was applied when the screen was created, this caused a noticeable
artifact in status bar color.

Set modal status bar style in constructor

---

example/src/screens/Actions.js

`title` field is no longer used.

Fixed wrong field name of Snackbar

---

src/Screen.js

This commit adds ability to register multiple navigator event listeners:
navigator.addOnNavigatorEvent(func)
navigator.removeOnNavigatorEvent(func)
Event listeners are removed when the screen the navigator is bound to
is unmounted, calling `removeOnNavigatorEvent` isn't mandatory.
As this api conflicts with the current api, addOnNavigatorEvent can't be used
in a screen where setOnNavigatorEvent was used before.
closes #2157

Register multiple navigatorEventListeners

---

src/Navigation.js
src/deprecated/platformSpecificDeprecated.android.js

This fix allows to pass unserializable props to custom buttons, such as navigator or functions.

Don't pass custom button props over the bridge

---

src/deprecated/platformSpecificDeprecated.ios.js

This commit applies the save props mechanism used when pushing screen
to navigator buttons as well, enabling us to pass unserializable props to buttons.

Support passing unserializable props to custom button

---

ios/RCCViewController.m

Support iOS 11 prefersLargeTitles #1643

---

docs/top-level-api.md
src/deprecated/platformSpecificDeprecated.android.js

Hello! This is my first pull request here so apologize if I made any mistakes. I'm working on my first React  Native project and thought I could solve this problem that can happen to other people.
This pull request allows you to disable the open gesture only in one side of the drawer. In my current application, I want to have 2 drawers (on both sides). The left drawer is always enabled. The right drawer is only enabled in one screen.
This way I can startSingleScreenApp() and pass the two drawers, but only the left would be 'enabled':
```js
Navigation.startSingleScreenApp({
screen: initialScreen,
drawer: {
left: {
screen: DRAWER_SCREEN,
disableOpenGesture: false,
},
right: {
screen: SIDEBAR_FILTER_SCREEN,
disableOpenGesture: true,
},
},
});
```
If we pass disableOpenGesture to the drawer …

(Android) Allow disableOpenGesture right or left in the drawer

---

ios/RCCViewController.m

This fixes a bug where navigator-level styles could override styles on a specific button.
Fixes #2199

[iOS] Ensure that styles set on individual buttons are not overridden

---

docs/styling-the-navigator.md
src/deprecated/platformSpecificDeprecated.ios.js

fixes #1961 #1546 #1705
This commit changes the way props are injected into custom navBar components. Instead of passing props over the bridge and initializing the native component with them, props are now stored in Js, and are injected back when the react component is created.
This change lets us pass unserializable props to the component.
For example, passing a navigator to the component is now possible:
```js
componentDidMount() {
this.props.navigator.setStyle({
navBarCustomView: 'example.CustomTopBar',
navBarComponentAlignment: 'center',
navBarCustomViewInitialProps: {title: 'Hi!', navigator: this.props.navigator}
});
}
```

Nav bar save props

---

android/app/src/main/java/com/reactnativenavigation/views/BottomTabs.java
docs/screen-api.md
ios/RCCTabBarController.m
ios/RCCViewController.m
src/deprecated/platformSpecificDeprecated.ios.js

This PR will add the functionality to update the label of a TabButton at RunTime in iOS and Android.

setTabButton to change the label of the TabButton

---

lib/ios/ReactNativeNavigationTests/RNNCommandsHandlerTest.m

Address issue  #2183
I still do not understand why original implementation works on CI (and failed in my environment), but think that this implementation slightly cleaner because use more high-level APIs.
Tested locally with `npm run test-unit-ios`, `npm run test-unit-ios -- --release` and from Xcode

Fix failing test

---

docs/adding-buttons-to-the-navigator.md
ios/Helpers/RCTConvert+UIBarButtonSystemItem.h
ios/Helpers/RCTConvert+UIBarButtonSystemItem.m
ios/RCCNavigationController.m
ios/ReactNativeNavigation.xcodeproj/project.pbxproj

UIKit supplies a range of glyphs to be used in navigation bar buttons, so let's expose them to developers to make better native apps!
This adds support for the `systemItem` key-value in the button config to allow for placing this type of `UIBarButtonItem`s in the navigation bar.
More information about these glyphs can be found in [Apple's Human Interface Guidelines](https://developer.apple.com/ios/human-interface-guidelines/icons-and-images/system-icons/).

[iOS] Add support for bar button system items

---

ios/RCCManagerModule.m

The root won't unregister when `dismissAllModals` been called

Fix dismissAllModal API

---

android/app/src/main/java/com/reactnativenavigation/layouts/BottomTabsLayout.java
android/app/src/main/java/com/reactnativenavigation/params/parsers/StyleParamsParser.java
android/app/src/main/java/com/reactnativenavigation/views/BottomTabs.java
ios/RCCNavigationController.m
ios/RCCTabBarController.h
ios/RCCTabBarController.m
ios/RCCViewController.m

Reverts wix/react-native-navigation#2224

Revert "setStyle to style the according TabBar"

---

android/app/src/main/java/com/reactnativenavigation/controllers/Modal.java
android/app/src/main/java/com/reactnativenavigation/params/StyleParams.java
android/app/src/main/java/com/reactnativenavigation/params/parsers/StyleParamsParser.java
android/app/src/main/java/com/reactnativenavigation/screens/Screen.java
android/app/src/main/java/com/reactnativenavigation/utils/StatusBar.java
docs/styling-the-navigator.md
src/deprecated/platformSpecificDeprecated.android.js

Added support to render current screen behind the status bar when you set the color of the status bar to transparent.
Resolves: #2034

[Android] Support for transparent statusbar with current screen rendered behind it

---

android/app/src/main/java/com/reactnativenavigation/views/ContentView.java

RN 0.50 introduced a new feature to dynamically measure ReactRootView. Since RNN uses RelativeLayout for Screen and BottomTabsLayout child views added to the layout may have additional rules. When the child views are measured they are measured with respect to the LayoutParams set during Screen creation and the Parent MeasureSpec. In RNN, ContentView extends ReactRootView and it calls onMeasure using the widthMeasureSpec and heightMeasureSpec passed to it. If these measureSpecs are EXACTLY then ReactRootView will measure itself to fit the exact size requested by the parent. 
If ContentView was added with LayoutParams.MATCH_PARENT for height and/or width with additional rules eg. BELOW or ABOVE the effective height of this View may not be compatible with MATCH_PARENT. RelativeLayout does …

Fix rn 0.50 repeated calls to onMeasure.

---

ios/RCCNavigationController.m

This now matches the same spelling as other references to `commandType`.

Ensure correct spelling of `commandType`

---

android/app/src/main/java/com/reactnativenavigation/params/StyleParams.java
android/app/src/main/java/com/reactnativenavigation/params/parsers/StyleParamsParser.java
android/app/src/main/java/com/reactnativenavigation/views/TitleBar.java
docs/styling-the-navigator.md
src/deprecated/platformSpecificDeprecated.android.js

On Android to draw under the StatusBar we have to set translucent=true on StatusBar. This will remove paddingBottom from the StatusBar and the ToolBar will move up. With this fix, we can add a top padding to the navBar on Android.

Add paddingTop to android ToolBar.

---

lib/android/app/src/main/java/com/reactnativenavigation/parse/NavigationOptions.java
lib/android/app/src/main/java/com/reactnativenavigation/parse/TopTabOptions.java
lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/toptabs/TopTabController.java
lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/toptabs/TopTabsAdapter.java
lib/android/app/src/main/java/com/reactnativenavigation/views/TopBar.java
lib/android/app/src/main/java/com/reactnativenavigation/views/TopTabsLayout.java
lib/src/commands/LayoutTreeParser.js
lib/src/commands/SimpleLayouts.js
playground/src/containers/WelcomeScreen.js

Slightly changes topTabs node declaration and removed the container from it.

Setup TopTabs with ViewPager

---

android/app/src/main/java/com/reactnativenavigation/params/SideMenuParams.java
android/app/src/main/java/com/reactnativenavigation/params/parsers/SideMenuParamsParser.java
android/app/src/main/java/com/reactnativenavigation/views/SideMenu.java
docs/top-level-api.md
package.json
src/deprecated/platformSpecificDeprecated.android.js

- Fixes: https://github.com/wix/react-native-navigation/issues/510
Example:
Navigation.startSingleScreenApp({
screen: 'Welcome'
drawer: {
left: {
screen: 'SideMenu',
fixedWidth: 400,
},
},
});
}

Added optional fixedWidth property to the Android side menu

---

docs/installation-ios.md

This code block appears fine on GitHub, but is malformatted on the site:
This PR updates it to fit the format of other code blocks in the docs, so it should appear okay.

Fix formatting of code block in installation-ios

---

lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/toptabs/TopTabController.java
lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/toptabs/TopTabsAdapter.java
lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/toptabs/TopTabsController.java
lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/toptabs/TopTabsViewPager.java
lib/android/app/src/main/java/com/reactnativenavigation/views/TopTabsLayout.java
lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/TopTabControllerTest.java
lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/TopTabsControllerMock.java
playground/src/containers/TopTabOptionsScreen.js

* minor refactor - moved some logic from view to controller

Test TopTab navigationOptions is applied correctly

---

ios/RCCViewController.m

This fixes an issue with a custom title-view (which has a title and a subtitle) appearing at the left side of the nav-bar instead of the center during a transition animation: when a screen with this title-view is being pushed or when you pop back to it.
This happens because the title-view is being created again when RCCViewController appears. There's probably no point in setting the title-view again with the same data when it already has it. The title view setup is done anyway in RCCNavigationController.
This can be easily reproduced by calling `this.props.navigator.setSubTitle({subtitle: 'a subtitle'});` from the constructor of a pushed screen (in the example project `screens/types/Push.js` for example)

Fix for "jumping" title view during push/pop transitions

---

docs/styling-the-navigator.md
ios/RCCViewController.m

Essentially this is the modified working code of the PR #1491 and seems like that PR has gone inactive, so created a new PR to implement this feature

introducing navbar shadow on iOS

---

ios/RCCManagerModule.m
ios/RCCNavigationController.m

This fixes two issues with `Navigation.getCurrentlyVisibleScreenId` and `this.props.navigator.screenIsCurrentlyVisible()` on iOS.
- The wrong "controllerId" was being set for the initial screen/layout. `controllerId` is only used to return a `screenId` for Navigation.getCurrentlyVisibleScreenId.
- Take into account drawers, when trying to find the visible viewController.

[iOS] Fix getCurrentlyVisibleScreenId with drawer

---

android/app/src/main/java/com/reactnativenavigation/views/TopBar.java

When disabling elevation by setting `topBarElevationShadowEnabled` to `false`, this commit allows to re-enable it by setting the same property to true.
Elevation was previously disabled by using `setOutlineProvider(null)`, with `ViewOutlineProvider` being an Android 5.0+ object responsible for determining how views draw their outline. To allow re-enabling elevation, we keep our original `ViewOutlineProvider` and restore it when elevation is enabled again.
Tested on Android 4.4 (no elevation appears at all as designed) and Android 6.0.
Fixes #1495.

Support re-enabling top bar elevation

---

lib/android/app/src/main/java/com/reactnativenavigation/NavigationApplication.java
lib/android/app/src/main/java/com/reactnativenavigation/presentation/OptionsPresenter.java
lib/android/app/src/main/java/com/reactnativenavigation/utils/ImageUtils.java
lib/android/app/src/main/java/com/reactnativenavigation/views/TitleBarButton.java

Only reason to offload icon loading to background thread is to avoid
supposed network on main thread calls which happen only in debug since
icons are passed loaded from localhost.

Load icons on main thread

---

docs/top-level-api.md

Fixed some formatting errors in the top level API docs.

Solved doc formatting issues

---

lib/android/app/src/main/java/com/reactnativenavigation/NavigationApplication.java
lib/android/app/src/main/java/com/reactnativenavigation/react/NavigationReactNativeHost.java
lib/android/app/src/main/java/com/reactnativenavigation/react/ReactGateway.java

Currently the default NavigationReactNativeHost only adds the NavigationPackage. Users may need to override additional methods in ReactNativeHost. This change allows advanced users to provide their own implementation of ReactNativeHost, with the requirement that they add the NavigationPackage themselves.

Allow users to provide a custom ReactNativeHost

---

android/app/src/main/java/com/reactnativenavigation/layouts/BottomTabsLayout.java
android/app/src/main/java/com/reactnativenavigation/params/parsers/StyleParamsParser.java
android/app/src/main/java/com/reactnativenavigation/screens/Screen.java
android/app/src/main/java/com/reactnativenavigation/views/BottomTabs.java
ios/RCCNavigationController.m
ios/RCCTabBarController.h
ios/RCCTabBarController.m
ios/RCCViewController.m

@danielang Removing changes in RCCNavigationController fixed the issue we had. Does this make sense?

SetStyle fix

---

android/app/src/main/java/com/reactnativenavigation/controllers/NavigationActivity.java
android/app/src/main/java/com/reactnativenavigation/react/JsDevReloadListenerReplacer.java

React Native 0.52.0 introduces a new way for rendering dev support related views on Android, so no SYSTEM_ALERT_WINDOW permission is required to display RedBox error dialog. Unfortunately, this change is breaking for this library because the interface `ReactInstanceDevCommandsHandler` has been renamed to `ReactInstanceManagerDevHelper`. 
In this PR I have rewritten `JsDevReloadListenerReplacer` so instead of a class implementing exactly interface, a dynamic proxy is used to create an implementation of a right interface at runtime. This way, backward compatibility with the previous versions is preserved, and RN 0.52.0 and up can be supported as well.
Also, I have added a small piece of code to `postHandleJsDevReloadEvent` method of `NavigationActivity` that check if `mRedBoxDialog` field …

[Android] Add backwards compatible support for react-native 0.52.0

---

docs/_sidebar.md
docs/docs/Component.md
docs/docs/Navigation.md
docs/docs/Root.md
docs/docs/SideMenu.md
docs/docs/usage.md
docs/docs/v1tov2diff.md

Some basic changes to the documentation, because starting with RNN today could be quite confusing.
Container is now Component.
Import statement is import { Navigation } from 'react-native-navigation'.
Added use case for stack.
I can't find any documentation on how to compile the documentation :P I tried to compile with Jekyll without any luck.

Update v2 documentation 

---

android/app/src/main/java/com/reactnativenavigation/params/StyleParams.java
android/app/src/main/java/com/reactnativenavigation/params/parsers/StyleParamsParser.java
android/app/src/main/java/com/reactnativenavigation/views/TitleBar.java
docs/styling-the-navigator.md
src/deprecated/platformSpecificDeprecated.android.js

Resolves [#2608](https://github.com/wix/react-native-navigation/issues/2608)
Problem: navBarTitleTextCentered doesn´t center the SubTitle. 
Solution: Introduce navBarSubTitleTextCentered for Android
Platform: Android
- Adapt title center
- Update docs

Set titleBarSubTitleTextCentered as navigator style for android

---

android/app/src/main/java/com/reactnativenavigation/views/SnackbarAndFabContainer.java

Fix the below EmptyStackException
```java
java.util.EmptyStackException: null
at java.util.Stack.peek(Stack.java:57)
at com.reactnativenavigation.screens.ScreenStack.peek(ScreenStack.java:240)
at com.reactnativenavigation.layouts.SingleScreenLayout.getCurrentScreen(SingleScreenLayout.java:323)
at com.reactnativenavigation.views.SnackbarAndFabContainer$1.run(SnackbarAndFabContainer.java:70)
at com.reactnativenavigation.views.FloatingActionButtonCoordinator$2.onAnimationEnd(FloatingActionButtonCoordinator.java:78)
at com.reactnativenavigation.views.FloatingActionButtonAnimator$2.onAnimationEnd(FloatingActionButtonAnimator.java:96)
at android.view.ViewPropertyAnimator$AnimatorEventListener.onAnimationEnd(ViewPropertyAnimator.java:1135)
at …
```

Fix EmptyStackException

---

ios/RCCNavigationController.m

The `UINavigationController` API allows for `setViewControllers:animated:` to be
called with multiple view controllers, for resetting entire stacks, rather than
just resetting to one view controller.
This allows for `navigator.resetTo()` to be called with an array of components,
rather than just one component, to let the navigation stack reset to multiple
view controllers.
This is backwards-compatible with the existing API.
An example of this would look like:
```js
this.props.navigator.resetTo({
components: [
{
component: "ScreenA",
passProps: {
greeting: "Hello, World"
},
leftButtons: [
// same as normal button setting for a screen
]
},
{
component: "ScreenB",
passProps: {
greetingId: 1234
},
style: {
// same as normal screen style
}
}
]
});
```

[iOS] Allow set view controllers to be called with multiple components

---

android/app/src/main/java/com/reactnativenavigation/layouts/BottomTabsLayout.java
android/app/src/main/java/com/reactnativenavigation/layouts/SingleScreenLayout.java
android/app/src/main/java/com/reactnativenavigation/params/ScreenParams.java
android/app/src/main/java/com/reactnativenavigation/params/parsers/ScreenParamsParser.java
android/app/src/main/java/com/reactnativenavigation/screens/ScreenStack.java
src/deprecated/platformSpecificDeprecated.android.js

For example, the following code will start a single screen app with two
screens pushed into the stack.
```js
Navigation.startSingleScreenApp({
components: [
{
screen: 'example.Types',
title: 'Navigation Types',
overrideBackPress: true
},
{
screen: 'example.Types.CustomButtonScreen',
title: 'Custom Buttons'
}
]
});
```

[Android] Add ability to start app with deep stack

---

android/app/src/main/java/com/reactnativenavigation/params/StyleParams.java
android/app/src/main/java/com/reactnativenavigation/params/parsers/StyleParamsParser.java
android/app/src/main/java/com/reactnativenavigation/views/BottomTabs.java
android/gradle/wrapper/gradle-wrapper.properties
docs/styling-the-tab-bar.md
src/deprecated/platformSpecificDeprecated.android.js

Added ability to specify font size for tab bar labels on Android

---

ios/RCCNavigationController.m

Fixed bug with `title` parameter in `resetTo` Screen API. Method `resetTo` should respect screen title and apply it to ViewController.
`props.navigator.resetTo({ screen: 'test.screen', title: 'First Screen' });`
Display screen with empty title.
[Result GIF](https://gfycat.com/ifr/WhichArtisticAlbino)
Display screen with title 'First Screen'.
[Expected Result GIF](https://gfycat.com/ifr/QuickSlimyDove)
Looks like `resetTo` behavior was broken in #2247. Code with `processTitleView` was removed in resetTo handler.
I've added `processTitleView` to viewController with support of view controller with multiple components (changes in #2247).
```javascript
import { Navigation } from "react-native-navigation";
import React from "react";
import { View, Text, StyleSheet, Button } from "react-native"; …
```

[iOS] Apply title parameter in resetTo

---

android/app/src/main/java/com/reactnativenavigation/views/SideMenu.java

Avoids a null pointer exception when not passing { side: "left" } to navigator.toggleDrawer() on Android

Make Left the default "side" for toggleDrawer

---

lib/android/app/src/main/java/com/reactnativenavigation/utils/ImageLoader.java

Steps to reproduce: 
- Implement Bottom Bar Navigation using Wix V2
- Add Microsoft CodePush.
- Launch app
- Background - Foreground app
Result Icons disappear and the following log shows in logcat:
```
BitmapFactory: Unable to decode stream: java.io.FileNotFoundException: file:/data/user/0/APP_NAME/files/CodePush/b3eb665d8241c3c032783e186d7611d4e235efc4a4a3d51d0a84ef9da1dfc9ff/bundle/drawable-xxhdpi/NAV_IMAGE.png (No such file or directory)
```
Expected: Updated/Existing icons should still be visible. 
The reason for this error is the attempt to load image using uri as string instead of the path

Fix: Bottom Nav Icons disappear when getting a CodePush (Android)

---

docs/README.md
docs/docs/Usage.md

Update the docs around a major naming change for screen lifecycle methods:
`didAppear`/`didDisappear`  to `componentDidAppear`/`componentDidDisappear`

Update V2 usage documentation for screen lifecycle methods

---

android/app/src/main/java/com/reactnativenavigation/react/NavigationReactGateway.java

There's a roundabout manner of obtaining the react context on initialisation that is null on some instances (https://github.com/wix/react-native-navigation/issues/2695), including errors on startup that prevents debugging on console. (For instance, throwing an error on index before starting the app)
It is solved by sending the same context given on method onReactContextInitialized, instead of discarding it and calling getReactContext.

Fixing NPE found on issue #2695

---

lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/bottomtabs/BottomTabsController.java

PR #2658 removed layout params from the child views, which causes
component children to receive zero width. Stack children work since
they don’t need the layout params.

[v2] Restore layout params for bottom tabs children

---

ios/RCCManager.m

Checking whether the `sharedBridge` is valid instead of only checking whether it is not null. This allows us to initialise a new bridge if the bridge was invalidated. This is useful when creating an app that loads other React Native apps, and the user wants to close the loaded app manually to try and load another.

Check whether the sharedBridge is valid

---

android/app/src/main/java/com/reactnativenavigation/params/StyleParams.java
android/app/src/main/java/com/reactnativenavigation/params/parsers/StyleParamsParser.java
android/app/src/main/java/com/reactnativenavigation/views/BottomTabs.java
docs/styling-the-tab-bar.md
src/deprecated/platformSpecificDeprecated.android.js

resolve https://github.com/wix/react-native-navigation/issues/2151

Make tabBarHideShadow to be configurable on Android

---

docs/installation-ios.md

Removed reference to - (BOOL)application:(UIApplication *)application... The way it's worded makes it seem like you only need to overwrite what's in the function, not the entire file's code.

Reference to function confusing and unnecessary

---

lib/ios/RNNBottomTabOptions.m

Not sure about adding tests for this small fix. Would you like me adding bottomTab tests, or you can merge it without it for now?
p.s. Maybe I'm wrong and there is another way to dismiss a bottomTab badge?

Add ability to set badge=null to hide it

---

ios/Helpers/RCCTitleViewHelper.m

This was occuring if a title has no properties set initially, but then are configured later. The title image data would go from `[NSNull null]` to `nil`, breaking this check.
By comparing against both values, we can ensure the correct logic for all behaviors.

Fix when a title image has nil or NSNull

---

android/app/src/main/java/com/reactnativenavigation/views/ContextualMenu.java
android/app/src/main/java/com/reactnativenavigation/views/ContextualMenuButton.java
android/app/src/main/java/com/reactnativenavigation/views/TitleBar.java
android/app/src/main/java/com/reactnativenavigation/views/TitleBarButton.java

Motivation:
When searching for the button's concrete TextView by label, if the
title has the same text as the buttons, both views are returned.

Pass ActionMenuView as parent to right buttons instead of Toolbar

---

package.json

According to https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html a package needs a `types` or `typings` field in the `package.json` that points to the correct declaration file.
Without this change I cannot import the typings.

Update package.json to reference typings

---

lib/ios/RNNTitleOptions.m

Now it uses hardcoded 20pt, which of course one can override, but in case of largerTitles, it's easier to stick with defaults.

[v2] Remove hardcoded title.fontSize to reset to defaults

---

lib/ios/RNNModalManager.m
lib/ios/RNNNavigationOptions.h
lib/ios/RNNNavigationOptions.m
lib/ios/RNNRootViewController.m
lib/ios/RNNRootViewProtocol.h

- IOS: allow tab bar / bottom tabs scene to be presented modally (it only wasn't bc showModal was calling an optional protocol method)
- IOS: fix bug where modal options weren't being applied before viewController was presented
- IOS: add UIKit `modalTransitionStyle` enum.

IOS: modal tab bar scene and modalTransitionStyle

---

lib/ios/RNNSideMenu/RCCDrawerController.h

Library wont build for me (cocoapods install) due to this file not building. The implementation file is all commented out - is this a file we should just remove?

Update import to <React/**.h>

---

android/app/src/main/java/com/reactnativenavigation/NavigationApplication.java
android/app/src/main/java/com/reactnativenavigation/controllers/SplashActivity.java
android/app/src/main/java/com/reactnativenavigation/react/NavigationReactGateway.java

We do that in order to allow the end user to decide wether they want to destroy the host based on which activity we're about to destroy.
For example in our app we do the following:
```java
@Override
public boolean clearHostOnActivityDestroy(Activity activity) {
// If the activity about to be destroyed is the SplashActivity
if (activity.getClass() == SplashActivity.class) {
// a.k.a an Instant Link was passed
return true; // we want to destroy the host for that activity
// If we returned false here, that will make the instant links get stuck on the Splash Screen for ever
}
// on every other case (i.e if NavigationActivity) we want the host to be kept intact
// Otherwise we run the risk of getting "Tried to enqueue runnable on already finished thread: 'native_modules...
return false;
}
```

[Breaking] Exposed activity on clearHostOnActivityDestroy

---

lib/android/app/src/main/java/com/reactnativenavigation/react/NavigationReactInitializer.java

When refreshing multiple times, the asynchronous process that creates React Navigation causes a crash. Looking at the code, there was a lint warning as the context that was being used might be null (as it's being recreated). This PR addresses the issue by passing the freshly created process and checking for flag before emitting event

Fixes NPE when initializing twice

---

lib/ios/RNNRootViewController.m

Hey guys, 
wanted to get your input on this.
Basically what's happening is that when you push a view controller on a navigationController with a custom view, the new ViewController will get rid of the custom view (as it should) but going back to the original ViewController won't restore the custom view.
the `if` inside the `else if` is checking if the pushed ViewController has a custom title at which point we should pop that outta the navigationController's top bar before presenting it's custom view.
i wish there was some kind of animation for when you do the edge to edge swipe 😆

IOS: Fix custom top bar from disappearing after a push

---

lib/android/app/src/main/java/com/reactnativenavigation/react/NavigationReactInitializer.java

Reverts wix/react-native-navigation#3128
`ApplicationLifecycleTest.test.js` broke after merging this

Revert "Fixes NPE when initializing twice"

---

ios/RCCManager.m

Add the iPad landscape launch image. Without this you get an ugly stretched portrait image when loading in landscape orientation.

Add iPad landscape launch image

---

lib/android/app/src/main/java/com/reactnativenavigation/react/ReactGateway.java

We need this constructor to be accessible in order to integrate with CodePush

Reverting ReactGateway constructor to `public`

---

android/app/src/main/java/com/reactnativenavigation/views/LeftButton.java

By default RTL is not enabled on the MaterialMenuDrawable from which the LeftButton extends. This results in the back button not being flipped when running your app against a right-to-left language. Enabling RTL for the LeftButton fixes this behavior and correctly flips the button when needed.

Enable RTL support on LeftButton

---

lib/ios/RNNEventEmitter.m

Problem
---------------
I registered a nativeEventListener for detecting bottomTab changes. Everything was looking good, events were coming. Then I realized, event name is undefined but params object is coming as expected. 
Code
-----------
```
function commandListener(name, params) => { console.log(name, params) };
Navigation.events().registerNativeEventListener(commandListener);
```
Investigation
-------------
As you can see here: https://github.com/wix/react-native-navigation/blob/v2/lib/src/events/EventsRegistry.ts#L28 nativeEventListener expects an object which includes name and params but on the iOS side, the native code triggers the event listener but passes wrong object. iOS is passes commandName instead of name. This PR fixes the problem.

iOS native event fix

---

lib/android/app/src/main/java/com/reactnativenavigation/parse/LayoutFactory.java
lib/android/app/src/main/java/com/reactnativenavigation/presentation/BottomTabsOptionsPresenter.java
lib/android/app/src/main/java/com/reactnativenavigation/presentation/SideMenuOptionsPresenter.java

Sidemenus weren't clickable on Android. It seems the order in which child views were being added to parent controllers, left or right before center, was affecting the ability to interact with the menus.  I've changed the code to always add them in a specific order: center, then left, then right.
I believe this closes issue #2835.
On Android, merging options to open a menu works.
```
Navigation.mergeOptions(currentComponentId, {
sideMenu: {
left: {
visible: true
}
}
})
```
But merging options to close it wasn't working.
```
Navigation.mergeOptions(currentComponentId, {
sideMenu: {
left: {
visible: false
}
}
})
```
The bottom tabs controller was reserving a margin space for the bottom tabs when switching from one to another, regardless of its visibility settings.

A few improvements for Android

---

docs/usage.md

One-line fix to a broken link in`docs/usage.md` to `Screen API`

Fixes broken link to Screen API page in docs/usage.md

---

docs/installation-ios.md

The links were pointing to the wrong documentation sections.

Fix screenshots links to React Native's docs

---

android/app/src/main/java/com/reactnativenavigation/NavigationApplication.java
android/app/src/main/java/com/reactnativenavigation/react/NavigationReactGateway.java

Now allowing a `UIImplementationProvider` to be passed by overriding the `getUIImplementationProvider` method.
Inside `MainApplication.java` we can now override:
```
@Override
protected UIImplementationProvider getUIImplementationProvider() {
return CalendarPackage.getCustomUIImplementationProvider(); // <-- pass a ui implementation provider here.
}
```
And [here's the custom UIImplementation provider](https://gist.github.com/SudoPlz/23ea2dee9772cb39e1e742034cdf8b98) we used after all (for fixing all our  https://github.com/wix/react-native-navigation/issues/2892#issuecomment-393509428 related issues)

Exposed getUiImplementationProvider for people to override if needed

---

docs/README.md

A similar link would be React Native's [navigation guide](https://facebook.github.io/react-native/docs/0.54/navigation.html).

Remove broken link in README

---

playground/src/screens/WelcomeScreen.js

I think this was just a typo. After changing title to text, and setting visible to true. the 'My Screen' text displays.

The title child property is 'text' not 'title'.

---

docs/docs/events.md
lib/ios/RNNEventEmitter.h
lib/ios/RNNEventEmitter.m
lib/ios/RNNRootViewController.h
lib/ios/RNNRootViewController.m
lib/ios/RNNTopBarOptions.m
lib/src/components/ComponentWrapper.test.tsx
lib/src/components/ComponentWrapper.tsx
lib/src/events/ComponentEventsObserver.test.ts
lib/src/events/ComponentEventsObserver.ts

Summary: This adds a new event `onSearchBarCancelPressed` that fires when the user presses the cancel button on the search bar in the navigation bar. `onSearchBarUpdated` does indirectly fire when the user presses cancel, as the query will be reset to an empty string, but it is not possible to distinguish those events from the user simply resetting the query. My use case for this is to have a view that appears on top of the normal content of the view controller when the search bar is focused.
This is my first pull request, so let me know if I'm doing anything wrong! I tried to adhere to the style in files as I found it.
Test Plan: ran `npm run test-js` and confirmed added JS unit tests passed.
I also tested this with my app, and confirmed the `onSearchBarCancelPressed` method was called …

[v2][ios] add onSearchBarCancelPressed Event

---

docs/docs/Installing.md

I was unable to compile my android app because I use multidex this line of code forces the multidex library to be version 25.4.0 when the latest for this one is 1.0.3:
```groovy
if (requested.group == 'com.android.support') {
details.useVersion "25.4.0"
}
```
This little fix may save some headches:
```groovy
if (requested.group == 'com.android.support' && requested.name != 'multidex') {
details.useVersion "25.4.0"
}
...
dependecies {
...
implementation 'com.android.support:multidex:1.0.3'
implementation "com.android.support:appcompat-v7:25.4.0"
implementation 'com.android.support:design:25.4.0'
...
}
```

[V2] Update Android Install Dependencies Docs with Multidex Fix

---

lib/ios/RNNSplashScreen.m

- Support storyboards on iOS
- By trying to load a storyboard before loading the nib, it fixes having a red box with a white background
If we try to load the nib first (which fails because it doesn't exist) and load the storyboard after that, the red box dialog of React Native is broken because the table view has a white background. It is caused by the `[[NSBundle mainBundle] loadNibNamed:launchStoryBoard owner:self options:nil][0]` statement although we cannot figure out why. Changing the order fixes it, that is also done in React Native Navigation v1.

Support storyboards in the splash screen & fix white red box on iOS

---

lib/android/app/src/main/java/com/reactnativenavigation/NavigationActivity.java
lib/android/app/src/main/java/com/reactnativenavigation/react/BundleDownloadListenerProvider.java
lib/android/app/src/main/java/com/reactnativenavigation/react/DevBundleDownloadListenerAdapter.java
lib/android/app/src/main/java/com/reactnativenavigation/react/JsDevReloadHandler.java
lib/android/app/src/main/java/com/reactnativenavigation/react/NavigationReactNativeHost.java
lib/android/app/src/main/java/com/reactnativenavigation/react/ReactGateway.java
lib/android/app/src/main/java/com/reactnativenavigation/react/ReloadHandler.java
lib/android/app/src/main/java/com/reactnativenavigation/react/ReloadListener.java
lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/Navigator.java
lib/android/app/src/test/java/com/reactnativenavigation/react/ReloadListenerTest.java
lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/NavigatorTest.java
playground/src/screens/PushedScreen.js

Until now, RNN unmounted components in `reactContextInitialized` event - which appears to be too late and results in mounted components entering some limbo state for a short time where there are two mounted instances of each mounted component.
This PR adds a listener to bundle load events, when bundle is loaded successfully, we unmount any existing components.
Related to #3472

Unmount react views when bundle load completes

---

docs/docs/styling.md

`largeTitle: true` is not valid and throws error

[Docs] Update styling

---

ios/RCCViewController.m

I think this pull request for revert is not sufficient.
https://github.com/wix/react-native-navigation/pull/3441
ver 1.1.475
This error occurred.
```
/react-native-navigation/ios/RCCViewController.m:208:14: error: property 'rootView' not found on object of type 'RCCViewController *'
if (self.rootView != nil) {
^
```
So I remove undefined rootView.
Please confirm my pull request.

Remove undefined rootView

---

ios/RCCViewController.m

Sorry, this pull request I created yesterday and merged same day is not sufficient...
https://github.com/wix/react-native-navigation/pull/3441
```
if (self.view != nil){
-        RCTRootView *rootView = self.view;
-        NSString *screenName = [rootView moduleName];
```
This condition is always true. So, when we reload simulator (cmd + r) app reset and back to home of simulator.
I modify my commit, so please check.

Fix app crash bug when reload [cmd + r]

---

lib/android/app/src/main/java/com/reactnativenavigation/presentation/StackOptionsPresenter.java
lib/android/app/src/main/java/com/reactnativenavigation/views/topbar/TopBar.java
lib/android/app/src/main/res/values/styles.xml

When no theme is provided, AppBarLayout styles itself programmatically. What happens is that because these tasks are done asynchronously based on events, its call for "setElevation" equivalent can run after RNN calls!
I'm proposing a fix for #3582 that create a style for TopBar where elevation=0 and make RNN responsible to set that 4dp elevation value which is default to Android.

Fixes AppBarLayout delayed init of elevation (issue #3582)

---

docs/docs/events.md

The name of the event handler of the topBar for iOS, does not start with ```on```

Fix error in docs: onSearch event handler

---

lib/android/app/src/main/java/com/reactnativenavigation/parse/SideMenuOptions.java
lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/SideMenuController.java
lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/SideMenuControllerTest.java

Dear Maintainers,
Thanks for the awesome library.
Hereby my pull request for adding height and width options for Android. The width option already worked for IOS and this PR makes it consistent.
The options can be set in sideMenu for left and/or right, i.e.: `options { sideMenu: { left: { width: 200 } }.`
It is a minor change in SideMenuOptions and SideMenuController. Nevertheless, I've added unit tests to SideMenuControllerTest. I also ran yarn test-all without any issues.
Please let me know if any changes are necessary.
Cheers, Derk

[v2][Android] Add sideMenu height and width options for consistency with IOS

---

android/app/src/main/java/com/reactnativenavigation/views/LeftButton.java

When change a left button's id from `back` to `cancel`, the event for click is still `back` in the animation duration. That is to say, click the button that seems to have became a `x` will still pop the screen.
So I think it's necessary to prevent user interaction in the duration to prevent unexpected interactions.

Prevent user interaction until animation stopped on Android's left button

---

docs/docs/options-migration.md

On *Migration from V1 › Options* the `navBarTextFontSize` to `topBar title fontSize` example was set to `'red'`, this PR changes it to the default value, 18.

[v2] Fix migration topBar fontSize example on docs

---

lib/android/app/src/main/java/com/reactnativenavigation/parse/LayoutFactory.java
lib/android/app/src/main/java/com/reactnativenavigation/presentation/StackOptionsPresenter.java
lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/ComponentViewController.java
lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/ParentController.java
lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/SideMenuController.java
lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/ViewController.java
lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/bottomtabs/BottomTabsController.java
lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/stack/StackController.java
lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/stack/StackControllerBuilder.java
lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/topbar/TopBarController.java
lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/toptabs/TopTabsController.java
lib/android/app/src/main/java/com/reactnativenavigation/views/StackLayout.java
lib/android/app/src/main/java/com/reactnativenavigation/views/titlebar/TitleBar.java
lib/android/app/src/main/java/com/reactnativenavigation/views/topbar/TopBar.java
lib/android/app/src/test/java/com/reactnativenavigation/BaseTest.java
lib/android/app/src/test/java/com/reactnativenavigation/TestUtils.java
lib/android/app/src/test/java/com/reactnativenavigation/mocks/SimpleViewController.java
lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/BottomTabsControllerTest.java
lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/OptionsApplyingTest.java
lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/StackOptionsPresenterTest.java
lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/TitleBarTest.java
lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/TopBarControllerTest.java
lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/stack/StackControllerTest.java
lib/android/app/src/test/java/com/reactnativenavigation/views/TopBarBackgroundComponentTest.java
lib/android/app/src/test/java/com/reactnativenavigation/views/TopBarTest.java

Currently TopBar title component, background and buttons are unmounted when a new screen is pushed to the stack.
This causes a bug when props are passed to these components as props are cleared when child components unmount. When navigating back to a screen which passed props to the component, the are missing as the component is recreated in native but props were already cleared in Js.
This commit fixes this bug only for title components.

Unmount title view when corresponding child component is unmounted

---

docs/docs/Installing.md

In React-Native v51+ the bundle roots are no longer platform specific (`index.ios` or `index.android`). In the current versions there is only one `index.js` file for both platforms. Yet in the provided `AppDelegate.m` file the `jsBundleURLForBundleRoot` is still written as `index.ios`. If you try to build from this documentation with `react-native` v56 you will get the following error from MetroBundler: `UnhandledPromiseRejectionWarning: Error: File not found: index.ios.js in any of the project roots (/Users/skingman/projects/niche-mobile-app)`. It should be looking for `index.js`. I assume this would be the case for the other supported versions of `react-native` (51+).

Update Installing.md with proper name for Bundle Root

---

android/app/src/main/java/com/reactnativenavigation/NavigationApplication.java
android/app/src/main/java/com/reactnativenavigation/react/NavigationReactGateway.java

`com.facebook.react.uimanager.UIImplementationProvider` has been removed as of react-native@0.57 ([commit](https://github.com/facebook/react-native/commit/506f92083806e91a90d9a213bcdd05ab3b2ba888)), breaking react-native-navigation v1 on android.
Hence removing the usage of UIImplementationProvider in react-native-navigation.
I know, all your efforts are on v2 already, but it would be great not to see v1 compatibility with react-native break too soon. :)

[v1][Android] react-native v.0.57 compatibility / remove deprecated UIImplementationProvider

---

docs/_sidebar.md

Added a header to the sidebar to indicate that this is the V1.1.X documentation and added a link to the V2 docs.
I know of at least one other person who waisted a few hours because they didn't realize they were looking at the wrong docs, so I thought that this header and link might be of some use.

Add link to V2 Documentation

---

android/app/build.gradle

when compileSdkVersion is 25, below error was occured in react native 0.56.0.
"No resource found that matches the given name: attr 'android:keyboardNavigationCluster'"
so i have to change compileSdkVersion to 26.
Please add this push on your repository.
Thanks

Update compileSdkVersion version

---

lib/ios/ReactNativeNavigation.xcodeproj/project.pbxproj

Reverts wix/react-native-navigation#3774
This caused xcode archiving failure.

Revert "Duplicate headers copy fix"

---

package.json

Fix crash when using the new `registerComponentWithRedux` API
https://github.com/wix/react-native-navigation/pull/3675#issuecomment-413923307

update hoist-non-react-statics to 3.x.x

---

docs/docs/third-party.md

The actual `registerComponentWithRedux` function definition is the following:
```
registerComponentWithRedux(componentName, getComponentClassFunc, ReduxProvider, reduxStore) {
return this.componentRegistry.registerComponent(componentName, getComponentClassFunc, ReduxProvider, reduxStore);
}
```
Note the order of `store` and `provider` are the opposite as shown in the original documentation.  This will fix it, but it's worth mentioning that v1 has the order shown in the original documentation, so it would be nice to keep the parameter order the same in v2.
I also capitalized Provider as it is a React Component.

[V2] Fix order of `registerComponentWithRedux` arguments in Third Party documentation

---

lib/src/interfaces/Layout.ts

I have added number to be valid screen name too because then you can easily use enums to define your screen. Like this
```
export enum Screen {
Login = 1,
Home,
Settings,
}
```
This way I just add new enum name and it will generate new id (number) for it. This reduces boilerplate when defining screen names

Allow also number to be passed

---

docs/docs/styling.md
lib/android/app/src/main/java/com/reactnativenavigation/parse/BottomTabsOptions.java
lib/android/app/src/main/java/com/reactnativenavigation/presentation/BottomTabsOptionsPresenter.java
lib/src/interfaces/Options.ts

- Add Android specific options elevation in BottomTabs
- Update docs with new styling option (ahbottomnavigation use by default 8dp elevation)

Add BottomTabs elevation option

---

android/app/build.gradle
android/build.gradle

I know you guys are focusing on v2, but Android 9.0 was released and v2 was not yet ready, so this commit supports latest Android version.
If you try `react-native-navigation` with Android 9.0, it simply doesn't work (white screen, React context not loaded). 
Can you give this PR a chance?

Support Android 9.0 Pie and update buildToolsVersion

---

android/app/src/main/java/com/reactnativenavigation/bridge/NavigationReactModule.java
android/app/src/main/java/com/reactnativenavigation/controllers/NavigationActivity.java

The changes in this PR are to address #2331 & Microsoft/react-native-code-push#1144.
I've tried it on a few devices and it seems to consistently prevent the crash from occurring; that said, I'm a bit wary that the `runOnUiThread` is introducing a race condition that may fail to prevent the bug under the right circumstances. Any thoughts on tackling this (potential) issue?
Edit: I should also mention I'm aware that V1 PRs are not being accepted at this time, but wanted to submit this at least for others that are struggling with this bug to implement the solution on their forks.

Destroy navigation activity layouts on catalyst instance destroy

---

android/app/src/main/java/com/reactnativenavigation/controllers/NavigationActivity.java

When the navigation activity is killed/restarted by the system, onCreate launches the SplashActivity and kills itself. The new SplashActivity starts context initialization but that is broken in between by the onDestroy of the NavigationActivity we just killed. This fix adds a boolean to disable destruction of js in this case.

Hack to fix when app is stuck on the splash screen.

---

docs/_sidebar.md

The [For V2 docs click here](https://wix.github.io/react-native-navigation/#/) link in the V1 documentation now directly send you to the V2 docs.

Update link to directly point to v2 documentation

---

docs/docs/Installing.md

Updates the instructions to use the latest version of React Native 0.57 'reactNative57' instead of 'reactNative56'.  Using reactNative56 prevented me from creating an Android Build.

Update Android Instructions to reactNative57

---

docs/docs/styling.md

Missing `color` property in the styling docs for the topBar background color.

Missing 'color' property

---

docs/README.md
docs/docs/options-migration.md

Implemented here https://github.com/wix/react-native-navigation/commit/126f31c2fbf2a59b18ff8cf07f6d6c66fd0834ad
In use by playground: https://github.com/wix/react-native-navigation/blob/v2/playground/src/screens/ModalScreen.js#L15

[V2] Checking off statusbarhidden for Android

---

ReactNativeNavigation.podspec
package.json

I am assuming that OCMock is a test only dependency and should not be included into the compiled pod which fails to compile.

[v2] [iOS] Remove OCMock files from being compiled into pod

---

docs/docs/styling.md
lib/src/interfaces/Options.ts

Title alignment works on Android; however, the OptionsTopBarTitle interface (in Options.ts) is missing the optional alignment field preventing us to use that option.
```
topBar: {
title: {
alignment: "center"
}
},
```

[Fix typescript] Add title alignment to OptionsTopBarTitle

---

docs/docs/styling.md
lib/ios/RCTConvert+SideMenuOpenGestureMode.h
lib/ios/RNNSideMenuController.m
lib/ios/RNNSideMenuOptions.h
lib/ios/RNNSideMenuOptions.m
lib/ios/RNNSideMenuPresenter.m
lib/ios/ReactNativeNavigation.xcodeproj/project.pbxproj
lib/ios/ReactNativeNavigationTests/RNNSideMenuPresenterTest.m
lib/ios/SideMenuOpenGestureModeParser.h
lib/ios/SideMenuOpenGestureModeParser.m
lib/ios/SideMenuOpenMode.h
lib/ios/SideMenuOpenMode.m
lib/src/interfaces/Options.ts

Until now controlling drawers touch gestures was impossible, drawers received gesture opening touch from the entire screen and that causes collisions with other gestures (which are implemented on the javascript side).
This commit adding modes for how sideMenu drawers gestures will receive opening touch.
```
{
sideMenu: {
openGestureMode: 'entireScreen' | 'bezel'
}
}
```
- `entireScreen`: drawer gesture will trigger drawer opening from the entire screen
- `bezel`: drawer gesture will trigger drawer opening only from the center screen bezel frame
The default didn't change.

Add sideMenu.openGestureMode option

---

docs/docs/screen-api.md
playground/src/screens/PushedScreen.js
playground/src/screens/WelcomeScreen.js

Seems like there are still some leftover 'enable' properties that should be 'enabled'.
While Android allows both 'enable' and 'enabled', it seems iOS does not and it's causing some minimal confusion.

Clean up last 'enable' properties

---

lib/src/interfaces/Options.ts

Based on my investigation, it looks like props can be passed to top bar buttons. If so, we should expose that in the types.
I modeled this off of other top bar options, but should this actually just be `LayoutComponent`?

[V2] Add props to TopBarButton type

---

lib/ios/RNNBridgeManager.h
lib/ios/RNNBridgeManager.m
lib/ios/RNNCommandsHandler.h
lib/ios/RNNCommandsHandler.m
lib/ios/RNNSplashScreen.h
lib/ios/RNNSplashScreen.m
lib/ios/ReactNativeNavigation.m
lib/ios/ReactNativeNavigationTests/RNNCommandsHandlerTest.m

Change the way main window application is created in order to initialize commandsHandler with this window instance in order to avoid inconsistency in overlays window management and separate between those two components.

Initialize and pass mainWindow to commandsHandler

---

docs/docs/styling.md

the generic buttonColor doesn't work for android. Backbutton color is not documented, see [#3454](https://github.com/wix/react-native-navigation/issues/3454)

Include missing backButton prop for android

---

lib/android/app/build.gradle
lib/android/app/src/main/java/com/reactnativenavigation/presentation/BottomTabPresenter.java
lib/android/app/src/main/java/com/reactnativenavigation/presentation/BottomTabsPresenter.java
lib/android/app/src/main/java/com/reactnativenavigation/utils/ImageLoader.java
lib/android/app/src/main/java/com/reactnativenavigation/utils/Time.java
lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/bottomtabs/BottomTabsController.java
lib/android/app/src/main/java/com/reactnativenavigation/views/BottomTabs.java
lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/BottomTabPresenterTest.java
lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/BottomTabsControllerTest.java
lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/navigator/NavigatorTest.java

The BottomTabs library we use recreates its children each time a style property changes.
This can hinder performance quite a bit as the view creation logic is quite costly.
This commit introduces a simple fix to this issue - we delay view creation until all options are applied.
Additional changes
* Prevent view recreation in `onSizeChanged`
* Cleanup `createTabs` method

Create bottom tabs once

---

lib/ios/RNNNavigationController.m
lib/ios/RNNSideMenuChildVC.m
lib/ios/RNNSideMenuController.m
lib/ios/ReactNativeNavigationTests/RNNNavigationControllerTest.m

Stop override tabBarItem by parent layouts as options are now propagated to all tree and handled by each layout presenter

Stop override tabBarItem by parent layouts

---

docs/README.md
docs/index.html

There has been a couple of complaints on Discord and issue #4473  about the documentation website not rendering properly.
This PR does the following:
- Anchored Docsify versions to 4.7.1 ( Docsify Github issues show there might be some rendering problems with 4.8.3)
- Anchor docsify-copy-plugin to 2
- Remove deprecated docsify-copy-code stylesheet
- Remove deprecated docsify-copy-code init function 
- Use HTTPS for all script loading
- Fix path for Working Locally

Documentation website maintenance

---

lib/src/adapters/AssetResolver.ts
lib/src/adapters/Element.tsx
lib/src/adapters/NativeCommandsSender.ts
lib/src/adapters/NativeEventsReceiver.ts
lib/src/adapters/TouchablePreview.tsx
lib/src/commands/OptionsProcessor.test.ts

This PR continues the work on making this project type safe with TypeScript. Goal is that the flag `noImplicitAny` will be set to `true`
- all files inside `adapter` folder is valid for `noImplicitAny`!
- `resolveAssetSource` is now imported from the current place where it should. Previously it was imported from legacy location. More info here: https://facebook.github.io/react-native/docs/image#resolveassetsource
- formatted many files
- add missing interfaces
- fix `onPressIn` prop on `TouchablePreview`
Next I am planning to make same treatment for `commands` folder and many it valid for `noImplicitAny` 🎉

Road to implicitAny part 4

---

lib/src/interfaces/Options.ts

using OptionsModalPresentationStyle would pass a number instead of string to modalPresentationStyle.
The reason is OptionsModalPresentationStyle is defined as a numeric enumeration.
I fixed OptionsModalPresentationStyle as a string enum

Fixed the bug that number will be passed to modalPresentationStyle when using OptionsModalPresentationStyle

---

lib/ios/RNNSideMenuChildVC.h
lib/ios/RNNSideMenuChildVC.m
lib/ios/RNNSideMenuController.m
lib/ios/ReactNativeNavigation.xcodeproj/project.pbxproj
lib/ios/ReactNativeNavigationTests/RNNSideMenuControllerTest.m
lib/ios/ReactNativeNavigationTests/RNNSideMenuPresenterTest.m

Setting react view according to the provided `sideMenu.{side}.width`.
When `sideMenu.{side}.width` isn't supplied, the react view will fill the screen.

Fix sideMenu intuitive side width - #4527

---

lib/src/interfaces/Options.ts

Some styling options are missing on https://github.com/wix/react-native-navigation/blob/master/lib/src/interfaces/Options.ts.
So I got warnings when I use them from typescript.
I added some types what existed on the Objective-C source and  possible to use.

Added missing types

---

docs/docs/animations.md

This is the Information I needed to figure out how to implement Peek and Pop previews. Since the rest of the documentation is fairly concise I was wondering wether it would be appropriate to include "recipe" type things, like disabling scroll during preview, reacting to preview state in the previewed screen etc here or maybe in some other section?

Document options for Peek & Pop

---

lib/android/app/src/main/java/com/reactnativenavigation/parse/TitleOptions.java
lib/android/app/src/test/java/com/reactnativenavigation/parse/OptionsTest.java

When setting the height of the title, it was not being parsed/set on the Android side.
```js
static options() {
return {
topBar: {
title: {
text: "Title",
height: 100
},
}  
}
}
```

[Android] Fix title height not being set on Android

---

lib/android/app/src/main/java/com/reactnativenavigation/parse/BottomTabsOptions.java
lib/android/app/src/main/java/com/reactnativenavigation/parse/LayoutFactory.java
lib/android/app/src/main/java/com/reactnativenavigation/parse/TabsAttachMode.java
lib/android/app/src/main/java/com/reactnativenavigation/presentation/OverlayManager.java
lib/android/app/src/main/java/com/reactnativenavigation/utils/CollectionUtils.java
lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/ViewController.java
lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/bottomtabs/AfterInitialTab.java
lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/bottomtabs/AttachMode.java
lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/bottomtabs/BottomTabsAttacher.java
lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/bottomtabs/BottomTabsController.java
lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/bottomtabs/OnSwitchToTab.java
lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/bottomtabs/Together.java
lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/modal/ModalPresenter.java
lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/navigator/RootPresenter.java
lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/stack/StackController.java
lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/topbar/TopBarController.java
lib/android/app/src/test/java/com/reactnativenavigation/BaseTest.java
lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/TopBarControllerTest.java
lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/bottomtabs/BottomTabsAttacherTest.java
lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/bottomtabs/BottomTabsControllerTest.java
lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/bottomtabs/attachmode/AfterInitialTabTest.java
lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/bottomtabs/attachmode/AttachModeTest.java
lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/bottomtabs/attachmode/OnSwitchToTabTest.java
lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/bottomtabs/attachmode/TogetherTest.java
lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/modal/ModalPresenterTest.java
lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/navigator/NavigatorTest.java
lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/navigator/RootPresenterTest.java
lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/stack/StackControllerTest.java
lib/src/interfaces/Options.ts

This pr adds support for changing tab initialisation mode. Currently bottom tabs are attached together and consequently, their corresponding react root views are created and rendered. This adds lots of stress on the js thread and hiders app start time.
To mitigate this issue, this pr adds support for three modes
* `together` (default, current behaviour) - all tabs are loaded together, adding unnecessary load on the js thread as we're loading invisible views, which leads to increased app start time.
* `afterInitialTab` - Initial tab is loaded first. After it is rendered, other tabs are loaded as well. This should shave a few hunderdish ms from app start time. Since other tabs are loaded after the initial tab is visible, the ui might be unresponsive for a few hunderdish ms as multiple root …

Bottom tabs attach mode

---

docs/docs/layout-types.md
lib/ios/RNNNavigationOptions.h
lib/ios/RNNNavigationOptions.m
lib/ios/RNNSplitViewController.m
lib/ios/RNNSplitViewOptions.m
lib/src/commands/LayoutTreeParser.test.ts
lib/src/interfaces/Layout.ts
lib/src/interfaces/Options.ts

The bottomTab settings were not being properly applied if a SplitView
controller was nested. Part of this seems to be that the 'options' for
SplitView were in their V1 form, i.e. they did not have access to the
full topBar/bottomTab/etc.
I refactored the options to be in their own sub object. NOTE: the
settings for `splitView` are not being applied currently -- they weren't
before and they still are not being respected now.
With access to the full options now, I was able to change
RNNSplitViewController to properly override
willMoveToParentViewController to get the bottomTab icon to properly
show up.
I would love to get the actual `splitView` settings to properly work, but I need some guidance on how to do that in the new Presenter framework.  Since this seems to be no worse off than …

Refactor SplitView options and make them work with Tabs

---

lib/ios/Constants.m

Pulls the height from the root UITabBarController.
Fixes #4190

Pull from the root TabBarController height

---

docs/docs/options-migration.md

Although it was quite obvious after, it wasn't mentioned that translucent: true was required for navBarBlur to work.
Also, I think adding required options to the JS snippets make this easier to follow.

Improve navBarBlur and navBarTranslucent documentation

---

lib/ios/RNNButtonOptions.h
lib/ios/RNNButtonOptions.m
lib/ios/RNNInsetsOptions.h
lib/ios/RNNInsetsOptions.m
lib/ios/RNNNavigationButtons.m
lib/ios/RNNUIBarButtonItem.m
lib/ios/ReactNativeNavigation.xcodeproj/project.pbxproj
lib/ios/UIImage+insets.h
lib/ios/UIImage+insets.m
lib/src/interfaces/Options.ts

```js
{
topBar: {
rightButtons: [{
id: '',
icon: 'require()'
iconInsets: {
top: 0,
left: 8,
bottom: 0,
right: 8
}
}]
}
}
```

Add Icon insets support for buttons

---

docs/docs/showcases.md

Doing `git clone -b v2 git@github.com:wix/react-native-navigation.git` gives me this:
```
fatal: Could not read from remote repository.
Please make sure you have the correct access rights and the repository exists.
```

changed the link to clone the library

---

lib/src/components/Store.ts

Using loads.set caused issues when keys contained the dot symbol. _.set created objects inside the store, which is intended to be a simple key value dictionary -
In some cases, set would overwrite previously set values.

Stop using lodash in store.js

---

lib/ios/RNNUIBarButtonItem.m

| Before | After |
| --- | --- |
| <img width="689" alt="screen shot 2019-02-13 at 4 57 20 pm" src="https://user-images.githubusercontent.com/1051453/52748874-aaa46f80-2fb5-11e9-8310-abd157ec3d4e.png"> | <img width="689" alt="screen shot 2019-02-13 at 5 34 54 pm" src="https://user-images.githubusercontent.com/1051453/52748891-b7c15e80-2fb5-11e9-9f4c-f0503055acc5.png"> |
Note the position of the custom `UIBarButtonItem` in the first image.
This fixes an issue where the `frame` for the custom view can be set to the incorrect y-offset upon setting the custom `frame`.
In iOS 11, this behavior changed, as `UIBarButtonItem` went from being using springs-and-struts for sizing, to using a `UIStackView` internally, and thus using Autolayout.
This lead to the superview of having a `frame` of `(0, …

[v2] [iOS] Use autolayout constraints to set size of custom bar button item

---

android/app/src/main/java/com/reactnativenavigation/controllers/NavigationActivity.java

Hi,
I was running into an annoying issue while trying to ask user permissions in my home screen on android (I have a map on the Deals maps screen so I need to ask the user for his location). I am using react-native-maps and since it requires location permission so when the user accepts or decline the permission, user will end up with the error `Tried to use permissions API while not attached to an Activity`.
So after some investigations I realize that when the native permissions pop up shows up, the app is put in pause and the `currentActivity` is null. I forgot to mention that I have a Login flow first and at the end I call `startSingleScreenApp` so the first activity is destroyed and replaced by the new one. The problem here is that the `onDestroy` callback is called after the `onPause` …

Prevent unwanted app destroy on Android

---

lib/android/app/src/main/java/com/reactnativenavigation/utils/ImageLoader.java

When loading local image resource (images in Drawable folder), RNN mistakingly tried to load the image as a js asset even if it successfully loaded the local image.
Using locals Drawables:
```js
rightButtons: [
{
id: 'btn',
icon: { uri: 'myImageFromDrawablesFolder' }
}
]
```
Related to (possibly fixes) #4751

Fix loading local images

---

lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/sidemenu/SideMenuController.java

Problem:
On Android, If the drawer is closed via options. The open gesture mechanism is broken. The drawer will snap shut on open.
Android Fix
Update the side menu visibility option during the open / close callback
In relation to 
https://github.com/wix/react-native-navigation/issues/4696
https://github.com/wix/react-native-navigation/issues/4636

Update side menu options on open / close callback - Android

---

ios/RCCManager.h
ios/RCCManager.m

Hello. On iOS to add the modules from Expo (https://github.com/unimodules/core) we need to provide extra bridge modules (https://gist.github.com/brentvatne/949d9cc3508cc45f54af5196b3ca497b/revisions) so we need custom bridge delegate.  
v1 RCCManager doesn't use bridge delegate, and since v1 won't have new features, so I assume it won't use the delegate in the future. It looks like this situation with delegates are handled in a better way in v2, but we are still stuck on v1.
If you agree to merge this one and you think it's better to follow the single source of truth in this case, I can refactor the code to make 1 method with 3 params which will know how to construct the bridge and the other methods will just call it.

[v1] [iOS] Add init bridge with custom delegate

---

lib/ios/RNNReactRootViewCreator.m
lib/ios/RNNReactView.h
lib/ios/RNNReactView.m
lib/ios/RNNRootViewController.m
lib/ios/RNNRootViewCreator.h

This bug was created when we removed this: https://github.com/wix/react-native-navigation/commit/5abea28c53ed34dc822641f30abe2190c08f8185#diff-cfad79521862e2b3122aaabaf57b701bL124

Fixes initial screen size

---

package.json

uilib is used only in the playground app and was added by mistake to dependencies.
Fixes #4805

Move uilib to devDependencies

---

lib/android/app/src/main/java/com/reactnativenavigation/anim/NavigationAnimator.java
lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/stack/StackController.java
lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/stack/StackControllerTest.java

When popToRoot or popTo were called while a screen was pushed, at the end of the push animation RNN tried to destroy an already destroyed ViewController.
Related to #3767

Cancel in-flight push animation on pop

---

lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/stack/StackController.java
lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/stack/StackControllerTest.java

Previous push animation wasn’t cancelled, when it ended the controller tried
to destroy previous view which was already destroyed.
Related to #3767

Fix crash when calling setStackRoot multiple times in quick succession

---

lib/src/interfaces/Layout.ts

extenalComponent?: ExternalComponent was not an option for interfaces LayoutStack and LayoutStackChildren, despite being valid.

Added ExternalComponent where missing

---

lib/android/app/src/main/java/com/reactnativenavigation/parse/Options.java
lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/ViewController.java
lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/bottomtabs/BottomTabsControllerTest.java
lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/sidemenu/SideMenuControllerTest.java

This fixes issue: #4696 
Behaviour before:
Behaviour after:

Clear sideMenu's visible options after applying

---

lib/ios/RNNBasePresenter.h
lib/ios/RNNBasePresenter.m
lib/ios/RNNBridgeManager.m
lib/ios/RNNControllerFactory.m
lib/ios/RNNNavigationControllerPresenter.h
lib/ios/RNNNavigationControllerPresenter.m
lib/ios/RNNReactComponentRegistry.h
lib/ios/RNNReactComponentRegistry.m
lib/ios/RNNReactView.m
lib/ios/RNNSplitViewControllerPresenter.m
lib/ios/RNNTopBarOptions.m
lib/ios/RNNViewControllerPresenter.h
lib/ios/RNNViewControllerPresenter.m
lib/ios/ReactNativeNavigationTests/RNNBasePresenterTest.m
lib/ios/ReactNativeNavigationTests/RNNTabBarPresenterTest.m
lib/ios/ReactNativeNavigationTests/RNNViewControllerPresenterTest.m

Until now, components registry held a weak reference to react view components. This resulted in unexpected detaching react views behaviour.
This PR moves the attaching and detaching components from the registry to the presenters, providing explicit behaviour.
Fixes #4929

Handle adding and removing components from registry manually by presenters

---

docs/docs/styling.md

- Fix typo for *popOver* value of *modalPresentationStyle*. Should be *popover* (lowercase)
- *topBar.buttonColor* is not works, but *leftButtonColor* and *rightButtonColor* instead works perfect

Update docs styling.md for modalPresentationStyle and topBar.buttonColor

---

lib/ios/RNNCommandsHandler.m
lib/ios/RNNOverlayManager.h
lib/ios/RNNOverlayManager.m
lib/ios/RNNOverlayOptions.h
lib/ios/RNNOverlayOptions.m

```
Navigation.showOverlay(Screens.OverlayAlert, {
overlay: {
handleKeyboardEvents: true
}
});
```
Resolves #4824

Add overlay.handleKeyboardEvents options

---

lib/ios/RNNBasePresenter.m
lib/ios/RNNControllerFactory.m
lib/ios/RNNLayoutProtocol.h
lib/ios/RNNRootViewController.m
lib/ios/RNNSideMenuChildVC.h
lib/ios/RNNSideMenuChildVC.m
lib/ios/RNNTopTabsViewController.m
lib/ios/RNNViewControllerPresenter.m
lib/ios/ReactNativeNavigationTests/RNNCommandsHandlerTest.m
lib/ios/ReactNativeNavigationTests/RNNNavigationControllerTest.m
lib/ios/ReactNativeNavigationTests/RNNRootViewControllerTest.m
lib/ios/ReactNativeNavigationTests/RNNSideMenuControllerTest.m
lib/ios/ReactNativeNavigationTests/RNNTabBarControllerTest.m
lib/ios/ReactNativeNavigationTests/UIViewController+LayoutProtocolTest.m
lib/ios/UIViewController+LayoutProtocol.m

• Fix top bar component layout frame size - Closes #5003
• Clean duplicate initWithLayoutInfo implementations
• Initialize parent child controllers in the constructors and not with `setViewControllers`

Fix top bar layout frame

---

lib/ios/InteractivePopGestureDelegate.m

In very specific cases, there may be multiple gesture recognizers active, which will result in `InteractivePopGestureDelegate` being sent the `shouldRecognizeSimultaneouslyWithGestureRecognizer` selector, which it does not respond to, resulting in the following exception:
```
-[InteractivePopGestureDelegate gestureRecognizer:shouldRecognizeSimultaneouslyWithGestureRecognizer:]: unrecognized selector sent to instance 0x600000fb9560
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[InteractivePopGestureDelegate gestureRecognizer:shouldRecognizeSimultaneouslyWithGestureRecognizer:]: unrecognized selector sent to instance 0x600000fb9560'
*** First throw call stack:
(
0   CoreFoundation                      0x000000010f70d6fb __exceptionPreprocess + 331
1 …
```

Handle simultaneous recognizers

---

lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/bottomtabs/BottomTabsController.java
lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/bottomtabs/BottomTabsControllerTest.java
playground/src/services/Navigation.js

When mergeOptions was called on a root view, it’s one time options weren’t cleared properly.
The entire one time options logic is terrible and has to be refactored out.
Fixes #5010

Explicitly clear bottom tabs options after mergeOptions

---

lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/YellowBoxDelegate.java
lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/YellowBoxHelper.java
lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/YellowBoxDelegateTest.java

After migrating to RN 0.59, view creation timings have changed a bit.
Seems like ruining this logic on pre draw sorts things out.
Fixes #5124

Fix YellowBox removal

---

lib/android/app/src/main/java/com/reactnativenavigation/utils/StringUtils.java
lib/android/app/src/main/java/com/reactnativenavigation/utils/UiUtils.java
lib/android/app/src/main/java/com/reactnativenavigation/views/titlebar/TitleBar.java
lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/TitleBarTest.java

When setting left button and the title was centred, it got an undesired offset.
Now whenever left button is set we make sure to realign the title.
Related to https://github.com/wix/react-native-navigation/pull/5111

Align title after left button is set

---

lib/ios/RNNNavigationControllerPresenter.m

Initialize topbar.background.component wrapper view on viewWillAppear
Closes #5138

Initialize topbar.background.component wrapper view on viewWillAppear

---

lib/src/events/ComponentEventsObserver.ts

Had an issue where a screen unmounting and remounting would cause a crash because component was null.
It seems to be caused by a race condition. I'm not totally sure where it comes from but this check makes it safer

Safer check around component listener trigger

---

lib/ios/RNNCommandsHandler.m

`setStackRoot` options should be resolve from the last presented viewController and not from `getCurrentChild` of this viewController.

Fix setStackRoot options

---

lib/ios/RNNControllerFactory.m

Possible fix for crash on ios when setting topbar left buttons with custom component.
Fixes issue #5180.

Fix crash on ios when setting topbar left buttons with custom component

---

docs/docs/Installing.md
lib/android/app/build.gradle
lib/android/app/src/reactNative60/java/com/reactnativenavigation/react/DevBundleDownloadListenerAdapter.java
lib/android/app/src/reactNative60/java/com/reactnativenavigation/react/JsDevReloadHandlerFacade.java
lib/android/app/src/reactNative60/java/com/reactnativenavigation/react/NavigationReactNativeHost.java
lib/android/app/src/reactNative60/java/com/reactnativenavigation/react/ReloadHandlerFacade.java
lib/android/app/src/reactNative60/java/com/reactnativenavigation/react/SyncUiImplementation.java

This pull request makes RNN compatible with the latest RN 0.60.0-rc.2. Since there will not be fundamental changes in the same minor version, we can assure this pull request can work for some time.
- Remove `MeasureSpecProvider` & `SizeMonitoringFrameLayout`. They no longer exist.
- Change imports to AndroidX, because RN 0.60 uses it as default.
- Add a new build flavor so users won't be effected even they stay on the old RN version.
- Update doc to demonstrate how to modify `MainApplication.java` to utilize RN new AutoLink feature.
Since there is no API change, all tests apply to this pull request as long as it passes build.

Add support for React Native 0.60

---

docs/docs/events.md

Fixing spelling of "hierarchy" and removing errant parenthesis

Fixing spelling on events doc

---

lib/ios/RNNTabBarItemCreator.m

The default value for `UITabBarItem.title` is `nil` as specified by the docs:
> You should set this property before adding the item to a bar. The default value is nil.
https://developer.apple.com/documentation/uikit/uibaritem/1616412-title
This changes allows for this to be `nil`.

Allow setting UITabBarItem.title to default value

---

lib/android/app/src/main/java/com/reactnativenavigation/presentation/Presenter.java

When setting a light status bar (grey icons on light background, `TextColorScheme.Dark`), the setting will get overridden by the order of `applyStatusBarOptions`:
```
private void applyStatusBarOptions(Options options) {
setStatusBarBackgroundColor(options.statusBar);
setTextColorScheme(options.statusBar.textColorScheme);
setTranslucent(options.statusBar);
setStatusBarVisible(options.statusBar.visible);
}
```
Since `setStatusBarVisible` is called last, and does not consider previous flags, the flag  `SYSTEM_UI_FLAG_LIGHT_STATUS_BAR` will get overridden.
This PR include previous set flags.

[v3] Dont override existing system ui visibility flags when setting statusbar visibility

---

docs/docs/options-migration.md

Fix typo in topBarElevationShadowEnabled documentation

---

lib/android/app/src/main/java/com/reactnativenavigation/parse/LayoutFactory.java
lib/android/app/src/main/java/com/reactnativenavigation/parse/parsers/JSONParser.java
lib/android/app/src/main/java/com/reactnativenavigation/react/LifecycleEventListenerAdapter.java
lib/android/app/src/main/java/com/reactnativenavigation/react/NavigationModule.java
lib/android/app/src/main/java/com/reactnativenavigation/react/NavigationPackage.java
lib/android/app/src/main/java/com/reactnativenavigation/react/NavigationReactInitializer.java
lib/android/app/src/main/java/com/reactnativenavigation/react/ReactGateway.java
lib/android/app/src/test/java/com/reactnativenavigation/parse/parsers/JSONParserTest.java
lib/android/app/src/test/java/com/reactnativenavigation/react/NavigationModuleTest.java
package.json

Under certain conditions, app launched event was emitted when the Android Activity isn't in resumed state. In this case, setting root isn't possible since ReactContext doesn't have an instance of the Activity (it can even be destroyed).
This PR ensures the event is emitted only when the Activity is resumed and root can be set.

Ensure appLaunched event is emitted only when app is resumed

---

lib/android/app/src/main/java/com/reactnativenavigation/parse/Component.java
lib/android/app/src/main/java/com/reactnativenavigation/parse/params/Button.java
lib/android/app/src/main/java/com/reactnativenavigation/parse/params/Param.java
lib/android/app/src/main/java/com/reactnativenavigation/utils/CollectionUtils.java
lib/android/app/src/main/java/com/reactnativenavigation/utils/ViewUtils.java
lib/android/app/src/main/java/com/reactnativenavigation/views/topbar/TopBar.java
lib/android/app/src/test/java/com/reactnativenavigation/views/TopBarTest.java

Like all other options, buttons are applied when a screen becomes visible. This means that in a BottomTabs layout,
options are applied when a tab is selected. Since tab change happens involves only changing view visibility, and button creation take a bit long,
the buttons appear to flicker some times.

Apply TopBar buttons only if they are different than current buttons

---

lib/android/app/src/main/java/com/reactnativenavigation/presentation/BottomTabsPresenter.java
lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/bottomtabs/BottomTabsController.java
lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/bottomtabs/BottomTabsControllerTest.java

When setting BottomTabs root, if one of the children was a stack with multiple children
and the top child in the stack had `drawBehind: true` while the bottom child had `drawBehind: false`, sometimes the tabs' bottomMargin would be wrong since it was applied in onPreDraw.

Fix rare race condition when applying bottomTabs.drawBehind

---

lib/ios/RNNCommandsHandler.m
lib/ios/ReactNativeNavigationTests/RNNCommandsHandlerTest.m

Last component in `setStackRoot` layout should consider `waitForRender` option, the other components should not be rendered because they shouldn't be presented yet and this can cause performance issues.
Closes #5355

Fixes unnecessary rendering of the last viewController in setStackRoot

---

docs/docs/Installing.md

I just generated a new react-native project with react-native 0.60.4 and the installation instructions for iOS don't work. It's much easier to install with cocoapods. I went ahead and added a "Installing with cocoapods" section to the docs.

[Docs] Installation Instructions | Add CocoaPods instructions for iOS

---

e2e/Options.test.js
lib/ios/RNNBasePresenter.h
lib/ios/RNNBasePresenter.m
lib/ios/RNNCommandsHandler.m
lib/ios/RNNNavigationController.m
lib/ios/RNNNavigationControllerPresenter.m
lib/ios/RNNRootViewController.m
lib/ios/RNNSideMenuController.m
lib/ios/RNNSideMenuPresenter.m
lib/ios/RNNTabBarPresenter.m
lib/ios/RNNViewControllerPresenter.m
lib/ios/UIViewController+RNNOptions.h
lib/ios/UIViewController+RNNOptions.m
playground/src/screens/StatusBarOptionsScreen.js

When defaultOptions are set after setRoot has been called presenters need to receive the default options as well,
otherwise the outdated default options are regarded.
Fixes #5395

Propagate new defaultOptions to presenters

---

package.json

Should fix a lot of the warnings when doing a clean install

Add @babel/core to dev dependencies as it's required by peer deps

---

src/deprecated/platformSpecificDeprecated.android.js

disableOpenGesture wasn't working as expected since parseInt(boolean) is NaN.
On RN 0.59.10 this would even crash the app since passing NaN to the bridge is not allowed.
This resolves issue #5429

Fix disableOpenGesture assignment

---

lib/ios/RNNBackButtonOptions.h
lib/ios/RNNBackButtonOptions.m
lib/ios/RNNViewControllerPresenter.m
lib/ios/UIViewController+RNNOptions.h
lib/ios/UIViewController+RNNOptions.m

The backButton options are always applied. Even when one of its values has changed in mergeOptions.
This commit adds a function to apply the backButton, and should probably replace the existing rnn_setBackButtonIcon - as that function does more than just set the icon, it sets all options.

Fix merging back button

---

lib/ios/UIViewController+RNNOptions.h
lib/ios/UIViewController+RNNOptions.m

This is already defined in UIViewController+LayoutProtocol and depending 
on the load order will actually prevent the default orders from being 
set

Remove duplicate setDefaultOptions in UIViewController categories

---

lib/android/app/src/main/java/com/reactnativenavigation/presentation/RootPresenter.java

I've seen the following crash in production. It's rare, but it appears there's some kind of race condition in `setRoot`'s `addOnAppearedListener` that results in `getView` throwing. Here's the stack trace:
```
java.lang.RuntimeException: Tried to create view after it has already been destroyed
at com.reactnativenavigation.viewcontrollers.ViewController.getView(ViewController.java:165)
at com.reactnativenavigation.viewcontrollers.ParentController.getView(ParentController.java:60)
at com.reactnativenavigation.viewcontrollers.navigator.RootPresenter.lambda$setRoot$0(RootPresenter.java:41)
at com.reactnativenavigation.viewcontrollers.navigator.-$$Lambda$RootPresenter$T5cjGG24h93OrmgUBwpekHEXTtY.run(lambda)
at com.reactnativenavigation.viewcontrollers.-$$Lambda$P7xe27l85RASi5iJcSC7JIxgcA8.on(la …
```

[V3, Android] Catch rare RuntimeException in setRoot when waitForRender = true

---

lib/ios/RNNDefaultOptionsHelper.m

There is no need to call `setDefaultOptions` on the `childViewController` while iterating the `childViewControllers` as those will be passed recursively as `rootViewController` anyway and thus calling `setDefaultOptions` in the nested recursive call.

Stop recursive double setting of default options

---

lib/ios/UIImage+tint.m

With this change, dynamic colors will be supported when tinting an image and the image color will change on the fly depending on the dynamic provider and traits. This will be especially useful when supporting the new dark mode in iOS 13.

Prefer new imageWithTintColor API when tinting an UIImage

---

playground/android/build.gradle
playground/android/gradle/wrapper/gradle-wrapper.properties

Upgrade Gradle to 5.1.1 and the Android gradle-plugin to equivalent version 3.4.1 in playground app. Biggest motivation for doing this is the [HTTP retries](https://docs.gradle.org/5.0/release-notes.html#http-retries-during-dependency-resolution) feature.
Disclaimer: the feature may not be fully functional as described [in this report to gradle](https://github.com/gradle/gradle/issues/8264). I hope it'd be ok for us nevertheless.

Upgrade playground app's Gradle to 5.1.1 (matches version of lib)

---

docs/docs/styling.md
docs/docs/topBar-buttons.md
lib/ios/RCTConvert+UIFontWeight.h
lib/ios/RNNBottomTabOptions.h
lib/ios/RNNBottomTabOptions.m
lib/ios/RNNFontAttributesCreator.h
lib/ios/RNNFontAttributesCreator.m
lib/ios/RNNLargeTitleOptions.h
lib/ios/RNNLargeTitleOptions.m
lib/ios/RNNNavigationButtons.m
lib/ios/RNNStackPresenter.m
lib/ios/RNNSubtitleOptions.h
lib/ios/RNNSubtitleOptions.m
lib/ios/RNNTabBarItemCreator.m
lib/ios/RNNTitleOptions.h
lib/ios/RNNTitleOptions.m
lib/ios/RNNTitleViewHelper.m
lib/ios/ReactNativeNavigation.xcodeproj/project.pbxproj
lib/ios/ReactNativeNavigationTests/RNNFontAttributesCreatorTest.m
lib/ios/UINavigationController+RNNOptions.h
lib/ios/UINavigationController+RNNOptions.m
lib/src/interfaces/Options.ts

This feature allow using the iOS native system font weights. Providing system font names as `.SFUIText-Heavy` are no longer supported in iOS 13.
• Add `fontWeight` support for:
• `topBar.title` option
• `topBar.largeTitle` option
• `topBar.subtitle` option
• `bottomTab` option
• `topBar.leftButtons` and `topBar.rightButtons` options
• Move all font creation to `RNNFontAttributesCreator`

Font weight option support for iOS

---

lib/ios/RNNModalManager.h
lib/ios/RNNModalManager.m

On iOS 13, when a `pageSheet` modal is dismissed with a swipe, the react view was not unmounted properly caused `componentWillUnmount` to never called.
This PR listen to this event and detach it from memory.
Closes #5370

Fix pageSheet modals causing memory leak when swiped

---

lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/ChildController.java
lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/ComponentViewController.java
lib/android/app/src/test/java/com/reactnativenavigation/mocks/SimpleViewController.java
lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/child/ChildControllerTest.java
playground/android/build.gradle
playground/src/screens/FirstBottomTabScreen.js

Until now, mergeOptions would merge with parent controller only if mergeOptions was called with
a componentId. This commit fixes the issue and makes options merge correctly even when called with a layoutId.

Always merge options with parent controller

---

lib/src/Navigation.ts
lib/src/commands/Commands.test.ts
lib/src/commands/Commands.ts
lib/src/commands/LayoutTreeCrawler.test.ts
lib/src/commands/LayoutTreeCrawler.ts
lib/src/commands/OptionsProcessor.test.ts
lib/src/commands/OptionsProcessor.ts
lib/src/components/ComponentWrapper.test.tsx
lib/src/components/Store.test.ts
lib/src/components/Store.ts
lib/src/events/ComponentEventsObserver.test.tsx
playground/src/screens/ButtonsScreen.js
playground/src/services/Navigation.js

The `Navigation.updateProps` command allows to update props for a component registered with Navigation.registerComponent.
The updated props are handled by shouldComponentUpdate and componentDidUpdate lifecycle methods.
API
```js
Navigation.updateProps('myComponentId', {
text: 'new value'
});
```
This commit builds upon the work done in 291f16177d2f67a474d3a980a503a85d0acf2b2a and is a breaking change.

[BREAKING] Introduce updateProps command

---

docs/docs/layout-types.md
lib/src/interfaces/Options.ts

When creating a new project using this library with TypeScript I noticed that the definition for `icon` with `bottomTab` was optional, but I ran into a crash on Android when I omitted it.
It appears this issue has come up several times before:
https://github.com/wix/react-native-navigation/issues/4534
https://github.com/wix/react-native-navigation/issues/4684
https://github.com/wix/react-native-navigation/issues/4990
https://github.com/wix/react-native-navigation/issues/5331
https://github.com/wix/react-native-navigation/issues/5435
https://github.com/wix/react-native-navigation/issues/5492
From what I can tell when I investigated, this library is used on Android for bottom tabs: https://github.com/aurelhubert/ahbottomnavigation
I didn't see a way to create a bottom tab without an icon in …

Add docs for bottomTab requiring icon on Android

---

lib/android/app/src/main/java/com/reactnativenavigation/presentation/Presenter.java

With the PR #5547 it is only possible to set the navigationBarColor while switching the screen.
This PR adds the possibility to change the color with a call to `Navigation.mergeOptions`

Allow navigationBarColor change within mergeOptions, addition to PR #5547

---

lib/ios/RNNBasePresenter.h
lib/ios/RNNBasePresenter.m
lib/ios/RNNCommandsHandler.m
lib/ios/RNNComponentOptions.h
lib/ios/RNNComponentOptions.m
lib/ios/RNNComponentPresenter.m
lib/ios/RNNSideMenuController.m
lib/ios/ReactNativeNavigation.xcodeproj/project.pbxproj
lib/ios/ReactNativeNavigationTests/RNNBasePresenterTest.m
lib/ios/ReactNativeNavigationTests/RNNComponentPresenterTest.m
lib/ios/ReactNativeNavigationTests/RNNSideMenuPresenterTest.m
lib/ios/ReactNativeNavigationTests/RNNStackPresenterTest.m
lib/ios/ReactNativeNavigationTests/RNNTabBarPresenterTest.m
lib/ios/UIViewController+LayoutProtocol.m

When mergeOptions was called without a title component, existing component was undesirably removed.
This commit changes how component is removed when mergeOptions is called. It will now be removed if a component is not defined and title is defined in mergeOptions.
Fixes #5628

Remove component if title is defined in mergeOptions

---

docs/docs/showcases.md
package.json
scripts/start-windows.js

Added script for the playground on windows.
On linus like systems we delete the lib/dist folder, i cant make it work with error catching if the folder does not exist.

Playground for windows

---

lib/src/interfaces/Options.ts

Looking at the docs (https://github.com/wix/react-native-navigation/blob/1581780d2ca66acebdb149751afa1bb4afc1c59e/docs/docs/styling.md) and code it's possible to use the shouldStretchDrawer property on sideMenu. This property was however missing in the TS interface.
https://github.com/wix/react-native-navigation/blob/1581780d2ca66acebdb149751afa1bb4afc1c59e/lib/ios/RNNSideMenuSideOptions.m#L11

Added shouldStretchDrawer property to SideMenuSide interface

---

lib/android/app/build.gradle
lib/android/app/src/main/java/com/reactnativenavigation/parse/BottomTabsOptions.java
lib/android/app/src/main/java/com/reactnativenavigation/presentation/BottomTabsPresenter.java
lib/src/interfaces/Options.ts

This option is used to force large icons to be displayed when only three icons, without titles, are present on the screen.

Add bottomTabs.preferLargeIcons option

---

lib/android/app/src/main/java/com/reactnativenavigation/parse/BottomTabsOptions.java
lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/ChildController.java
lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/bottomtabs/BottomTabsController.java
lib/android/app/src/test/java/com/reactnativenavigation/mocks/SimpleViewController.java
lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/bottomtabs/BottomTabsControllerTest.java

When BottomTabs are hidden, draw components behind the tabs even if drawBehind isn't set to true explicitly.

DrawBehind when tabs are hidden

---

lib/android/app/src/main/java/com/reactnativenavigation/NavigationApplication.java
lib/android/app/src/main/java/com/reactnativenavigation/react/ReactGateway.java
lib/android/app/src/main/java/com/reactnativenavigation/utils/Functions.java

Under certain configurations, creating ReactNativeHost before SoLoader.init throws an exception.
This commit changes the behaviour of the main ReactGateway constructor to ensures host is created after SoLoader.init.

Create react host after SoLoader.init

---

lib/ios/RNNModalManager.m
lib/src/events/ComponentEventsObserver.test.tsx
playground/ios/NavigationTests/RNNModalManagerTest.m

Closes https://github.com/wix/react-native-navigation/issues/5737
closes #5744

Fix sending dismissed modal event when dismissing modal by swiping gesture

---

lib/android/app/src/main/java/com/reactnativenavigation/presentation/BottomTabsPresenter.java
lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/bottomtabs/BottomTabsController.java
lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/bottomtabs/BottomTabsControllerTest.java

Default options were not taken into account when determining bottom inset.
Closes #5738

Fix incorrect bottom inset when hiding BottomTabs in default options

---

lib/src/commands/LayoutTreeParser.ts
lib/src/interfaces/Layout.ts

Fixes #5570 
Added type `LayoutTabsChildren[]` on the `children` property of `TopTabs` inside Layout (before was `any[]`. Also unified the naming of the export to be prefixed by `Layout + component name` as the other components exported from the layout.

Add types for children property on TopTabs

---

lib/android/app/src/main/java/com/reactnativenavigation/parse/BackButton.java
lib/android/app/src/main/java/com/reactnativenavigation/parse/LayoutFactory.java
lib/android/app/src/main/java/com/reactnativenavigation/presentation/StackPresenter.java
lib/android/app/src/main/java/com/reactnativenavigation/utils/ImageLoader.java
lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/TitleBarButtonController.java
lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/button/NavigationIconResolver.java
lib/android/app/src/test/java/com/reactnativenavigation/TestUtils.java
lib/android/app/src/test/java/com/reactnativenavigation/mocks/BackDrawable.java
lib/android/app/src/test/java/com/reactnativenavigation/mocks/ImageLoaderMock.java
lib/android/app/src/test/java/com/reactnativenavigation/utils/TitleBarHelper.java
lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/StackPresenterTest.java
lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/TopBarButtonControllerTest.java
lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/button/NavigationIconResolverTest.java
lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/stack/StackControllerTest.java

This commit fixes hiding the back button with `backButton.visible: false` in mergeOptions. It didn't work on Android.

Hide back button in mergeOptions

---

docs/docs/styling.md
lib/android/app/build.gradle
lib/android/app/src/main/java/com/reactnativenavigation/parse/params/TitleDisplayMode.java
lib/src/interfaces/Options.ts

_**Related Issue**_
Closes #5800
_**Description**_
When playing around with [AHBottomNavigation](https://github.com/aurelhubert/ahbottomnavigation) demo app, in order to only show to title of the active bottom tab when there's three tabs, the `TitleState` needs to be set to `SHOW_WHEN_ACTIVE_FORCE`. 
Adding these changes allow for this behavior in RNN, but when I'm clicking on a tab, the app dies. I only added this change to the playground app, to the bottomTabs root in `app.js`:
```
options: {
bottomTabs: {
titleDisplayMode: 'showWhenActiveForce'
}
}
```
Would anyone have a pointer on how to fix this or how to figure out what's wrong?

Added TitleState showWhenActiveForce option for bottomTabs

---

lib/android/app/src/main/java/com/reactnativenavigation/presentation/BottomTabsPresenter.java
lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/bottomtabs/BottomTabsController.java
lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/BottomTabsPresenterTest.java

When calling mergeOptions to update BottomTabs visibility, apply the visibility only if the child is visible.

Apply BottomTabs visibility only if child is visible

---

lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/modal/ModalPresenter.java
lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/modal/ModalPresenterTest.java

This is required so that a component displayed in a modal can react to the dismiss of the modal it's presented in. This change aligns behaviour with iOS.
closes #5830

Emit modalDismissed event before ViewController is destroyed

---

lib/android/app/src/main/java/com/reactnativenavigation/presentation/Presenter.java

Fix #5858 
Proposed changes add functionality to check applied navigation background color and apply contrast navigation bar style.
This PR does not contain tests since it seems quite impossible to test proposed changes.
Implementation is based on implementation of [react-native-navigation-bar-color](https://github.com/thebylito/react-native-navigation-bar-color/blob/8ee6a25bd2edae55e080389cd0b652097349e2fc/android/src/main/java/com/thebylito/navigationbarcolor/NavigationBarColorModule.java#L44). Color check is based on this [code snippet](https://codepen.io/WebSeed/pen/pvgqEq)

Add adaptive navigation bar buttons color

---

lib/android/app/src/main/java/com/reactnativenavigation/presentation/BottomTabPresenter.java

In Android dotIndicator with initial value of visible: false is not respected and the dot appears in any case.

make dotIndicator to respect visible value

---

e2e/ExternalComponent.test.js
lib/ios/RNNControllerFactory.m
lib/ios/RNNExternalViewController.m
playground/ios/NavigationTests/RNNExternalViewControllerTests.m
playground/ios/playground.xcodeproj/project.pbxproj
playground/src/screens/ExternalComponentScreen.js

• Fix external component options resolving
• Fix external component wrapper view frame

External components fixes

---

lib/android/app/src/main/java/com/reactnativenavigation/presentation/OverlayManager.java
lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/navigator/Navigator.java
lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/navigator/NavigatorTest.java
lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/overlay/OverlayManagerTest.java

react-native-youtubte is a popular library which wraps the native youtube library. The native lib attempts to detect if the player is hidden behind other views in order to prevent developers from playing videos in the background.
Since the overlay container was always attached to hierarchy, the library stopped playback as it mistakingly detected the player was used in the background.
This commit simply attaches the overlay container only when needed so as long as no overlays are displayed, the lib can be used.
Fixes #4256
Fixes #4358

Support react-native-youtube

---

lib/ios/UIViewController+LayoutProtocol.m
lib/ios/UIViewController+RNNOptions.m
playground/ios/NavigationTests/UIViewController+LayoutProtocolTest.m
playground/ios/NavigationTests/UIViewController+RNNOptionsTest.m

Fix wrong SafeAreaView margins when using `bottomTabs.drawBehind: true`.

Apply extendedLayoutIncludesOpaqueBars true on all viewControllers

---

lib/ios/RNNOverlayWindow.m

On new iPads, `UIWindow` content is wrapped with another `UIView`.
Fixed by propagating touch events through all `UIView` members in overlays.
Closes #5889

Fix overlays touch interception on new iPads

---

lib/ios/RNNComponentPresenter.m
lib/ios/RNNFontAttributesCreator.m
lib/ios/TopBarTitlePresenter.m
package.json
playground/ios/NavigationTests/RNNFontAttributesCreatorTest.m

Allow reset topBar.title.color when color isn't provided

---

lib/ios/DeprecationOptions.h
lib/ios/DeprecationOptions.m
lib/ios/RNNBottomTabsPresenter.m
lib/ios/RNNComponentPresenter.m
lib/ios/RNNLayoutOptions.h
lib/ios/RNNLayoutOptions.m
lib/ios/RNNSideMenuPresenter.m
lib/ios/RNNStackPresenter.m
lib/src/commands/Deprecations.ts
playground/ios/NavigationIOS12Tests/RNNRootViewControllerTest.m
playground/ios/NavigationTests/RNNRootViewControllerTest.m
playground/ios/NavigationTests/RNNSideMenuPresenterTest.m
playground/ios/NavigationTests/RNNStackPresenterTest.m
playground/ios/NavigationTests/RNNTabBarPresenterTest.m

* Modified `layout.backgroundColor` to control the layout parent background color.
* Add `layout.componentBackgroundColor` to control the component background color. (Until now on iOS, `layout.backgroundColor` controlled the component and not the parent.
* Remove drawBehind deprecation

Layout background color

---

lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/modal/ModalStack.java
lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/modal/ModalStackTest.java

This commit adds parity with iOS which does not reject the promise if dismissAllModals is called while no modals are displayed.

Stop rejecting on dismissAllModals if no modals are displayed

---

lib/android/app/build.gradle
lib/android/app/src/main/java/com/reactnativenavigation/presentation/BottomTabsPresenter.java
lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/bottomtabs/BottomTabsController.java
lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/bottomtabs/BottomTabsControllerTest.java

This commit introduces parity with iOS which allows the user to show tabs without icons. While there's no real production use case for this feature, it's helpful when getting started with a new project.

Support tabs without icons on Android

---

autolink/postlink/gradleLinker.js
autolink/postlink/path.js
autolink/postlink/podfileLinker.js
autolink/postlink/postLinkIOS.js

This PR fixes the autolink script including:
- Specifying the minSdkVersion for Android. Closes https://github.com/wix/react-native-navigation/issues/5983.
- Removing the RNN Pod added by the react-native link script.
@guyca  I've assumed the minSdkVersion will be 19 unless user specified higher. I've got the version from the doc, should this be updated to something higher?

Fix autolink script

---

lib/android/app/src/main/java/com/reactnativenavigation/presentation/OverlayManager.java
lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/modal/ModalPresenter.java
lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/navigator/Navigator.java
lib/android/app/src/test/java/com/reactnativenavigation/BaseTest.java
lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/modal/ModalPresenterTest.java
lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/navigator/NavigatorTest.java
lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/overlay/OverlayManagerTest.java

This commit improves support for react-native-youtube library. This library uses the native Youtube player which requires that no visible views will be laid out on top of the player. This commit set visibility of Modal and Overlay containers to GONE when they are empty.

Root layouts refactor

---

lib/ios/RNNBasePresenter.m
lib/ios/RNNComponentPresenter.m
lib/ios/RNNComponentViewController.h
lib/ios/RNNComponentViewController.m
lib/ios/RNNConvert.h
lib/ios/RNNConvert.m
lib/ios/RNNModalManager.m
lib/ios/RNNNavigationOptions.h
lib/ios/RNNNavigationOptions.m
lib/ios/RNNSplitViewControllerPresenter.m
lib/ios/RNNStackController.m
lib/ios/ReactNativeNavigation.xcodeproj/project.pbxproj
playground/ios/NavigationTests/RNNComponentPresenterTest.m
playground/ios/NavigationTests/RNNModalManagerTest.m
playground/ios/NavigationTests/RNNTabBarControllerTest.m
playground/ios/NavigationTests/UIViewController+LayoutProtocolTest.m

* Resolve `modalPresentationStyle` and `modalTransitionStyle` from layout tree on `showModal`.
* Remove merging `modalPresentationStyle` and `modalTransitionStyle` because it make no sense.
* Restore few tests that were disabled.
Closes #6003

Resolve modal presentation and transition on showModal

---

lib/ios/TabBarItemAppearanceCreator.m

There's an issue with iOS 13 bottomTab appearance where the label layout calculation is wrong when changing the font weight. Updating the titleAttributes using the old API solves this.
Closes #6005

Fix truncated bottomTab.text with semibold fontWeight

---

lib/ios/BottomTabsAppearancePresenter.h
lib/ios/BottomTabsAppearancePresenter.m
lib/ios/BottomTabsBasePresenter.h
lib/ios/BottomTabsBasePresenter.m
lib/ios/RNNBottomTabsOptions.h
lib/ios/RNNBottomTabsOptions.m
lib/ios/RNNBottomTabsPresenter.h
lib/ios/RNNBottomTabsPresenter.m
lib/ios/RNNComponentPresenter.m
lib/ios/RNNTopBarOptions.h
lib/ios/RNNTopBarOptions.m
lib/ios/ReactNativeNavigation.xcodeproj/project.pbxproj
lib/ios/TopBarPresenter.m
lib/ios/Utils/UIColor+RNNUtils.h
lib/ios/Utils/UIColor+RNNUtils.m
playground/ios/NavigationIOS12Tests/RNNBottomTabsPresenterTest.m
playground/ios/NavigationTests/RNNBottomTabsAppearancePresenterTest.m
playground/src/components/Root.js

* Add bottomTabsPresenter base class
* Always drawBehind `bottomTabs` and `topBar` when `translucent: true`
* Resolve `bottomTabs` background appearance in the correct order - 
* translucent - strongest option
* backgroundColor
* drawBehind when largeTitle is visible - fixes black large title
Closes #6006 
Closes #6014

Fix bottomTabs.translucent option

---

lib/ios/RNNComponentViewController.m
lib/ios/TopBarAppearancePresenter.m

Resolves largeTitle background color from `topBar.title.background.color`
Closes #5779

Fix largeTitle background color on iOS 13

---

lib/ios/RNNStackController.m

Check if prefersLargeTitles is supported to avoid a crash on iOS < 11.0

Fix issue with previous iOS version

---

lib/ios/RNNBottomTabsController.m
playground/ios/NavigationTests/RNNCommandsHandlerTest.m

Solves an issue where setting `bottomTabs.badge` with `mergeOptions` resets the bottomTab icon and title.

Resolve options from bottomTabs direct child in mergeChildOptions

---

lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/modal/ModalStack.java
lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/modal/ModalStackTest.java
lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/navigator/NavigatorTest.java

When no modals are displayed and dismissAllModals is called, resolve the promise successfully. This regression was introduced in  #5991

Always resolve dismissAllModals promise

---

lib/ios/TopBarAppearancePresenter.m

I noticed there is now an animation that occurs when pushing the first
view on a stack. This will happen with both:
`largeTitle: { visible: true }`
and
`largeTitle: { visible: false }`
It seems caused by the setting of the `scrollEdgeAppearance` background
without first configuring it using `configureWithOpaqueBackground`.
I also added checks for iOS 13 since these APIs require iOS 13.
I used this StackOverflow answer for reference: https://stackoverflow.com/a/57152709

Configure scrollEdgeAppearance with opaque background

---

playground/src/screens/OptionsScreen.js

This is probably leftover from the previous Shared Element implementation which was refactored in v5

Remove Shared Element Screen from Options screen

---

lib/android/app/src/main/java/com/reactnativenavigation/presentation/StackPresenter.java
lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/TitleBarReactViewController.java
lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/topbar/TopBarController.java
lib/android/app/src/main/java/com/reactnativenavigation/views/titlebar/TitleBar.java
lib/android/app/src/test/java/com/reactnativenavigation/utils/TitleBarHelper.java
lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/StackPresenterTest.java
lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/TitleBarReactViewControllerTest.java
lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/TitleBarTest.java
playground/src/commons/Options.js

This commit fixes a bug related to setting a new react component as title via mergeOptions. When a title component was set, and the user tried to replace the existing title with a new title via mergeOptions, the new title was not created and instead the current title was reapplied.
Fixes #5377

Fix title component not being replaced via mergeOptions

---

lib/ios/TopBarAppearancePresenter.m
playground/ios/NavigationTests/RNNStackPresenterTest.m

This commit fix topBar background wrong color when swiping pop gesture on iOS 13 and above.
Addresses #6055

Fix white topBar on pop with swipe gesture

---

lib/ios/RNNBasePresenter.h
lib/ios/RNNBasePresenter.m
lib/ios/RNNBottomTabsController.m
lib/ios/RNNComponentViewController.m
lib/ios/RNNSideMenuController.m
lib/ios/RNNStackController.m
lib/ios/UIViewController+LayoutProtocol.m
playground/ios/NavigationTests/BottomTabsControllerTest.m
playground/ios/NavigationTests/RNNSideMenuControllerTest.m
playground/ios/NavigationTests/RNNStackControllerTest.m
playground/ios/playground.xcodeproj/project.pbxproj

This PR fixes `statusBar.visible` option which stopped working on iOS 13.

Fix status bar visibility on iOS 13

---

lib/ios/RNNBasePresenter.h
lib/ios/RNNBasePresenter.m
lib/ios/RNNBottomTabsController.m
lib/ios/RNNComponentViewController.m
lib/ios/RNNExternalViewController.m
lib/ios/RNNSideMenuChildVC.m
lib/ios/RNNSideMenuController.m
lib/ios/RNNSplitViewController.m
lib/ios/RNNStackController.m
lib/ios/UIViewController+LayoutProtocol.m
playground/ios/NavigationTests/BottomTabsControllerTest.m
playground/ios/NavigationTests/RNNBasePresenterTest.m
playground/ios/NavigationTests/RNNSideMenuControllerTest.m

iOS 13.4 doesn't allow overriding UIViewController's methods in categories (and it's also discouraged by apple) which causes styles to break.
* Move UIViewController override methods from category to controllers.
* Fixes BottomTab style visibility
* Fixes `statusBar.style`
Closes #6075

Fix styling options on iOS 13.4

---

docs/api/OptionsModalPresentationStyle.md
docs/docs/options-migration.md
lib/src/interfaces/Options.ts

The enum `OptionsModalPresentationStyle` contained a value "popOver", which should probably be lowercase "popover" to match https://developer.apple.com/documentation/uikit/uimodalpresentationstyle/popover. This should fix bug #6004.

Fix modalpresentationstyle

---

playground/src/screens/StackScreen.js

For some reason the stack root was set to another stack instead of the children 😕

Fix wrong usage of setStackRoot command in playground app

---

lib/android/app/src/main/java/com/reactnativenavigation/utils/Animator.kt
lib/android/app/src/main/java/com/reactnativenavigation/views/element/animators/BackgroundColorAnimator.kt
lib/android/app/src/main/java/com/reactnativenavigation/views/element/animators/ClipBoundsAnimator.kt
lib/android/app/src/main/java/com/reactnativenavigation/views/element/animators/MatrixAnimator.kt
lib/android/app/src/main/java/com/reactnativenavigation/views/element/animators/ScaleXAnimator.kt
lib/android/app/src/main/java/com/reactnativenavigation/views/element/animators/ScaleYAnimator.kt
lib/android/app/src/main/java/com/reactnativenavigation/views/element/animators/XAnimator.kt
lib/android/app/src/main/java/com/reactnativenavigation/views/element/animators/YAnimator.kt

This commit adds support to the startDelay option in shared element transitions on Android. It also fixes image scale transition which only animated the image's scale type, but not its bounds.

Implement startDelay + fix image scale transition

---

website/api/options-stack.mdx

I think `visible` option should be under Options/Stack/TopBar. Correct me if I am wrong.

Add 'visible' option in TopBar docs

---

playground/src/app.js

This commit adds a call to dismissAllModals before setRoot to ensure this use case doesn't break in the future.

Dismiss all modals before app start to ensure this use case does not break

---

website/api/options-button.mdx

Corrected typo in file options-button.mdx: `ifRooom` > `ifRoom`

Corrected typo in options-button.mdx

---

website/api/options-stack.mdx
website/docs/docs-bottomTabs.mdx
website/docs/docs-playground-app.mdx
website/docs/style-animations.mdx
website/docusaurus.config.js

- All "Edit this page" links were broken
- And some links inside `.md` files
```sh
npx broken-link-checker "https://wix.github.io/react-native-navigation/docs/before-you-start" -ro
```
(c) Mur Amur

[Docs] Fix invalid links

---

lib/android/app/src/main/java/com/reactnativenavigation/presentation/StackPresenter.java
lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/TitleBarButtonController.java
lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/StackPresenterTest.java

Updating button options with mergeOptions stopped working in 6.5.0. The regression was introduced by #6090. When updating buttons, RNN didn't take button options into account when checking if two buttons are equal, instead it checked only by button id.
closes #6205

Fix updating button options with mergeOptions

---

lib/android/app/src/main/java/com/reactnativenavigation/presentation/FabPresenter.java
lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/ViewController.java
lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/stack/StackController.java
lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/stack/StackControllerBuilder.java
lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/FloatingActionButtonTest.java

Fab was instantiated with the default margin (16dp), without the containing screen's bottom inset. The caused the FAB to jump up when the screen appeared since it then received the correct bottom margins (16dp + bottom insets)
Fixes #5816

Fix flickering FAB when changing bottom tabs

---

website/docs/docs-bottomTabs.mdx

a missed comma (,) added in the bottom-tabs example

Fixed syntax error in bottomTabs example

---

scripts/release.js

This PR disables snapshot tags in order to make github releases page more readable.

Tag release versions only

---

lib/ios/UIViewController+RNNOptions.m

The badge colour was not changing from the default red in the tab bar item (when passing "badgeColor" to "bottomTab" options)

fixes badgeColor in ios 13+

---

website/docs/docs-functional-components.mdx

Using `Navigation.events().bindComponent()` to register event listeners in functional components leads to typing errors when using Typescript, as bindComponent method requires a `React.Component<any>` as first argument.
With registerComponentListener we achieve the exact same effect, but providing more appropiate typings for for its parameters, using `NavigationComponentListener` for the listener, and making componentId required.

[Docs] Modify functional components event listener example

---

website/docs/third-party-react-context.mdx

Documentation appeared to references an undefined function. Likely an
overlooked find-and-replace change.

Fix typo in React Context API documentation

---

autolink/postlink/activityLinker.js
autolink/postlink/appDelegateLinker.js
autolink/postlink/applicationLinker.js
autolink/postlink/gradleLinker.js
autolink/postlink/log.js
autolink/postlink/podfileLinker.js
autolink/postlink/postLinkAndroid.js
autolink/postlink/postLinkIOS.js
autolink/postlink/run.js

This PR aims to provide some basic error handling logic to the postlink scripts, which run after `react-native link`, by identifying potential drawbacks and managing the execution flow via try/catch statements and the use of throw under specific conditions. It was developed with the support of the @underscopeio team!
I added a few messages I thought are informative, which provide some basic feedback and direct the user to the specific section in the documentation whenever it's possible. The script was mostly optimistic, so I changed this a little bit to throw a few errors when unexpected things occur. On the previous version, errors would either be silent or be incorrectly informed as the library being already linked, as this could not be asserted from the information available during …

Handle errors in postlink scripts

---

autolink/postlink/run.js
package.json
website/docs/docs-Installing.mdx

Running `react-native link` will be deprecated in the following major versions of rn-cli.
React Native Navigation recommends the `react-native link` command to install the library, although it already implements Autolinking. These causes the library to make unnecessary modifications to the project it's installing to, which are already handled in Autolinking. 
However, since manual steps need to be completed, we are benefiting from the `"postlink"` hook in the `link` command which allows to run any set of scripts after the link has completed, in our case the node script `./autolink/postlink/run.js`.
I propose using the `bin` field from npm's package.json to perform these tasks from a single command and without using react-native link. I named it "rnn-link" and it can be run via `npx …

Replace deprecated link process

---

website/docs/docs-basic-navigation.mdx

Removed duplicate component declarations(`SettingsScreen`) and obsolete styles(`styles.settings`) in example code. And moved them under `HomeScreen`

Fix duplicate SettingsScreen declaration in 'Basic Navigation' documentation

---

lib/src/index.ts
lib/src/interfaces/NavigationFunctionComponent.ts

- Added NavigationFunctionComponent interface
This interface can be used instead of React.FunctionComponent, fixing Typescript `Property 'options' does not exist on type 'FunctionComponent<{}>'` error when trying to declare static options on a functional component.

Add NavigationFunctionComponent interface

---

website/docs/docs-before-you-start.mdx

This PR fixes #6299 
---
Interesting to find that on the very first initial load of the doc site before user clicks any of the pages in the side bar, if you reference another page by its `id`, it will navigate to the wrong url.
Using the file name fixes the problem

Fix Documentation link on Before you start page

---

e2e/BottomTabs.test.js
lib/android/app/src/main/java/com/reactnativenavigation/NavigationActivity.java
lib/ios/BottomTabsBasePresenter.m
lib/ios/RNNBasePresenter.m
lib/ios/RNNBottomTabsController.h
lib/ios/RNNBottomTabsController.m
lib/ios/UITabBarController+RNNOptions.h
lib/ios/UITabBarController+RNNOptions.m
playground/ios/NavigationIOS12Tests/RNNBottomTabsPresenterTest.m
playground/ios/NavigationTests/RNNBottomTabsAppearancePresenterTest.m

Until now, `tabBar.frame` got restored each time child appeared which resulted in wrong bottomTabs visibility.
In this PR we changed it so the `tabBar.frame` will get restored only after the tabBar frame has changed through `mergeOptions`.
Closes #6282

Restore bottomTabs visibility when needed

---

website/docs/docs-passing-data-to-components.mdx

Fix return statement in the example code given in the `Handling passProps in static options` section

Fix return statement in the example code

---

lib/android/app/src/main/java/com/reactnativenavigation/utils/ButtonSpan.kt
lib/android/app/src/test/java/com/reactnativenavigation/utils/ButtonSpanTest.java

When attempting to show a disabled TopBar button, RNN attempted to obtain the `disabledButtonColor` option even it was undefined which led to a crash.
closes #6257
closes #6204

Fix crash when disabledButtonColor is undefined

---

lib/android/app/src/main/java/com/reactnativenavigation/presentation/StackPresenter.java
lib/android/app/src/main/java/com/reactnativenavigation/views/titlebar/TitleBar.java
lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/TitleBarTest.java

This change addresses an issue where if the user increased their device's font size in accessibility settings, then they would exceed from TopBar bounds.

TopBar title and subtitle font size is measured in dp instead of sp

---

website/docs/third-party-react-context.mdx

Example docs were missing apostrophes on several import statements in the examples

Fix missing apostrophes

---

e2e/BottomTabs.test.js
lib/ios/RNNBottomTabsController.m
playground/src/screens/SecondBottomTabScreen.js

`BottomTabsController.currentTabIndex` didn't get updated on pressing tabs which resulted in wrong option resolving and multiple styling bugs.
Closes #6310
Closes #6313

Fix updating currentTabIndex

---

autolink/postlink/appDelegateLinker.js
website/docs/docs-Installing.mdx

This PR includes:
- Not removing `#import <React/RCTBridge.h>` in `AppDelegate.m` as per playground app.
- Updated the Installation documentation to reflect the correct iOS `AppDeletegate.m` file.
Related to #6270

iOS installation documentation/autolink in parity with Playground app

---

lib/ios/RNNBottomTabsController.h
lib/ios/RNNBottomTabsController.m
lib/ios/UITabBar+utils.h
lib/ios/UITabBar+utils.m
playground/ios/NavigationTests/BottomTabsControllerTest.m
playground/src/app.js

Until now, `bottomTabs` longPress event gesture was implemented wrong and caused this [bug](https://github.com/wix/react-native-navigation/issues/6305).
It also reported wrong index in the first place, starting from 1 instead of 0.
This PR fixes both issues.
Closes #6305

Fix bottomTabs long press event

---

lib/android/app/src/main/java/com/reactnativenavigation/views/BottomTabs.java

This is a temp fix for a crash that happened when attempting to set the initial tab index before BottomTabs view is created.
closes #6316

Fix crash when currentTabIndex is defined

---

lib/android/app/src/main/java/com/reactnativenavigation/parse/parsers/IconParser.java

We always parsed icons, even if they are undefined. This addresses the JSON parse exception stack trace users often saw when opening the app.

Parse icon only if it is defined

---

.gitignore
.vscode/settings.json
package.json
website/docs/meta-contributing.mdx

This PR includes:
- Adding `Enable linter` section in `Contributing` documentation to explain that the project uses `ESLint` with `Prettier` and has a pre-commit hook to verify the linter.
- Committing `.vscode` folder to enable `formatOnSave` in VSCode. 
- Adding pre-commit hook which runs the `eslint` check on staged files to block any unformatted to be staged.

Adding pre-commit hook and Enable Linter in documentation

---

lib/src/interfaces/Options.ts
website/api/options-fab.mdx

This PR closes #6369:
- Removed `alignVeritically` option for Fab button
- Removed `actions` option for Fab button
- Updated `size` option to `'mini' | 'regular'`

Fixed up the doc and type for Fab button

---

lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/stack/topbar/button/ButtonPresenter.kt
lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/stack/topbar/button/ButtonSpan.kt
lib/android/app/src/test/java/com/reactnativenavigation/utils/ButtonPresenterTest.java
lib/android/app/src/test/java/com/reactnativenavigation/utils/ButtonSpanTest.java

When a button was disabled, changing its color once it became enabled did not work.

Fix changing disabled button color

---

lib/src/interfaces/NavigationComponent.ts
lib/src/interfaces/NavigationFunctionComponent.ts
lib/src/interfaces/Options.ts
playground/src/commons/Layouts.ts
playground/src/screens/FullScreenModalScreen.tsx
playground/src/screens/LayoutsScreen.tsx
playground/src/screens/ModalScreen.tsx
playground/src/screens/PushedScreen.tsx
playground/src/screens/SideMenuCenterScreen.tsx
playground/src/screens/SideMenuLeftScreen.tsx
playground/src/screens/sharedElementTransition/CocktailsListScreen.tsx
playground/src/screens/splitView/CocktailsListMasterScreen.tsx
playground/src/services/Navigation.ts
website/docs/third-party-typescript.mdx
website/sidebars.js

This commit makes static options added to components strongly typed.
I also updated a few screens in the Playground app to reflect this, and also corrected rightButtons and leftButtons option which accepts both single button and an array of buttons.

Type component options

---

lib/android/app/src/main/java/com/reactnativenavigation/options/ButtonOptions.java
lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/stack/topbar/button/ButtonPresenter.kt
lib/android/app/src/test/java/com/reactnativenavigation/utils/ButtonPresenterTest.java
lib/src/interfaces/Options.ts

TopBar buttons are allCaps by default on Android. This option can be used to turn this option off, making camel case buttons possible.

Add allCaps option to TopBar buttons

---

website/api/options-button.mdx

Support for the allCaps option was added in #6397 but was left undocumented.

Document button.allCaps

---

lib/src/commands/Commands.test.ts
lib/src/commands/Deprecations.ts
lib/src/commands/OptionsProcessor.test.ts
lib/src/commands/OptionsProcessor.ts

On iOS the system doesn't support dynamically toggling bottomTabs at all so we had to hack through it which resulted in many issues with this feature. We plan on entirely removing it and stick to the framework's guidelines which means that toggling the bottomTabs will not be possible at all and controlling it with static options will be the only option.

Show deprecation warning while toggling bottomTabs visibility on iOS

---

lib/ios/ContentTransitionCreator.h
lib/ios/ContentTransitionCreator.m
lib/ios/StackControllerDelegate.m
lib/ios/StackTransitionDelegate.h
lib/ios/StackTransitionDelegate.m
lib/ios/TransitionDelegate.m

The transition context needs to be different for pop and push, until now we didn't handle that.

Fix shared element transition on pop

---

website/docs/docs-playground-app.mdx

Fixes #6414
Adds missing `pod install` to  playground installation instructions at `website/docs/docs-playground-app.mdx`:
```js
1. Install dependencies via `npm install` (if you haven't already) and `cd ./playground/ios && pod install` (for iOS)
```

Fix playground docs

---

lib/src/Navigation.ts

RNN should be agnostic of state management solutions. Redux can be used with the regular registerComponent method:
```js
const myStore = createStore();
Navigation.registerComponent(
'MyScreen',
() => (props) => (
<Provider store={myStore}>
<MyScreen {...props} />
</Provider>
),
() => MyScreen
);
```

Deprecate register component with redux

---

lib/src/adapters/TouchablePreview.tsx
playground/src/components/Button.tsx

This PR includes:
- Ensuring the `onPress` or `onPressIn` props are not being overriden in `Navigation.TouchablePreview` as the internal `onPress` and `onPressIn` are handling the touch.
- Revert the `Button` component in the Playground app to class component to provide access to `ref`. 
Related to #6420 
@yogevbd This PR does fix triggering the `Preview` API in the Playground app however the Preview is still not appearing.

Fix TouchablePreview regression

---

lib/ios/RNNSplitViewControllerPresenter.m
lib/ios/RNNSplitViewOptions.h
lib/ios/RNNSplitViewOptions.m
lib/ios/UISplitViewController+RNNOptions.h
lib/ios/UISplitViewController+RNNOptions.m
lib/src/commands/LayoutTreeParser.test.ts
lib/src/interfaces/Options.ts
website/api/options-splitView.mdx

This PR adds the primaryBackgroundStyle option in splitView to enable translucent sidebars when developing Mac Catalyst apps. Like splitView it's iOS only and requires iOS 13+, the moment it seems to only have an effect on Mac apps and not affect apps running on iOS, see: https://developer.apple.com/documentation/uikit/uisplitviewcontroller/3238075-primarybackgroundstyle
The following layout
```typescript
Navigation.events().registerAppLaunchedListener(() => {
Navigation.setDefaultOptions({
layout: {
backgroundColor: 'transparent',
componentBackgroundColor: 'transparent',
},
topBar: { 
background: {translucent: true, blur: true},
visible: false,
}, 
});
Navigation.setRoot({
root: {
splitView: {
master: {
stack: {
children: [
{
component: {
name: 'Sidebar',
},
},
],
},
},
detail: {
stack: …
```

Add primaryBackgroundStyle option to splitView

---

lib/ios/NSObject+Utils.h
lib/ios/NSObject+Utils.m
lib/ios/RNNOptions.m
lib/ios/ReactNativeNavigation.xcodeproj/project.pbxproj
playground/ios/NavigationTests/NSObjectUtilsTests.m
playground/ios/playground.xcodeproj/project.pbxproj

* Fix options.animations merging - `objectProperties` function didn't return superclass properties which resulted in wrong option merging.
* Rename `objectProperties` to `classProperties`.
Closes #6373

Fix merging options

---

lib/ios/RNNBasePresenter.m
playground/ios/NavigationTests/RNNBasePresenterTest.m

`mergeOptions` with `statusBar.visible` didn't work on iOS. This PR fix it.

Fix statusBar visibility through mergeOptions

---

lib/ios/RNNBridgeManager.mm
lib/ios/RNNBridgeModule.m
lib/ios/RNNCommandsHandler.h
lib/ios/RNNCommandsHandler.m
lib/ios/RNNEventEmitter.h
lib/ios/RNNEventEmitter.m
lib/ios/RNNModalManager.h
lib/ios/RNNModalManager.m
lib/ios/RNNModalManagerEventHandler.h
lib/ios/RNNModalManagerEventHandler.m
lib/ios/ReactNativeNavigation.xcodeproj/project.pbxproj
playground/ios/NavigationTests/RNNCommandsHandlerTest.m
playground/ios/NavigationTests/RNNModalManagerEventHandlerTest.m
playground/ios/NavigationTests/RNNModalManagerTest.m
playground/ios/playground.xcodeproj/project.pbxproj

* Resolve `Navigation.dismissModal()` with topmost parent `componentId`.
* Resolve `ModalDismissedListener` event with topmost parent `componentId`.
* Remove `componentName` from `ModalDismissedListener` event.

Resolve dismissModal promise with topmost parent componentId

---

lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/stack/StackPresenter.java
lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/stack/topbar/button/ButtonPresenter.kt
lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/stack/topbar/button/ButtonSpan.kt
lib/android/app/src/test/java/com/reactnativenavigation/utils/ButtonPresenterTest.java
lib/android/app/src/test/java/com/reactnativenavigation/utils/ButtonSpanTest.java
lib/android/app/src/test/java/com/reactnativenavigation/utils/TitleBarHelper.java
lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/stack/TitleBarButtonControllerTest.java
lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/stack/TitleBarTest.java
lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/stack/TopBarButtonControllerTest.java
lib/src/interfaces/Options.ts
playground/src/screens/ButtonsScreen.tsx
website/api/options-button.mdx

TopBar button text broke in 6.5.0 and instead of being applied in sp it was applied in pixels. This made if seem like the fontSize option didn't work. This commit fixes the problem and also sets button fontSize in dp so it won't increase too much if users change font size settings in their device.
closes #6405

Set button text in dp

---

lib/src/interfaces/NavigationComponent.ts

The static options field can either be a concrete options object or a generator function which accepts props as parameter. Unfortunately, static fields don't play well with TypeScript generics and the param was left as `any`.

Update static options prototype to include props param

---

lib/src/commands/LayoutTreeCrawler.test.ts
lib/src/commands/LayoutTreeCrawler.ts

Up until now the static options generator was invoked with passProps while the component's props contain passProps as well as componentId. This commit eliminates this inconsistency as it's a source for confusion and from now on passProps will also contain the componentId.
Note that if the user has specified a prop named `componentId` then Navigation won't override it.

Include componentId in props passed to static options generator

---

lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/stack/StackController.java
lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/stack/StackControllerTest.java

When popToRoot is called and the stack size is 1, the command promise is now resolved successfully instead of being rejected. This PR introduces parity with iOS.

Don't reject promise if popToRoot is called and there's nothing to pop

---

lib/ios/RCTConvert+Interpolation.h
lib/ios/RCTConvert+Interpolation.m
lib/ios/ReactNativeNavigation.xcodeproj/project.pbxproj

Resolves 
```
ld: warning: meta method 'RNNInterpolationOptions:' in category from [...] conflicts with same method from another category
```
from build.
Obj-C `@implementation` shouldn't be in header files!

Fix category warnings for RNNInterpolationOptions

---

lib/ios/ColorParser.m

See https://reactnative.dev/blog/2020/07/06/version-0.63#native-colors-platformcolor-dynamiccolorios for an intro.
Fixes #6113
Color values can now be more than just numbers. So just pass through to `RCTConvert` for handling (this takes care of `PlatformColor` / `DynamicColorIOS` automatically). If it comes back as `nil` fallback onto `NoColor`.

Enable PlatformColor / DynamicColorIOS for iOS

---

lib/ios/TopBarAppearancePresenter.m
playground/ios/NavigationTests/RNNRootViewControllerTest.m

On iOS 13, title attributes should be applied on `scrollEdgeAppearance` as it applied on `standardAppearance`.
@guyca We need to think about adding more options to control those two states.
Closes #6337

Fix large title styles

---

lib/android/app/src/main/java/com/reactnativenavigation/views/element/animators/MatrixAnimator.kt

When animating images in shared element transition, we change their ScaleType to an InterpolatingScaleType.
At the end of the animation we need to restore the ScaleType back to its original value but for some reason this doesn't seem to work.
The current solution recursively find the original scale type used for the destination image.
Related to #6505

Use correct ScaleType when animating same element multiple times

---

lib/ios/RNNBasePresenter.m
lib/ios/ReactNativeNavigation.m

Usually UIWindow is initalized in the UIAppDelegate.
This is also how the standard react-native template is set up.
By replacing an already setup window, we are not only doing more work
but also loosing already set properties or custom UIWindow implementations.
Other libraries (like fbsdk) depend on the UIWindow already being setup in the app delegate.
Lastly, this presents a potential debugging nightmare as nobody would expect their UIWindow just being replaced.
Therefor, we should only set it up from inside rnn if it doesn't exist already.

Only initialize UIWindow if needed

---

lib/ios/RNNBasePresenter.m

It appears that UIViewController's delegate methods `preferredStatusBarStyle` and `prefersStatusBarHidden` needs to run faster than it does now. So instead of resolving all the options object, I changed it to resolve only the `statusBar` options object, which fix's the issue.
Closes #6506

Fix status bar disappears on setRoot

---

lib/ios/ReactNativeNavigation.h
lib/ios/ReactNativeNavigation.m

Without a delegate there is no support for source url and extra modules which are both needed since v7.
@guyca Maybe I missed something in your v7 commit, but it currently doesn't work without a delegate as the `RCTBridgeDelegate` wrapper in `RNNBridgeManager` was removed. So there is no fallback anymore if user doesn't provide a delegate.

Remove broken bootstrap method

---

lib/src/components/ComponentWrapper.tsx
lib/src/components/Store.test.ts
lib/src/components/Store.ts

UpdateProps now keeps the old props.

---

lib/src/interfaces/NavigationFunctionComponent.ts

* Adds `NavigationComponentProps` type (e.g. `componentId`) to options function (`(props) => Options`)

Fix props type in options function

---

lib/ios/TopBarAppearancePresenter.m

Fixes issue with border shown on iOS TopBar in combination with `largeTitle {visible: true}`, even though `{noBorder:true}` is passed in the config

Fixes issue with border shown on iOS TopBar

---

lib/ios/RNNComponentPresenter.m
lib/ios/RNNTopBarOptions.h
lib/ios/RNNTopBarOptions.m
lib/ios/UIViewController+RNNOptions.h
lib/ios/UIViewController+RNNOptions.m
lib/src/interfaces/Options.ts
website/docs/api/options-stack.mdx

* Sets [`UISearchBar::searchTextField::backgroundColor`](https://developer.apple.com/documentation/uikit/uisearchbar/3175433-searchtextfield?language=objc) to the value supplied in the `Options.searchBarBackgroundColor` (only available on > iOS 13)
* Sets [`UISearchBar::tintColor`](https://developer.apple.com/documentation/uikit/uisearchbar/1624286-tintcolor?language=objc) to the value supplied in the `Options.searchBarTintColor` (only available on > iOS 11)
* As a side-effect, sets [`UISearchBar::searchBarStyle`](https://developer.apple.com/documentation/uikit/uisearchbar/1624281-searchbarstyle?language=objc) to [`UISearchBarStyleProminent`](https://developer.apple.com/documentation/uikit/uisearchbarstyle/uisearchbarstyleprominent?language=objc)
* Adds `searchBarBackgroundColor` and …

Add support for searchBarBackgroundColor and searchBarTintColor

---

ReactNativeNavigation.podspec
lib/ios/RNNCommandsHandler.m
lib/ios/RNNStackController.m
lib/ios/RNNSwizzles.m
lib/ios/TopBarPresenter.m
lib/ios/UISplitViewController+RNNOptions.m
lib/ios/UIViewController+RNNOptions.m
playground/ios/Podfile

RNN supports iOS 11 and upwards. There is no need to keep legacy available statements around.

Remove old iOS < 11 code

---

lib/ios/RNNModalManager.m

The typedef of `RNNTransitionWithComponentIdCompletionBlock`:
```objc
typedef void (^RNNTransitionWithComponentIdCompletionBlock)(NSString * _Nonnull componentId);
```
requires the completion handler to be called with a non-null string.

Pass componentId on showModal completion callback

---

lib/ios/AnimatedReactView.m
lib/ios/CornerRadiusTransition.h
lib/ios/CornerRadiusTransition.m
lib/ios/RNNViewLocation.h
lib/ios/RNNViewLocation.m
lib/ios/ReactNativeNavigation.xcodeproj/project.pbxproj
lib/ios/SharedElementAnimator.m
lib/ios/TransformRectTransition.h
lib/ios/TransformRectTransition.m
lib/ios/Utils/UIView+Utils.h
lib/ios/Utils/UIView+Utils.m
playground/src/screens/sharedElementTransition/CocktailDetailsScreen.tsx
scripts/test-snapshot.js

See https://github.com/wix/react-native-navigation/issues/6519
Creates a new `CornerRadiusTransition` which allows animating the `cornerRadius` property of a View's layer. The new Transition is added to the `DisplayLinkAnimation` array (in `createAnimations`) when the fromView's cornerRadius property is different than the toView's cornerRadius property.
1. **Android support.** Sorry, I'm more of an iOS dev.
2. **Pop support.** I don't know why, but the cornerRadius animation only works on push. When going back in the Cocktail example app, the cornerRadius will not be visibly animated, even though the `CornerRadiusTransition::animateWithProgress` function is called.
3. [optional] **Masked Corner support.** Support cornerRadius only being animated on corners that actually change. Currently …

Animate borderRadius for Shared Element Transitions

---

lib/android/app/src/main/java/com/reactnativenavigation/options/params/Interpolation.java
lib/android/app/src/main/java/com/reactnativenavigation/options/parsers/InterpolationParser.java
lib/ios/RCTConvert+Interpolation.h
lib/ios/RCTConvert+Interpolation.m
lib/ios/RNNInterpolator.m
lib/src/interfaces/Options.ts
playground/src/screens/sharedElementTransition/CocktailsListScreen.tsx
website/docs/docs/style-animations.mdx

This PR renames the `'spring'` interpolation mode to `'overshoot'`. 
On Android, an [`OvershootInterpolator`](https://android.googlesource.com/platform/frameworks/base/+/master/core/java/android/view/animation/OvershootInterpolator.java) was used, so it made no sense to call it `'spring'`. On iOS, I changed the Spring implementation to be the exact same of the android's [`OvershootInterpolator::getInterpolation`](https://android.googlesource.com/platform/frameworks/base/+/master/core/java/android/view/animation/OvershootInterpolator.java#73) so we have the same look and feel on both platforms. 
This means, using the `tension` property we can configure both animations. Now we only need to expose that to the JS API somehow.
If requested, I can add the spring implementation (which uses …

'spring' -> 'overshoot'

---

lib/ios/ImageParser.m
lib/src/interfaces/Options.ts

Note: This PR needs https://github.com/wix/react-native-navigation/pull/6575 merged in order to work on all icons in RNN.
Apple introduced SF Symbols with iOS 13: https://developer.apple.com/design/human-interface-guidelines/sf-symbols/overview/
> SF Symbols provides a set of over 2,400 consistent, highly configurable symbols you can use in your app.
This PR enables using those throughout all images that can be specified with RNN.
Instead of 
```ts
{
icon: require("my-custom-camera-icon.png")
}
```
it is now possible to use
```ts
{
icon: {
system: "camera.fill",
fallback: require("my-custom-camera-icon.png")
}
}
```
which will result in the SF Symbol `camera.fill` to be used on iOS >= 13. The fallback for everything else.
In theorie this would be better suited in `RCTConvert` upstream. …

[ios] Allow sync loading of sf symbols

---

lib/ios/RNNNavigationButtons.m

This PR streamlines the sync loading of images to always go through the appropriate `ImageParser` class.

Use ImageParser instead of calling RCTConvert directly

---

playground/src/screens/sharedElementTransitionAlt/Constants.ts

Small fix for the playground only (bug introduced in https://github.com/wix/react-native-navigation/commit/1d8e3b784ecedc7153fb0b0d900e42ab4a8b8f16)

Rename `'spring'` to `'overshoot'` in playground demo

---

lib/ios/AnimatedReactView.m
lib/ios/RNNViewLocation.h
lib/ios/RNNViewLocation.m
lib/ios/SharedElementAnimator.m

Until now we resolved the corner radius of shared element view from the view itself, but it is possible that corner radius are applied on this view from a wrapper parent so now we will also try to resolve it from any parent view that have the exact same bounds.
Closes #6596

Better resolving shared element corner radius value

---

ReactNativeNavigation.podspec

From now on native modules should only depend on `React-Core` instead of `React`.
This fixes Xcode 12 build errors, see: https://github.com/facebook/react-native/issues/29633

Podspec: Depend on React-Core instead of React

---

lib/android/app/src/main/java/com/reactnativenavigation/utils/ImageUtils.kt
lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/viewcontroller/OverlayLayout.kt
lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/viewcontroller/ViewControllerOverlay.kt

This is needed when an entire screen is scaled down, typically with a gesture, and when the gesture reaches
a certain threshold the screen is popped.

Include all ancestors scale when determining an element's initial scale

---

lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/stack/StackAnimator.kt

This was originally added to workaround an issue with flickering images. We've since added a better workaround so this can be removed.

Remove redundant awaitPost before popping screen with Shared Element Transition

---

lib/android/app/src/main/java/com/reactnativenavigation/views/element/SharedElementTransition.kt

Corner radius has to be evaluated after clip bounds are evaluated as the radius calculation relies on bounds.

Fix timing issue with shared element animators

---

lib/ios/AnimatedReactView.m

For a split second, the shared element view isn't initialised with the correct corner radius.

Fix initial shared element corner radius glitch

---

lib/android/app/src/main/java/com/reactnativenavigation/views/element/animators/ReactViewOutlineAnimator.kt

Width/Height (Right/Bottom) bounds were multiplied by the inherited scale twice

Fix ReactViewOutlineAnimator width/height wrong scale

---

lib/src/interfaces/Options.ts
playground/src/commons/Options.ts

Setting default root window view's background color. Fixes linter warning when setting window's view background color
Sample usage:
```
Navigation.setDefaultOptions({
window: {
backgroundColor: '#25C2A0',
},
});
```

Create WindowOptions type

---

lib/ios/RNNBasePresenter.h
lib/ios/RNNBasePresenter.m
lib/ios/RNNComponentViewController.m
lib/ios/RNNLayoutOptions.h
lib/ios/RNNLayoutOptions.m
lib/ios/UIViewController+LayoutProtocol.m
lib/src/interfaces/Options.ts
website/docs/api/options-layout.mdx

```js
const options = {
layout: {
autoHideHomeIndicator: true // Default is false
}
}
```
Closes https://github.com/wix/react-native-navigation/issues/6290

Add the ability to control the iOS home indicator auto-hiding

---

lib/ios/RNNCommandsHandler.m

This moves the call to the completion handler to a later time. Instead of relying on the completion of the CATransaction, we are now waiting until [UIViewController dismissViewControllerAnimated:completion:] calls back
Fixes #5045, #5552

Call dismissAllModals completion handler after the dismissal has actually completed

---

.github/support.yml
autolink/postlink/podfileLinker.js

Sets the minimum iOS version to iOS 11.0 which is the minimum version required by the library.

Fix link script on iOS

---

lib/ios/RNNBasePresenter.h
lib/ios/RNNBasePresenter.m
lib/ios/RNNComponentViewController.m
lib/ios/RNNSideMenuController.m
lib/ios/RNNStackController.m
lib/ios/UIViewController+LayoutProtocol.m
playground/src/screens/LayoutsScreen.tsx

* Removes `setDefaultOptions` from RNNBasePresenter. This is already covered by the synthesized `defaultOptions` prop.
* Add calling `[presenter setDefaultOptions:]` to the default implementation in order to remove all the overrides that do the same thing.
Notice that the override implementation of `setDefaultOptions` in `RNNSideMenuController` does not call `super`. This leads to the `defaultOptions` only being available in the `RNNSideMenuPresenter` but not in the controller itself. Therefor causing bugs in accessing options that were set as defaults through the controller (as they are just not available).

Remove unnecessary overrides to setDefaultOptions, apply defaultOptions to RNNSideMenuController

---

lib/ios/RNNSideMenuChildVC.m
lib/ios/RNNSideMenuController.m
lib/ios/RNNTopTabsViewController.m

As per the docs:
> If you are implementing your own container view controller, it must call the didMoveToParentViewController: method of the child view controller after the transition to the new controller is complete or, if there is no transition, immediately after calling the addChildViewController: method.
>
> The removeFromParentViewController method automatically calls the didMoveToParentViewController: method of the child view controller after it removes the child.

Balance out addChildViewController with didMoveToParentViewController

---

lib/ios/TabBarItemAppearanceCreator.m

this is a fix for when bottom tab items with custom title attributes get truncated on iPads running iOS14.
Fixes #6533

fix for truncated tab item names on ios14

---

lib/android/app/src/main/java/com/reactnativenavigation/options/TopBarButtons.java
lib/android/app/src/main/java/com/reactnativenavigation/utils/CollectionUtils.java
lib/android/app/src/test/java/com/reactnativenavigation/options/TopBarButtonsTest.kt
playground/src/services/Navigation.ts

When copying TopBarButtons, the copy function would mutate the original object and change the right buttons object.

Fix copy function mutating original buttons object

---

lib/ios/RNNSideMenuChildVC.m
lib/ios/RNNSideMenuController.m

By calling [super render] the child render will get called via getCurrentChild.
Afterwards the super method will call the readyForPresentation callback.
Fixes #6000 
⚠️ Relies on #6689 to be merged first in order for `waitForRender` to propagate properly down the parent / child chain.

Enable side menu readyForPresentation callbacks

---

website/docs/docs/style-animations.mdx

file extension changed from `.js` -> `.tsx` and we forgot to update the docs.
happens to the best of us

Fix dead links in SET docs

---

lib/ios/StackControllerDelegate.m

Uses to lookup in the `toVC` when actual info is stored in the `fromVC`. `toVC` is screen beneath.

Fix viewcontroller for pop animation lookup

---

lib/android/app/src/main/java/com/reactnativenavigation/options/FadeAnimation.java
lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/stack/StackAnimator.kt

If you comment out [these](https://github.com/wix/react-native-navigation/blob/master/playground/src/screens/sharedElementTransition/CocktailsListScreen.tsx#L51-L57) and [these](https://github.com/wix/react-native-navigation/blob/master/playground/src/screens/sharedElementTransition/CocktailsListScreen.tsx#L93-L99) lines in the playground demo, then test the Cocktails screen and select your favourite gin cocktail (@danilobuerger !!!!), you can notice that on popping the alpha animation is reversed. You'd expect it to go from visible (opacity of `1`) to invisible (opacity of `0`), but instead it jumps to `0` and then goes to `1` making it look really weird.
This PR changes this default behavior to reverse the default `FadeAnimation` on pop.

Fix default alpha animation being reversed

---

lib/ios/RNNBridgeManager.h
lib/ios/RNNBridgeManager.mm
lib/ios/RNNCommandsHandler.h
lib/ios/RNNCommandsHandler.m
lib/ios/RNNLayoutManager.h
lib/ios/RNNLayoutManager.m
lib/ios/RNNLayoutProtocol.h
lib/ios/ReactNativeNavigation.m
lib/ios/UINavigationController+RNNCommands.m
playground/ios/NavigationTests/RNNCommandsHandlerTest.m
playground/ios/NavigationTests/RNNLayoutManagerTest.m
playground/ios/SnapshotTests/Utils/CommandsHandlerCreator.m

When `waitForRender` is set to `true`, calling `Navigation.mergeOptions` early (for example in `componentDidMount`) will lead to the options not being applied as the backing view controller has not yet been placed in the window hierarchy. This PR aims to keep track of any pending view controllers and opens them up to being found via their component id. Thus enabling `Navigation.mergeOptions` to work on view controllers in transit.
The pending view controllers are now being kept in `RNNLayoutManager`. For that reason, the layout manager was converted to be instantiable.
A `NSHashTable` was chosen as the backing storage to support keeping the view controllers as a weak reference.
Fixes #6085

Fix waitForRender + mergeOptions not working when view controller is in transit

---

website/docs/api/options-scrollEdgeAppearance.mdx

Seems like the docs for `scrollEdgeAppearance` don't match the actual code. Fixed it here.
cc @mateioprea

Fix scrollEdgeAppearance docs

---

lib/ios/RNNCommandsHandler.m
playground/ios/NavigationTests/RNNCommandsHandlerTest.m

When calling `dismissModal` with an options object, the options were merged into the appearing modal instead of the disappearing modal.

Fix merge options on dismissModal

---

lib/android/app/src/main/java/com/reactnativenavigation/views/element/SharedElementTransition.kt
lib/android/app/src/main/java/com/reactnativenavigation/views/element/animators/FastImageBoundsAnimator.kt
lib/android/app/src/main/java/com/reactnativenavigation/views/element/animators/ReactImageBoundsAnimator.kt
lib/android/app/src/main/java/com/reactnativenavigation/views/element/animators/ReactImageCornerRadiusAnimator.kt

While animating ReactImageView in shared element transition, we're changing the bounds of the destination image to max(sourceImage.bounds, destinationImage.bounds) and apply a clipping Rect.
This apparently messes up border-radius as Fresco isn't aware of the clipping Rect and draws the corners according to the actual image bounds.
This commit splits the clip bounds animator into two animators, one for Image and another for FastImage.
In the ReactImageView animator, we update both clip bounds and the drawable bounds
This was noticeable when the default resize mode (cover) was used.
**Note: this or doesn't add support for animating border-radius in ReactImageView. This will be added hopefully in a separate PR**
| Before …

Fix incorrect border radius end value

---

website/docs/docs/third-party-mobx.mdx
website/docs/docs/third-party-mobx/counter-screen.tsx
website/docs/docs/third-party-mobx/counter-store-decorator.tsx
website/docs/docs/third-party-mobx/persistent-data.tsx

Updated the `mobx integration` documentation to reflect the latest mobx update. It highlights the new mobx standard pattern of using `makeObservable` but still provides an integration guide on using decorator pattern.
Closes #6739

Updated the documentation for mobx integration.

---

.grenrc.js
scripts/release.js

* Add bullets to issues
* Sleep one minute before running gren release - This is an attempt to fix wrong release draft created by gren in CI which doesn't reproduce locally, It might happening to fast after creating the new git tag.

Fix gren script

---

.github/stale.yml

If an issue still needs to be looked at, it can't be stale.

Do not close "needs triage" issues as stale

---

lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/stack/StackPresenter.java
lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/stack/StackPresenterTest.java

When calling mergeOptions on a stack layout directly, the default options were applied as well.

Fix default options being applied when calling mergeOptions on a stack layout

---

lib/src/commands/Commands.test.ts
lib/src/commands/Commands.ts

According to documentation passProps don't need to be serializable. So
don't try to deep clone them. Add tests for this behavior.
Should fix #6768

Pass props to components by ref (without deep cloning)

---

e2e/Buttons.test.js
lib/ios/NSArray+utils.m
playground/ios/NavigationTests/NSArray+utilsTest.m
playground/ios/playground.xcodeproj/project.pbxproj
playground/src/screens/RoundedButton.tsx

When calling mergeOptions to set a right button, the button was recreated even if the component specifies an `id`.

Fix unnecessary button recreation through mergeOptions

---

.github/ISSUE_TEMPLATE/bug.md
CONTRIBUTING.md

Fix 'Contribution Guidelines' links, without slash link is not working.

Fix 'Contribution Guidelines' links

---

lib/ios/AnimatedReactView.m
lib/ios/RNNViewLocation.h
lib/ios/RNNViewLocation.m

Restores the hijacked react view to the original position index.

Fix SET hijacked react view position index

---

website/docs/api/options-bottomTabs.mdx
website/versioned_docs/version-7.0.0/api/options-bottomTabs.mdx

`Android` was used instead of `Platform` in the header. I checked and `titleDisplayMode` is supported on both platforms, let's fix this.

Fix options.bottomTabs.titleDisplayMode

---

playground/src/screens/Screens.ts
playground/src/screens/index.tsx
playground/src/screens/sharedElementCarDealer/CarDetailsScreen.tsx
playground/src/screens/sharedElementCarDealer/Constants.ts
playground/src/screens/sharedElementCarDealer/ImageFullScreenViewer.tsx

Reproduction for Shared Element Transitions between different resize modes (`FastImage`)

Add full screen image viewer page for Car Dealer

---

lib/ios/RNNScrollEdgeAppearanceOptions.h
lib/ios/RNNScrollEdgeAppearanceOptions.m
lib/ios/TopBarAppearancePresenter.h
lib/ios/TopBarAppearancePresenter.m
lib/src/interfaces/Options.ts
playground/ios/NavigationTests/RNNNavigationStackManagerTest.m
playground/ios/NavigationTests/TopBarAppearancePresenterTest.m
website/docs/api/options-scrollEdgeAppearance.mdx

Add control over the `topBar` border in [scrollEdge](https://developer.apple.com/documentation/uikit/uinavigationbar/3198027-scrolledgeappearance) appearance mode.
Closes #6754

Add scrollEdgeAppearance border options

---

lib/ios/RNNUIBarButtonItem.m
playground/ios/NavigationTests/RNNUIBarButtonItemTest.m

[This commit](8131ea7650b997cbaefa2665fcad039005ae6955) created a bug where buttons received default size and not the original icon size which causes the insets to be bigger that it needed to be.

Fix default button size with insets

---

lib/ios/TopBarAppearancePresenter.m
playground/ios/NavigationTests/TopBarAppearancePresenterTest.m

Fixes `topBar` border visibility in [scrollEdge](https://developer.apple.com/documentation/uikit/uinavigationbar/3198027-scrolledgeappearance) appearance mode.
```js
scrollEdgeAppearance: {
active: true,
noBorder: true,
},
```
Closes #6754

Fix scrollEdgeAppearance border visibility

---

lib/ios/ViewAnimationOptions.m

Adds missing enable and waitForRender props for copying. Allows for showModal/dismissModal to run without animation.

Fix ViewAnimationOptions not merging correctly

---

lib/src/adapters/AssetResolver.ts
lib/src/interfaces/Options.ts

Closes #6099
Rationale: https://github.com/wix/react-native-navigation/issues/6099#issuecomment-702537239

Fix (Types) - Icon type does not accept object

---

lib/ios/RNNExternalViewController.m
playground/ios/NavigationTests/RNNExternalViewControllerTests.m

This PR fixes emitting `componentDidAppear` and `componentDidDisappear` events for external components.
Closes #6844

Fix external component appearance events

---

lib/ios/RNNCommandsHandler.m
lib/ios/RNNModalManager.m
playground/ios/NavigationTests/RNNModalManagerTest.m

Calling `Navigation.dismissAllModals` promise never resolved when no modals are presented. 
Closes #6875

Fix resolving dismissAllModals when there are no presented modals

---

lib/ios/RNNUIBarBackButtonItem.m

`UIBarButtonItem` `menu` property was added on iOS 14 and it fails the build in Xcode versions < 12.0.

Fix iOS build on older Xcode versions

---

lib/ios/RNNUIBarButtonItem.m
playground/ios/NavigationTests/RNNUIBarButtonItemTest.m

Fixes a regression created in [this commit](8131ea7650b997cbaefa2665fcad039005ae6955) which caused buttons with icon to never receive a tint color on iOS 12.
Closes #6877

Fix buttons tint color on iOS 12

---

lib/src/Navigation.ts
lib/src/commands/Commands.test.ts
lib/src/commands/Commands.ts
lib/src/commands/LayoutTreeCrawler.test.ts
lib/src/commands/LayoutTreeCrawler.ts
lib/src/commands/OptionsCrawler.test.ts
lib/src/commands/OptionsCrawler.ts
lib/src/commands/OptionsProcessor.test.ts
lib/src/interfaces/Layout.ts

We found out that [LayoutProcessors](https://wix.github.io/react-native-navigation/next/docs/style-theme/#conditional-themes-with-layout-processor) was missing the static options from the components. This PR fixes it.

Resolve component static options before calling layout processors

---

lib/ios/TopBarAppearancePresenter.m

Fixes `topBar` border visibility and color in `scrollEdge` appearance mode.
closes: [#6754](https://github.com/wix/react-native-navigation/issues/6754)
Calling `[self updateScrollEdgeAppearance]` as the latest part of applying options overrides `scrollEdge` properties since it applies predefined config with border by default:
```objc
- (void)updateScrollEdgeAppearance {
if (self.scrollEdgeTransparent) {
[self.getScrollEdgeAppearance configureWithTransparentBackground];
} else if (self.scrollEdgeAppearanceColor) {
[self.getScrollEdgeAppearance configureWithOpaqueBackground];
[self.getScrollEdgeAppearance setBackgroundColor:self.scrollEdgeAppearanceColor];
} else if (self.scrollEdgeTranslucent) {
[self.getScrollEdgeAppearance configureWithDefaultBackground];
} else { …
```

Change applying options order for scrollEdgeAppearance border properties

---

website/docs/api/options-scrollEdgeAppearance.mdx
website/docs/api/options-stack.mdx
website/versioned_docs/version-7.7.0/api/options-scrollEdgeAppearance.mdx
website/versioned_docs/version-7.7.0/api/options-stack.mdx
website/versioned_docs/version-7.8.1/api/options-scrollEdgeAppearance.mdx
website/versioned_docs/version-7.8.1/api/options-stack.mdx

Add specific (iOS 13+) version info regarding scrollEdgeAppearance.
Fix incorrect formatting of  `active` property.

Add minimal iOS scrollEdgeAppearance supported version, minor formatting fixes

---

lib/android/app/src/main/java/com/reactnativenavigation/views/stack/topbar/titlebar/TitleBar.java
lib/android/app/src/test/java/com/reactnativenavigation/views/stack/topbar/titlebar/TitleBarTest.java
playground/src/screens/CustomTopBar.tsx
playground/src/screens/OptionsScreen.tsx

**Issue:**
Closes #6883 
setting Component ignores alignment, works only on centre.
**Fix:**
- use-case tests added.
- rename `centerComponent` to `alignComponent`.
- calculate X where the component should be as the wanted alignment value set before in LayoutParams (alignment - gravity)
- support RTL into calculations (The component must be aware of this and adapt, RNN just change horizontal position)

Component title bar alignment fix

---

lib/src/index.ts

ProcessorSubscription is returned when registering an options or a layout processor. It wasn't exported by mistake.

Export ProcessorSubscription

---

lib/android/app/src/main/java/com/reactnativenavigation/views/stack/topbar/titlebar/TitleBar.java
lib/android/app/src/test/java/com/reactnativenavigation/views/stack/topbar/titlebar/TitleBarTest.java

There was a missing margin at the start of the custom title, added into considerations to fix backwards compatibility with the default spaces

add missing default margin in component title bar

---

lib/android/app/src/main/java/com/reactnativenavigation/utils/ImageLoader.kt

As @guyca suggested, this fix an issue where the icon color was modified in release mode, because resources are bundled in release. RNN was changing the Drawable's color, but wasn't mutating the drawable.

Fix icon color being applied to all instances of the same icon in release mode

---

lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/bottomtabs/BottomTabPresenter.java

I see that this issue is kinda present in the issue backlog so I've decided to fix it (since it happened to me). 
This is the error that I'm encountering: 
```
java.lang.NullPointerException: Attempt to invoke virtual method 'float java.lang.Float.floatValue()' on a null object reference
at com.aurelhubert.ahbottomnavigation.AHBottomNavigation.setTitleInactiveTextSizeInSp(AHBottomNavigation.java:1311)
at com.reactnativenavigation.viewcontrollers.bottomtabs.BottomTabPresenter.lambda$applyOptions$0$BottomTabPresenter(BottomTabPresenter.java:65)
at com.reactnativenavigation.viewcontrollers.bottomtabs.-$$Lambda$BottomTabPresenter$xw0BqWFLHJmeiaHq_MSiMyHoYmc.run(Unknown Source:4)
at com.reactnativenavigation.utils.LateInit.perform(LateInit.java:19)
```
basically my assumption is that calling …

Fix SET when pushing a screen from bottom tabs

---

lib/src/Navigation.ts
lib/src/commands/Commands.test.ts
lib/src/commands/OptionsCrawler.test.ts
lib/src/commands/OptionsCrawler.ts

Generate `componentId` before calling static options function with passProps that should contain the `componentId`.
Closes #6916

 Fix undefined passProps.componentId in static options

---

lib/src/Navigation.ts
lib/src/commands/OptionsCrawler.ts
lib/src/commands/OptionsProcessor.test.ts
lib/src/commands/OptionsProcessor.ts
lib/src/interfaces/Processors.ts
website/docs/docs/style-theme/option-processor.tsx

This PR adds the ability to receive the component `passProps` in option processor.
```js
Navigation.addOptionProcessor<OptionsTopBar>(
'topBar',
(topBar: OptionsTopBar, commandName: string, props: any): OptionsTopBar => {
return topBar;
}
);
```

Pass component props to option processors

---

lib/ios/RNNButtonOptions.m

Setting buttons with `systemItem` stopped working in [this commit](https://github.com/wix/react-native-navigation/commit/08a9630220c7d1a166b99bfe3c42ff7cc1cbdfd0).
Closes #6924, #6911

Fix systemItem buttons

---

lib/ios/TransitionDelegate.m

The shared element animation `transitionContext` is strongly held by the `transitionDelegate` which resulted in a leak. 
@mrousavy Awesome finding!
Closes #6929

Fix a leak in shared element animation

---

lib/android/app/src/main/java/com/reactnativenavigation/views/element/finder/ExistingViewFinder.kt

Not sure why, but we started seeing null pointer errors when running SETs.
@guyca could you please take a look and tell me if that fix is a good idea or just a lazy workaround?
```
E  Process: com.cuvent.experiences.friends, PID: 21034
E  java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.drawable.Drawable.getIntrinsicWidth()' on a null object reference
E      at com.reactnativenavigation.views.element.finder.ExistingViewFinder.hasMeasuredDrawable(ExistingViewFinder.kt:59)
E      at com.reactnativenavigation.views.element.finder.ExistingViewFinder.find(ExistingViewFinder.kt:21)
E      at com.reactnativenavigation.views.element.TransitionSetCreator$createSharedElementTransitions$2$invokeSuspend$$inlined$map$lambda$1.invokeSuspend(TransitionSetCreator.kt:3 …
```

Check view.drawable for null before reading width/height

---

lib/ios/RNNBottomTabOptions.h
lib/ios/RNNBottomTabOptions.m
lib/ios/RNNTabBarItemCreator.m
lib/src/interfaces/Options.ts
website/docs/api/options-bottomTab.mdx

Overrides the text that's read by the screen reader when the user interacts with the `bottomTab` button.

Add bottomTab.accessibilityLabel

---

autolink/postlink/path.js
autolink/postlink/plistLinker.js
autolink/postlink/postLinkIOS.js

In order to control the `statusBar` appearance on iOS through RNN, adding `UIViewControllerBasedStatusBarAppearance` true to the project `info.plist` was a mandatory step. 
Now this step will no longer be needed as the link script will update it automatically.

Enable UIViewControllerBasedStatusBarAppearance on rnn-link

---

lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/stack/topbar/button/ButtonPresenter.kt
lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/stack/topbar/button/IconResolver.java
lib/android/app/src/main/java/com/reactnativenavigation/views/stack/topbar/titlebar/IconBackgroundDrawable.kt
lib/android/app/src/test/java/com/reactnativenavigation/fakes/IconResolverFake.kt
lib/android/app/src/test/java/com/reactnativenavigation/mocks/ImageLoaderMock.kt
lib/android/app/src/test/java/com/reactnativenavigation/utils/ButtonPresenterTest.java
lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/stack/TopBarButtonControllerTest.java

**Issue:**
#6938
Crashing when setting `iconBackground`, it was crashing because of missing conditions that yield different results of colours depending on the options.
**Fix:**
Added tests that simulate the wanted behaviour, fix the crash by checking that bg colour selection is done correctly as the options suggesting, make sure colours changing as expected.

Fix Icon bg color crash

---

lib/android/app/src/main/java/com/reactnativenavigation/views/bottomtabs/BottomTabsContainer.kt
lib/android/app/src/main/java/com/reactnativenavigation/views/bottomtabs/ShadowLayout.kt

shadow was enabled by default, changed to opt-in, by having valid shadow options in the BottomTabsOptions

Bottom tabs shadow default visibility

---

website/docs/docs/style-animations.mdx

See [this line](https://github.com/wix/react-native-navigation/blob/a867b417926e51a56f289da92111c32c798d3f05/lib/android/app/src/main/java/com/reactnativenavigation/options/parsers/InterpolationParser.java#L47) in the Android package and [this line](https://github.com/wix/react-native-navigation/blob/a867b417926e51a56f289da92111c32c798d3f05/lib/ios/RCTConvert%2BInterpolation.m#L63) in the iOS package. 
Seems like the docs say its 1000 by default when it should be 200 🤔

docs: fix default `stiffness` value

---

lib/android/app/src/main/java/com/reactnativenavigation/options/FadeInAnimation.kt
lib/android/app/src/main/java/com/reactnativenavigation/options/FadeOutAnimation.kt

Fix shared element transition is broken when `content` property is missing. It should fallback to the default fade animation.
Closes #6957

Fix SET default fade animation

---

lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/stack/StackPresenter.java
lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/stack/StackPresenterTest.kt

When passing empty `rightButtons` with `rightButtonColors` it caused a crash.
example here: #6970
Checking for nulls when applying colours for empty buttons list, Right and left.
Added test that covers the flow.
Closes #6970

Fix Crash topBar merge empty buttons with color

---

website/docs/api/options-stack.mdx

Add missing documentation about `TopBarOptions.height`, stating about android only, and on iOS referring to `largeTitle` Option.
Closes #6983

add missing TopBar Height documentation 

---

website/versioned_docs/version-7.11.0/api/options-layout.mdx

It's not clear when using `rtl` feature that in android, projects that want RTL support should declare that (`android:supportsRtl="true"`) in the `AndroidManifest.xml`, like in the playground.
Updated the docs about this note.
Closes #6974.

add missing Android RTL manifest attribute to docs

---

lib/ios/RNNNavigationBarDelegateHandler.h
lib/ios/RNNNavigationBarDelegateHandler.m
lib/ios/RNNStackController.m
lib/ios/ReactNativeNavigation.xcodeproj/project.pbxproj

On iOS 12 and below, `navigationBar:shouldPopItem` behave differently than the following iOS versions, Thus it should have its own specific implementation.
Closes #6993

Fix back button doesn't pop on iOS 12

---

lib/ios/RNNScreenTransition.m

[This commit](https://github.com/wix/react-native-navigation/commit/17c82b456e0d6b0ee79f3d2a1643fe14054bf069) added exit screen animation option on Android and by that changed the object received in native. We should have update it on iOS as well. This PR fixes it.
Closes #6992

Fix custom animations on iOS

---

lib/ios/RNNBottomTabsController.m
playground/ios/NavigationTests/BottomTabsControllerTest.m

On iOS, when there are more than 5 tabs, the fifth tab becomes "more" tab. This tab is not clickable since we added `selectTabOnPress`. This PR fixes it.

Fix bottomTabs More tab not clickable

---

lib/ios/RNNComponentView.m

This PR fixes a crash caused by a KVO observer that isn't cleared.
Closes #7009

Remove yellowBox observer on dealloc

---

lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/viewcontroller/ViewController.java
lib/android/app/src/main/java/com/reactnativenavigation/views/stack/topbar/titlebar/MainToolBar.kt
lib/android/app/src/test/java/com/reactnativenavigation/mocks/SimpleViewController.java
lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/navigator/NavigatorTest.java
lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/viewcontroller/ViewControllerTest.java
lib/android/app/src/test/java/com/reactnativenavigation/views/MainToolbarTest.kt

Apps using RNN with `title.component` defined as a react component, might get this crash.
I'll share my insights as a logical flow:
- The crash itself is about casting the [`ReactClippingViewGroupManager.getChildCount(T parent)`](https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/views/view/ReactClippingViewManager.java#L53) template param, `parent` that is declared to extend `ReactViewGroup`.
- `parent` in this case is a `TitleBarReactView`, which is a `ReactRootView` but it isn't a `ReactViewGroup`.
- Since the stack trace indicates **line 19** in the [`ReactClippingViewGroupManager`](https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/views/view/ReactClippingViewManager.java) it is mostly …

Title react view crash

---

website/docs/api/options-hardwareBackButton.mdx
website/versioned_docs/version-7.11.2/api/options-hardwareBackButton.mdx

The hardwareBackButton is not part of the TopBar options object, and is Android only.

Fix hardwareBackButton docs

---

lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/stack/StackPresenter.java
lib/android/app/src/main/java/com/reactnativenavigation/views/stack/topbar/TopBar.java
lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/stack/StackPresenterTest.kt

when setting default alignment in default options it wasn't being respected when `mergeOptions` called with options that do not include alignment, like updating the text or colour, it was resetting the alignment.
- Use the result of default options merged with requested options to update
- Ensure that alignment change should apply to the container when changing subtitle
CC: @danilobuerger

Android mergeOptions subtitle center & margin fix

---

lib/android/app/src/main/java/com/reactnativenavigation/options/ElementTransitions.kt
lib/android/app/src/main/java/com/reactnativenavigation/options/SharedElements.kt
lib/android/app/src/main/java/com/reactnativenavigation/options/TransitionAnimationOptions.kt

Crashing over parsing the wrong types for modal animations.
Ensure that animations are parsed with the correct type.
Closes #7020

Fix shared element crash on Android

---

lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/stack/StackPresenter.java
lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/stack/StackPresenterTest.kt

MergeOptions with `topBar.backButton.someProp` on a stack that has single child (nothing to pop) showed back button.
Make sure that no changes to the back button should apply to the Stack with one child

BackButton on stack root fix

---

playground/src/screens/SideMenuCenterScreen.tsx

TSC is unhappy as `leftButtons` is defined as an object instead of an array. Declaring buttons as a single object is not reflected in Options, but still supported. We should keep this options as is since it serves as some sort of sanity ensuring the old API is still supported.

Fix TypeScript error in the playground app

---

lib/src/commands/OptionsProcessor.test.ts
lib/src/commands/OptionsProcessor.ts

Processing `setRoot` animations options for enter and exit animations on Android broke the iOS implementation.
Closes #7068, #7066

Fix setRoot animations on iOS

---

lib/ios/AnimatedImageView.m
lib/ios/UIImageView+Transition.h
lib/ios/UIImageView+Transition.m

Fixes https://github.com/wix/react-native-navigation/issues/7078.
@yogevbd was there a specific reason to only account for the Image Scale in `UIViewContentModeScaleAspectFit`? All other contentModes just used the image width/height without dividing by it's scale. I changed it so that now every contentMode respects the scale.

Fix SET if image has not yet been loaded

---

lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/modal/ModalAnimator.kt
lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/modal/ModalPresenter.java
lib/android/app/src/test/java/com/reactnativenavigation/options/TransitionAnimationOptionsTest.kt
lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/modal/ModalAnimatorTest.kt

Showing modal with shared element transition broke, in the opening direction, while it is working in the closing direction, like when opening a card in the Car dealer in the Playground, the shared card won't animate to the new position, fading instead.
https://user-images.githubusercontent.com/7227793/114307698-7cfdd700-9ae9-11eb-8f4c-d4ca4235e9db.mov
Check and test that SharedElement transition is playing, matching `push` shared element behaviour, making `showModal` and `push` aligned since push does not suffer such misbehaving in shared element.
https://user-images.githubusercontent.com/7227793/114307791-c2ba9f80-9ae9-11eb-9068-8931a8238994.mov
Closes: #7070

Shared element android fix

---

website/docs/docs/style-theme/option-processor-defaults.tsx
website/versioned_docs/version-6.12.2/docs/style-theme/option-processor-defaults.tsx
website/versioned_docs/version-7.11.2/docs/style-theme/option-processor-defaults.tsx
website/versioned_docs/version-7.13.0/docs/style-theme/option-processor-defaults.tsx
website/versioned_docs/version-7.7.0/docs/style-theme/option-processor-defaults.tsx

Update option-processor-defaults example to work. The current example wouldn't work properly or do anything b/c an array of rightButtons is returned to the processor, not a single button.

docs: Update option-processor rightButtons example

---

website/versioned_docs/version-7.13.0/api/options-bottomTab.mdx

This appears twice, and is applicable for both platforms, so I removed the "Android" specific version.

Remove duplicate disableIconTint option in API documentation.

---

lib/ios/RNNBottomTabsController.m

Fix `tabsAttachMode: 'afterInitialTab'` option for `bottomTabs` used in a `sideMenu` layout.
Closes #7095

Fix tabsAttachMode: 'afterInitialTab'

---

lib/android/app/src/main/java/com/reactnativenavigation/views/element/animators/FastImageBorderRadiusAnimator+utilities.kt
lib/android/app/src/main/java/com/reactnativenavigation/views/element/animators/FastImageBorderRadiusAnimator.kt

The `FastImageBorderRadiusAnimator#shouldAnimateProperty` returned false in cases where the `FastImage` component is a child of another component that has a border radius. Example for such a use case:
```jsx
<View style={{ borderRadius: 30, overflow: "hidden" }}>
<FastImage {...} />
</View>
```
In this case the animation would look like this. You can see that the borders will "make a jump" once the SET is finished:
https://user-images.githubusercontent.com/16821682/118120763-aebbd380-b3f0-11eb-879f-1348b11721a0.mp4
I wrote a function that checks recursively:
* If the view is a ReactView -> try to get border radius from this react view
* If the view is a FastImageView -> try to get border radius from this FastImage view
* If it founds a border radius it returns …

Fix fast image border animation

---

lib/ios/RNNAnimationsOptions.m
lib/ios/ViewAnimationOptions.m

Reverts wix/react-native-navigation#7091 as it broke shared element transitions on iOS.

Revert "Fix disabling modal animations on iOS"

---

ReactNativeNavigation.podspec

Was renamed in https://github.com/facebook/react-native/commit/941bc0ec195716e6a505a3c3a67f97a87ea9bcdc

Rename folly spec dependency

---

autolink/postlink/appDelegateLinker.js
lib/ios/RNNBridgeManager.h
lib/ios/RNNBridgeManager.mm
lib/ios/ReactNativeNavigation.h
lib/ios/ReactNativeNavigation.m
playground/ios/playground/AppDelegate.m

* Bootstrap with user created bridge instead of creating own bridge instance
* initialize `RNNBridgeManager` in the `extraModulesForBridge` call
* , allows support for Fabric
* , allows support for injecting custom TurboModules into ExecutorFactory
* Update rnn-link script
> Based on https://github.com/wix/react-native-navigation/pull/6835

feat: Bootstrap with user-created Bridge, add support for Fabric

---

lib/android/app/src/main/java/com/reactnativenavigation/views/stack/topbar/titlebar/TitleAndButtonsMeasurer.kt
lib/android/app/src/main/java/com/reactnativenavigation/views/stack/topbar/titlebar/TitleBarReactView.kt
playground/android/build.gradle

Moving to Kortlin 1.4 is a breaking change, applying proper changes, delaying 1.4 to RNN v8 #7034.
CC: @yogevbd

downgrade kotlin 

---

lib/android/app/src/main/java/com/reactnativenavigation/views/stack/topbar/titlebar/TitleBarReactView.kt

`maxBy` was deprecated for Kotlin >= 1.4.x, while `maxByOrNull` is not supported in 1.3.x, so, for now, it's being replaced by Kotlin independent way to find child max measured width of react component.
RNN v8 may have a minimum requirement for Kotlin as 1.4 or 1.5.

Fix Kotlin 1.3 & 1.4 compatibility

---

lib/android/app/src/main/java/com/reactnativenavigation/react/NavigationModule.java
lib/ios/RNNBridgeModule.m
lib/src/Navigation.ts
lib/src/adapters/Constants.ts

Allows getting the `NavigationConstants` synchronously. Useful wherever async waiting is not possible.

Add synchronous constants call

---

lib/ios/RNNCommandsHandler.m

This should resolve the promise even if you add a none existing componentId to `popTo`.
More context: https://github.com/wix/react-native-navigation/issues/7152

fix popTo so promise get resolved

---

package.json

Since we use `remx` as the store in Navigation mock, it is no longer a dev dependency.

Move remx from devDependencies

---

lib/android/app/src/main/java/com/reactnativenavigation/react/NavigationModule.java
lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/navigator/Navigator.java
lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/parent/ParentController.java
lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/navigator/NavigatorTest.java
lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/parent/ParentControllerTest.java

When the app switches to BG or a new activity is opened, appearance events did not get sent to the RN side, since it's logical to have them sent when the app is not visible, which means every visible component now is invisible, and vice versa.
Support sending `DidAppear/Disappear` events when activity changes visibility state, `OnPause` & `OnResume`.
Closes: #7158

Activity lifecycle send DidAppear & Disappear 

---

tsconfig.json

When configured as `react-native`, jsx is not converted to function calls https://www.typescriptlang.org/tsconfig#jsx .  This means other tools (e.g. `jest`) must themselves be configured to transpile, instead of being able to consume the js directly.

Compile jsx to plain js

---

lib/src/commands/Commands.test.ts
lib/src/commands/Commands.ts
lib/src/components/ComponentWrapper.test.tsx
lib/src/components/ComponentWrapper.tsx
lib/src/components/Store.ts

Invoking `Navigation.mergeOptions()` before the component is mounted is wrong and can cause flickering UI as it updates the native views while the screen is in the middle of the presentation animation.
For that we have the static options which should always be used when we want to initialise the screen with options.

Warn when calling mergeOptions before component is mounted

---

lib/src/NavigationDelegate.ts
website/docs/docs/style-constants.mdx

`Navigation.constantsSync()` was introduced in [v7.17.1](https://github.com/wix/react-native-navigation/releases/tag/7.17.1) but is not accessible on the `Navigation` object. This PR fixes that, and adds some documentation for the new method.

Added `constantsSync` to delegate, updated docs

---

lib/ios/RNNOverlayWindow.m

Presenting react-native declarative modals from an overlay freeze the app as the overlay window didn't pass the touch event to the underlying window.

Fix persenting react-native modals from overlays

---

lib/ios/RNNUIBarButtonItem.m

Currently on iOS, adding top bar buttons with no color always fallbacks to the system default tint color. This behaviour makes rendering the original image impossible.
Closes #6934

Render original top bar image when no color provided

---

website/docs/docs/docs-stack.mdx
website/docs/docs/stack-buttons.mdx
website/versioned_docs/version-6.12.2/docs/docs-stack.mdx
website/versioned_docs/version-6.12.2/docs/stack-buttons.mdx
website/versioned_docs/version-7.11.2/docs/docs-stack.mdx
website/versioned_docs/version-7.11.2/docs/stack-buttons.mdx
website/versioned_docs/version-7.16.0/docs/docs-stack.mdx
website/versioned_docs/version-7.16.0/docs/stack-buttons.mdx
website/versioned_docs/version-7.7.0/docs/docs-stack.mdx
website/versioned_docs/version-7.7.0/docs/stack-buttons.mdx

This took me some time. For searchability, using a string instead of the object for component throws "Attempted to assign to readonly property.". Leaving out the id freezes the app (it's marked as mandatory in the button docs).

docs: Fix wrong API in example for custom button

---

lib/ios/RNNComponentPresenter.m
playground/ios/NavigationTests/RNNComponentPresenterTest.m

When we added button animations feature, our intention was to disable it by default for backward compatibility. 
Closes #7168

Disable button animations on iOS by default

---

e2e/BottomTabs.test.js
lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/bottomtabs/BottomTabPresenter.java
lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/bottomtabs/BottomTabPresenterTest.java
playground/src/screens/SecondBottomTabScreen.tsx

Badge got cleared on this flow:
- set badge on a tab
- Push a screen
- open a modal from the pushed screen
- dismiss modal
- badge got cleared
Prevent applying empty badge when there is no value

Badge cleared dismissing modal Fix

---

lib/ios/RNNBackButtonOptions.m

Fixes #7208 This allows displayMode on iOS to actually function (ish. The if clause in L192 of TopBarPresenter.m at least can enter now, but displayMode is not respected).
Note: L192 of TopBarPresenter.m needs reworking of the logic in order to accommodate for the showTitle option. For some reason, current implementation does not respect displayMode minimal. However, like what the original comment said, if you just comment out L199, it'll just "work". Additionally, if someone specifies a displayMode of "default" with some kind of color, then the backItem is not actually used in the current implementation and thus is an unexpected behavior.
So L199 always executes for some reason? This table summarizes how because L199 is executed, the title still appears: …

Add missing displayMode from RNNBackButtonOptions

---

package.json

Moving remx to optional peer dependencies as it isn't always needed as a dependency. 
It is needed only when consuming our mocks in render tests (Introduced in #7140).
Closes #7187

Move remx to optional peer dependencies

---

lib/src/Mock/mocks/AppRegistryService.ts
lib/src/Navigation.ts
lib/src/NavigationDelegate.ts

We don't need to register the component using react-native's `AppRegistry` as in mocked mode we read it from our own store.

Avoid calling AppRegistry.registerComponent in mocked mode

---

lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/viewcontroller/Presenter.java

Modify flags for DecorView in the global main thread handler caused ui to freeze when calling `mergeOptions` inside useEffect.
This happens on Samsung devices with Android 9, that seems it has issues internally since it is not reproduce on emulator and other devices including Samsungs with new android versions.
The workaround was to set the flags in a task to run in the DecorView MessageQueue in order to ensure flags are set when the DecorView is ready internally to accept changes.

Status bar updates causes ui freeze on some devices

---

lib/src/commands/OptionsProcessor.test.ts
lib/src/commands/OptionsProcessor.ts

DynamicColorIOS stopped working In [this PR](#7178). This PR fix it.
Closes #7247

Support DynamicColorIOS

---

website/docs/docs/community-libraries.mdx
website/versioned_docs/version-7.16.0/docs/community-libraries.mdx

Couldn't find a ready-to-use solution for a bottom sheet component that would work seamlessly with react-native-navigation, so decided to write my own - [React Native Navigation Bottom Sheet Extension](https://github.com/CursedWizard/react-native-navigation-bottom-sheet). Added it to community libraries in docs.
Also made the list of packages a little bit more organized.

docs: updated community libraries.

---

lib/src/commands/OptionsProcessor.test.ts
lib/src/commands/OptionsProcessor.ts

On iOS, `DynamicColorIOS` should never receive undefined or null values, therefor there is no reason to always pass the native `DynamicColorIOS` even when the color value is undefined.

Fix color processing on iOS

---

lib/android/app/src/main/java/com/reactnativenavigation/views/stack/topbar/titlebar/TitleBarReactButtonView.java

Fixes #7229 
It also happens with left button.
Also noticed that width spec was used for the height measurement (probably typo).

Fix left and right top bar buttons with component crash on Android

---

website/docs/docs/docs-sideMenu.mdx

Updated the example using `Navigation.mergeOptions` to open the side menu with the correct first argument.

Fix sideMenu docs

---

lib/android/app/src/main/java/com/reactnativenavigation/NavigationActivity.java

User can set their own `windowBackground` in his xml style to match the theme

Remove default splash layout color on Android

---

lib/ios/RNNDotIndicatorPresenter.m
playground/ios/NavigationTests/RNNDotIndicatorPresenterTest.m

- Fixes #6411 
- Fixes the crash if `dotIndicator` is applied without `icon` in tab

Fix dot indicator location on iOS

---

website/docs/docs/docs-customBackNavigation.mdx
website/versioned_docs/version-7.16.0/docs/docs-customBackNavigation.mdx

Actual buttonId for hardware back button event is `RNN.hardwareBackButton`, not `RNN.hardwareBack` :-)

Fix hardware back button event button id in docs

---

lib/ios/RNNAssert.h
lib/ios/RNNBottomTabOptions.m
lib/ios/RNNButtonBuilder.m
lib/ios/RNNButtonOptions.m
lib/ios/RNNCommandsHandler.m
lib/ios/RNNDotIndicatorPresenter.m
lib/ios/RNNModalManager.h
lib/ios/RNNModalManager.m
lib/ios/RNNSegmentedControl.h
lib/ios/RNNTabBarItemCreator.m
lib/ios/RNNUIBarButtonItem.h
lib/ios/RNNUIBarButtonItem.m
lib/ios/TopBarPresenter.m

Currently we manually dismiss all modals on `setRoot`, we should instead clear it from the modal manager so that those controllers will be automatically released by the reference count system.

Remove manually dismissing all modals on setRoot

---

lib/android/app/src/main/java/com/reactnativenavigation/options/LayoutFactory.java
lib/android/app/src/main/java/com/reactnativenavigation/options/Options.java
lib/android/app/src/test/java/com/reactnativenavigation/utils/LayoutFactoryTest.java

When parsing options, `ReactInstanceManager.getCurrentContext()` might return null, which caused color parsing to throw null exception since it assumes that context is not null.
This can be the case when Activity was killed but the Application still alive (Don't keep activity for example), and since js is bound to the Application lifecycle, opening the activity triggers recreating context in bg, in the meantime calling a command that requires reactContext can cause such crashes to unwanted behaviours when react context is needed.
This happens internally and it looks like it is some flow where calling navigation command when react is not ready. 
Since the issue did not happen before, and the crash occurred in parsing options that are independent of `ReactContext`, we can use Activity or …

Android context crash when parsing options

---

e2e/BottomTabs.test.js
lib/src/Mock/Components/ComponentScreen.tsx
lib/src/Mock/Stores/EventsStore.ts
lib/src/Mock/mocks/NativeEventsReceiver.ts
playground/src/screens/FirstBottomTabScreen.tsx
playground/src/screens/LayoutsScreen.tsx

* Fix sending bottomTabPressed event when using our mocks
* Throw error when trying to load an unregistered component
* Support `selectTabIndex` in our mocks

[Navigation Mock] Fix bottomTabPressed event

---

lib/ios/UIViewController+RNNOptions.m

Until now we used `UIBlurEffectStyleLight` effect on the `statusBar` background. In order to support dark mode blur color, we need to use `UIBlurEffectStyleRegular` so the system can automatically decide which style to use.
Closes #7346

Fix statusBar blur option in dark mode

---

lib/src/commands/Commands.test.ts
lib/src/commands/Commands.ts
lib/src/commands/LayoutTreeCrawler.ts
lib/src/commands/OptionsProcessor.test.ts
lib/src/commands/OptionsProcessor.ts

We missed `mergeOptions` processing on the following commands: `pop`, `popTo`, `popToRoot`, `dismissModal` and `dismissAllModals`. That resulted in a bug where using the old animations syntax didn't work.

Fix missing options processing

---

playground/src/screens/sharedElementCarDealer/CarCard.tsx
playground/src/screens/sharedElementCarDealer/CarDetailsScreen.tsx
playground/src/screens/sharedElementCarDealer/CarStoryScreen.tsx
playground/src/screens/sharedElementCarDealer/useDismissGesture.ts

Fix playground reanimated animations

---

lib/android/app/src/main/java/com/reactnativenavigation/react/ReactView.java
lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/component/ComponentViewController.java
lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/modal/ModalPresenter.java
lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/stack/StackController.java
lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/component/ComponentViewControllerTest.java
lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/modal/ModalStackTest.java
lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/toptabs/TopTabsViewControllerTest.java
playground/src/screens/LayoutsScreen.tsx
playground/src/screens/NavigationScreen.tsx
playground/src/screens/OptionsScreen.tsx

`componentDidDisappear` event was sent, on a component that is not even displayed in the past, it happens, when using slow enter/exit animations, as described [here](https://github.com/swabbass/navigation-bar-demo/blob/master/index.js#L7), once, with the default animation it seems not happening, but with slow enter/exit, which starts to Exit Navigator which has already the newly added view (pushed) on top and while animating the navigator sees the new entering view on top since we add the entering view to the hierarchy with alpha 0 and then making the animation, which caused a case where disappear called when a view is not even received disappear.
#Fix: 
- Prevent sending disappear on already disappeared view.
- Post Events on ReactView MessagesQueue in order to keep view sync with …

ComponentDidDisappear event Android fix

---

.npmignore
lib/android/app/build.gradle
scripts/test-unit.js

Exclude android native unit tests and their dependencies from being passed to other projects.

Exclude android unit tests for non playground projects

---

lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/component/ComponentViewController.java
playground/src/screens/KeyboardScreen.tsx

When Bottom tabs are visible a margin is added on top of the keyboard when it was opened.
The margin is a bottom inset set to component due to bottom tabs height, which always will push the component up by bottom tabs height pixels.
- Determine bottom insets when bottom tabs are hidden or visible.
- Subtract the component bottom inset from new insets once the keyboard is opened.

Fix keyboard bottom insets removing bottom tabs margin

---

lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/component/ComponentViewController.java
lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/sidemenu/SideMenuControllerTest.java

Window insets does not apply when keyboard got closed in case of adjustPan, and in case of adjustNothing it will just ignore it and treat it like adjustResize.
The difference between Pan and Resize as pointed [here](https://www.techrepublic.com/article/pro-tip-make-sense-of-pan-vs-resize-in-the-android-manifest/):
adjustResize: The activity’s main window is always resized to make room for the soft keyboard on screen.
adjustPan: The activity’s main window is not resized to make room for the soft keyboard. Rather, the contents of the window are automatically panned so that the current focus is never obscured by the keyboard and users can always see what they are typing. **This is generally less desirable than resizing, because the user may need to close the soft keyboard to get at and …

Android < 30 Keyboard insets adjustNothing & adjustPan Fix

---

lib/ios/RNNComponentRootView.m

This reverts commit 345344a2c27611c6b3dc24f7a54742b2df25a7cc.
It seems like removing the setAvailableSize call has caused issues for some people (#7457). So I would recommend reverting this for now although I still don't think that the setAvailableSize call is really necessary here. It seems like the issues are caused by another problem thats just masked by this. We will need to investigate this further.

Revert "Remove unneeded RCTUIManager setAvailableSize call (#7412)"

---

lib/android/app/build.gradle

See [Issue 7463](https://github.com/wix/react-native-navigation/issues/7463)

Fix Build Error After Upgrading To Android Gradle Plugin 7.1.1

---

lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/viewcontroller/Presenter.java

`getLayoutParams()` can return null if the view is not currently attached. This may occur during device rotation.
Fixes #7473

Resolve android crash on device rotate

---

lib/ios/UINavigationController+RNNOptions.m
lib/ios/UIViewController+LayoutProtocol.m
playground/ios/NavigationTests/UIViewController+LayoutProtocolTest.m

`bottomTabs` and `topBar` height constants resolved incorrectly, fixed it to be resolved from the current visible screen.
Closes #7514

Fix Navigation bottomTabs and topBar height constants

---

lib/ios/RNNModalManager.m
playground/ios/NavigationTests/RNNModalManagerTest.m

This caused a bug in our Wix app when presenting a modal while another one is dismissed. The presented modal was dismissed as well along with the one that was being dismissed.

Avoid returning modal that is being dismissed as the top presented viewController

---

lib/android/app/build.gradle
lib/android/app/src/main/AndroidManifest.xml
lib/android/app/src/main/java/com/reactnativenavigation/NavigationActivity.java
lib/android/app/src/test/java/com/reactnativenavigation/TestActivity.java
playground/android/build.gradle

This reverts commit 2d247ce5b82d9de0de0f40c138eb2267b78f8972.

Revert "Revert "Added support for the predictive back gesture on Android

---

lib/Mock/mocks/NativeCommandsSender.tsx
lib/src/Navigation.ts
lib/src/adapters/Constants.ts
lib/src/adapters/NativeCommandsSender.ts
lib/src/commands/Commands.ts
lib/src/commands/OptionsCrawler.ts
lib/src/processors/LayoutProcessor.ts

Until now, invoking `Navigation.constants()` and `Navigation.constantsSync()` failed in our headless tests.
This PR fix this and some lint issues.

Support constants in Navigation mocks

---

lib/android/app/src/main/java/com/reactnativenavigation/utils/UiUtils.java

This fixes a crash happening in the Wix app, look like there's a race condition where the activity is destroyed and `navigator.onHostPause()`gets called too late. Most of times this shouldn't be delayed as it is called on the main thread.

Fix runOnMainThread to postAtFrontOfQueue when already on the main thread

---

lib/ios/SharedElementAnimator.m

Previously if an element was not found, then it would break out of the loop looking for further (possibly valid) shared element transitions. Now it'll continue the loop, which is the expected behavior.

Fix SharedElementAnimator missing some animations

---

lib/android/app/build.gradle
lib/android/app/src/reactNative71/java/com/reactnativenavigation/options/parsers/ColorParser.kt
lib/android/app/src/reactNative71/java/com/reactnativenavigation/react/DevBundleDownloadListenerAdapter.java
lib/android/app/src/reactNative71/java/com/reactnativenavigation/react/JsDevReloadHandlerFacade.java
lib/android/app/src/reactNative71/java/com/reactnativenavigation/react/NavigationReactNativeHost.java
lib/android/app/src/reactNative71/java/com/reactnativenavigation/react/ReactGateway.java
lib/android/app/src/reactNative71/java/com/reactnativenavigation/react/ReloadHandlerFacade.java
lib/android/app/src/reactNative71/java/com/reactnativenavigation/react/modal/ModalContentLayout.kt
lib/android/app/src/reactNative71/java/com/reactnativenavigation/viewcontrollers/viewcontroller/YellowBoxHelper.java

Add new flavor for RN 0.71

---

lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/parent/ParentController.java
lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/parent/ParentControllerTest.java

1. Set system theme to light.
2. Create stack root with multiple tabs
3. Set nav bar color to black on first tab.
```
Navigation.mergeOptions({
navigationBar: {
backgroundColor: '#000000',
}
});
```
4. Change app orientation.
**Expected Result:** Nav bar stays black.
**Achieved Result:** Nav bar becomes white.
As I've figured out during debugging, `mergeOptions` changes only option of controller with specified `componentId`. However, when `Navigator.onConfigurationChanged` is invoked the options of all existing controllers are being applied to presenter, therefore the last created controller's options are finally set.
Check for `controller.isViewShown` before triggering it's `onConfigurationChanged`.

Fix: Wrong options are set when onConfigurationChanged occurs

---

lib/ios/Utils/UITabBarController+RNNUtils.m
playground/src/screens/FirstBottomTabScreen.tsx
playground/src/screens/SecondBottomTabScreen.tsx

Fix the bottomTab dotIndicator is displayed at a wrong tab button after changing the badge state.
Related issue: https://github.com/wix/react-native-navigation/issues/7146
It happens after we modify the badge option by calling `mergeOptions` .
https://user-images.githubusercontent.com/25456520/218294543-57d214ec-322f-40c2-9dce-bd4a86fd8354.mp4
Fix `getTabView` to return the correct view at the given index.
It currently uses `subviews` to find the view at index, but it doesn't work after tab bar buttons are modified.
Fixed it by using `tabBarItemViewAtIndex` which is already implemented.

[iOS] Fix: the bottomTab dotIndicator is sometimes displayed at a wrong tab button

---

lib/src/components/ComponentWrapper.test.tsx
lib/src/components/ComponentWrapper.tsx
lib/src/interfaces/NavigationComponentProps.ts

Currently we inject only the `componentId` to screens, this PR add `componentName` as well.

pass componentName prop to screens

---

lib/android/app/src/main/java/com/reactnativenavigation/views/stack/topbar/titlebar/TitleAndButtonsContainer.kt
lib/android/app/src/reactNative51/java/com/reactnativenavigation/views/stack/topbar/titlebar/TitleBarReactView.kt
lib/android/app/src/reactNative55/java/com/reactnativenavigation/views/stack/topbar/titlebar/TitleBarReactView.kt
lib/android/app/src/reactNative56/java/com/reactnativenavigation/views/stack/topbar/titlebar/TitleBarReactView.kt
lib/android/app/src/reactNative57/java/com/reactnativenavigation/views/stack/topbar/titlebar/TitleBarReactView.kt
lib/android/app/src/reactNative57_5/java/com/reactnativenavigation/views/stack/topbar/titlebar/TitleBarReactView.kt
lib/android/app/src/reactNative60/java/com/reactnativenavigation/views/stack/topbar/titlebar/TitleBarReactView.kt
lib/android/app/src/reactNative62/java/com/reactnativenavigation/views/stack/topbar/titlebar/TitleBarReactView.kt
lib/android/app/src/reactNative63/java/com/reactnativenavigation/views/stack/topbar/titlebar/TitleBarReactView.kt
lib/android/app/src/reactNative68/java/com/reactnativenavigation/views/stack/topbar/titlebar/TitleBarReactView.kt
lib/android/app/src/reactNative71/java/com/reactnativenavigation/views/stack/topbar/titlebar/TitleBarReactView.kt

Remove the hack and let ReactRootView measure itself when view is centered

Fix title component measurement on Android

---

lib/ios/RNNBridgeModule.m

Solves
```
Main Thread Checker: UI API called on a background thread: -[UITabBarController tabBar]
```
warnings

Use getConstants on main thread

---

lib/Mock/Components/ComponentScreen.tsx

I have made some changes it order to make the bottom tabs more correct when rendering visually (by using react-native-web).
before: 
after:

Make bottom tabs more visually correct

---

lib/android/app/src/main/java/com/reactnativenavigation/utils/UiUtils.java

This fixes a crash happening in the Wix app, look like there's a race condition where the activity is destroyed and navigator.onHostPause() gets called too late and should always be called at front of queue. Most of times this shouldn't be delayed as it is called on the main thread.
This is the crash:
```
Location
NavigationModule.java line 213 in com.reactnativenavigation.react.NavigationModule.navigator
Exception
java.lang.NullPointerException
Message
Attempt to invoke virtual method 'com.reactnativenavigation.viewcontrollers.navigator.Navigator com.reactnativenavigation.NavigationActivity.getNavigator()' on a null object reference
```
Closes #7769

Fix runOnMainThread to run at front of queue

---

lib/android/app/src/main/java/com/reactnativenavigation/react/JsDevReloadHandler.java

From react native [pr](https://github.com/facebook/react-native/pull/38256)
> Summary:
> Add RECEIVER_EXPORTED/RECEIVER_NOT_EXPORTED flag support to DevSupportManagerBase for Android 14 change. See
> https://developer.android.com/about/versions/14/behavior-changes-14#runtime-receivers-exported for details.
> 
> Without this fix, app crashes during launch because of :
> SecurityException: {package name here}: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts

Android 14 support

---

lib/src/interfaces/Options.ts

Android doesn't have `upsideDown` or `all` (but does have `default`), but then again iOS doesn't have the `sensor*` ones.

fix: update layout.orientation types to match iOS implementation

---

lib/android/app/src/main/java/com/reactnativenavigation/react/NavigationModule.java

This fixes a crash happening in the Wix app, look like there's a race condition where the activity is destroyed and navigator.onHostPause() gets called too late and should always be called at front of queue. Most of times this shouldn't be delayed as it is called on the main thread.
This is the crash:
```
Location
NavigationModule.java line 213 in com.reactnativenavigation.react.NavigationModule.navigator
Exception
java.lang.NullPointerException
Message
Attempt to invoke virtual method 'com.reactnativenavigation.viewcontrollers.navigator.Navigator com.reactnativenavigation.NavigationActivity.getNavigator()' on a null object reference
```

Fix onHostPause crash on Android

---

package.json
scripts/postinstall.js

add post-install patch to use boost.io's mirror due to installation errors from the original source
See https://github.com/boostorg/boost/issues/843

build(playground): patch boost podspec on post-install.

---

lib/ios/RNNTabBarItemCreator.m

For some reason, this change resolves the issue in the attached snapshots.
When `centered=YES`, setting the text alignment to `NSTextAlignmentCenter` ([see here](https://github.com/wix/react-native-navigation/blob/4b48f75ae5e3b319d6243362bbf77f769d50990e/lib/ios/RNNFontAttributesCreator.m#L44)) may incidentally cause the text layout engine to more effectively manage the available space. Doesn't seem like it affects anything in iPhones.
Overall, it seems like a bug in UIKit..
**Before:**
**After:**

fix(iOS): avoid cutting-off text on bottom bar buttons on iPad.

---

lib/android/app/src/main/java/com/reactnativenavigation/views/stack/topbar/titlebar/ButtonBar.kt

fixes #7832
After spending a fair amount of efforts trying to get a deep understanding the layout and view arrangement flow, i couldn't get to the very bottom of why the buttons menu transitively renders in a broken way, namely like this:
instead of:
Nevertheless, `clipChildren=false` over the action menu's root (i.e. the `ActionMenuView` class) - introduced [here](https://github.com/wix/react-native-navigation/pull/6918/files) seems to be causing the flicker, while removing it doesn't seem to be introducing any regressions.
While with `clipChildren=false` the layout is broken transitively, removing it doesn't make all-things-perfect. There is still a very noticeable flicker happening in each stack push/pop, which could probably be avoided. Read below for hints as to why that is.
_Update: …

Disable action-menu clipChildren=false

---

lib/ios/RNNReactView.mm

After migration to RN73,`RNNReactView` now extends from `RCTSurfaceHostingProxyRootView` and uses new `initWithBridge:` implementation (with Fabric) with `RCTFabricSurface` instance. In `initWithBridge:` method, we call `[super initWithSurface:surface sizeMeasureMode:sizeMeasureMode]`, but this method located in `RCTSurfaceHostingView` (parent for `RCTSurfaceHostingProxyRootView`)  and does not call `[surface start]` (unlike `RCTSurfaceHostingProxyRootView` `[super initWithSurface:surface]` that calls it, but it does not allow us to specify `RCTSurfaceSizeMeasureMode`), so all we need to do is to call `[surface start]` after `RNNReactView` init.
Also I created Expo plugin for this wonderful library, it supports SDK 49 and SDK 50 (RN 72 & 73): [RNN Expo …

[iOS] Fabric renderer fix

---

lib/Mock/Components/LayoutComponent.tsx
lib/src/adapters/NativeEventsReceiver.mock.ts
lib/src/events/EventsRegistry.test.tsx
package.json

adding {cause} should make it easier to understand where the error comes from.

fix: make sure we don't swallow errors inside the mock

---

lib/ios/RNNBottomTabsController.m
playground/ios/NavigationTests/RNNCommandsHandlerTest.m

Fixes #7921 by setting _currentTabIndex in the RNNBottomTabsController before initialization happens.
>  _currentTabIndex needs to be set before the super() is called, since - [RNNBottomTabsController selectedViewController] will be called during initialization and which depends on _currentTabIndex. If not set, an initial render of the tab content with index 0 will occur when tabsAttachMode is set to "onSwitchToTab".

fix(ios): ensure correct initial tab is rendered when onSwitchToTab is set

---

package.json

Should solve this Gradle issue during the build:
```
* What went wrong:
--
  | Execution failed for task ':react-native-community_blur:extractReleaseAnnotations'.
  | > Error while evaluating property 'hasAndroidAnnotations' of task ':react-native-community_blur:extractReleaseAnnotations'.
  | > Could not resolve all artifacts for configuration ':react-native-community_blur:releaseCompileClasspath'.
  | > Failed to transform blurview-1.6.3.aar (com.eightbitlab:blurview:1.6.3) to match attributes {artifactType=android-classes-jar, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-api}.
  | > Could not find blurview-1.6.3.jar (com.eightbitlab:blurview:1.6.3).
  | Searched in the following locations:
  | …
```

chore: upgrade react-native-blur version.

---

lib/ios/RNNBottomTabsController.m
playground/ios/NavigationTests/RNNCommandsHandlerTest.m

This fixes the issue mentioned on #7921, #7922 and #7924.
This prevents the bug of loading of the tab from index `0` immediately after calling the `super` init regardless of the custom initial rendered tab. More specifically, the original issue was the method `setSelectedIndex` was called immediately when calling to the `super` initializer with a `0` value regardless of the initial `currentTabIndex` value.
After this fix, changing the `selectedIndex` with the non-initial value from `options` will not have any effect before the setup has finished.

fix(ios): avoid setting selected-index before setup has finished.

---

lib/android/app/src/main/java/com/reactnativenavigation/FeatureToggles.kt
lib/android/app/src/main/java/com/reactnativenavigation/NavigationActivity.java
lib/android/app/src/main/java/com/reactnativenavigation/utils/ColorUtils.java
lib/android/app/src/main/java/com/reactnativenavigation/utils/SystemUiUtils.kt
lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/bottomtabs/BottomTabPresenter.java
lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/bottomtabs/BottomTabsController.java
lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/component/ComponentPresenter.java
lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/component/ComponentViewController.java
lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/stack/StackController.java
lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/stack/StackPresenter.java
lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/stack/statusbar/StatusBarController.kt
lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/stack/statusbar/StatusBarPresenter.kt
lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/stack/topbar/TopBarController.kt
lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/statusbar/StatusBarPresenter.kt
lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/viewcontroller/Presenter.java
lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/viewcontroller/StatusBarColorAnimator.kt
lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/viewcontroller/ViewController.java
lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/viewcontroller/ViewControllerVisibilityInfo.kt
lib/android/app/src/test/java/com/reactnativenavigation/BaseTest.kt
lib/android/app/src/test/java/com/reactnativenavigation/mocks/TitleBarReactViewCreatorMock.java
lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/bottomtabs/BottomTabsControllerTest.kt
lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/stack/TopBarControllerTest.kt
playground/android/app/src/main/java/com/reactnativenavigation/playground/MainApplication.java
playground/src/screens/NavigationScreen.tsx

Resolves #7956; Extends the work in #7969.

 Apply color animations on tab-switching (Android-only)

---

lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/bottomtabs/BottomTabsController.java

Fix bottom-tab positioning for apps targeting SDK35 (i.e. with edge-to-edge layout by default), which otherwise does not account for the bottom window inset and is therefore laid out under the navigation bar (e.g. in the 3-button mode).
Before:
After:
(in edge-to-edge the 3-btn nav bar is [80% transparent by default])
**Note: This does not in any way introduce complete support for SDK35. There are still numerous adjustments to be made (see #7978).**

Fix SDK35 Bottom-tab positioning

---

e2e/StaticLifecycleEvents.test.js
lib/ios/TopBarTitlePresenter.mm

The problem was that when setting a titleView of a navigationItem the normal life cycle flow of a view will not be called so the RNNReactView componentWillAppear and DidAppear need to be implicitly called. 
This was somehow removed from the TopBarTitlePresenter.mm unit but is present on the current Master branch's file.
This PR restores those two lines and also actives the Unit test for that module.

iOS: RN 77 no lifecycle events for Top Bar Title component

---

e2e/SideMenu.test.js
lib/Mock/Components/ComponentScreen.tsx
lib/Mock/Components/LayoutComponent.tsx
lib/Mock/Components/SideMenu.tsx
lib/Mock/Layouts/BottomTabsNode.ts
lib/Mock/Layouts/LayoutNodeFactory.ts
lib/Mock/Layouts/ParentNode.ts
lib/Mock/Layouts/SideMenu.ts
lib/Mock/Stores/LayoutStore.ts
lib/Mock/actions/layoutActions.ts
lib/Mock/mocks/NativeCommandsSender.tsx

Fixes #7981 -- introduces fundamental support for side-menus in mocked tests
Caveats:
- Multiple side-menus (i.e. across several tabs) are not supported yet
--
@yedidyak fyi

Mocked side-menus - support

---

ReactNativeNavigation.podspec

During `pod install` react-native-navigation does not correctly detect if a project has an obj-c or swift AppDelegate. Resulting in the a crash saying `ReactNativeNavigationModule not found`
https://github.com/wix/react-native-navigation/issues/8049
This should handle both normal and monorepo projects

Fix swift delegate detection

---

lib/ios/RNNAppDelegate.mm

We were missing this one liner in our RNNAppDelegate
`[RCTComponentViewFactory currentComponentViewFactory].thirdPartyFabricComponentsProvider = self;`
which would assign a delegate that would take care of calling the auto-generated RCTThirdPartyComponentsProvider.mm to register 3rd party components.

RNDatePicker not registering - including any 3rd party component - #8069

---

lib/ios/RNNAppDelegate.mm

The RNNAppDelegate was implementing the RCTTurboModuleManagerDelegate with having the getTurboModule:jsInvoker returning nullptr.
Because the RNNAppDelegate's RCTTurboModuleManagerDelegate implementation was almost idenitcal to RCTAppDelegate's (except for the nullptr return) the RNNAppDelegate implementation of it is not needed so was removed.

Fix Property setImmediate doesn't exist issue

---

lib/android/app/src/main/java/com/reactnativenavigation/utils/SystemUiUtils.kt
lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/statusbar/StatusBarPresenter.kt
lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/viewcontroller/ViewController.java

This is a replay of #8095 over the 8.x.x version

Fix crash due to java2kotlin refactor (#8095)

---

lib/android/app/src/androidTest/java/com/reactnativenavigation/TestUtils.java
lib/android/app/src/main/java/com/reactnativenavigation/options/LayoutFactory.java
lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/stack/StackController.java
lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/stack/StackPresenter.java
lib/android/app/src/test/java/com/reactnativenavigation/TestUtils.java
lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/OptionsApplyingTest.java
lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/stack/StackControllerTest.kt
lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/stack/StackPresenterTest.kt

This is a replay of #8098 over the 8.x.x version

Fix crash coming from top-bar color animation (#8098)

---

lib/android/app/src/main/java/com/reactnativenavigation/react/NavigationTurboModule.kt

Crash in NavigationTurboModule.kt.
Fixed null safety

Fixed crash in Android 
