wix/react-native-navigation

example/android/app/src/main/java/com/example/MainActivity.java

Fix Android example

---

android/app/src/main/res/layout/bottom_tab_activity.xml
android/app/src/main/res/layout/single_screen_activity.xml

As suggested in issue #109, allow the menu width to adjust to the content width.

[Android] Allow menu width to adjust to content

---

src/Navigation.js

since "allProps" was not being updated, existing props were not receiving prop updates as well

Fix for register components not updating props

---

src/deprecated/platformSpecificDeprecated.android.js

Remove debugger

---

example/src/app.js
example/src/screens/StyledScreen.js
src/deprecated/platformSpecificDeprecated.ios.js

Navigation bar now supports in title, subtitle, title image

add subtitle support to navigation bar

---

android/app/build.gradle

Added missing $

---

src/deprecated/platformSpecificDeprecated.ios.js

Fix immutable error after updating rn@0.35

---

android/app/src/main/java/com/reactnativenavigation/controllers/NavigationActivity.java

Fix npe when appStyle is undefined

---

android/app/src/main/java/com/reactnativenavigation/bridge/BundleConverter.java
android/app/src/main/java/com/reactnativenavigation/params/StyleParams.java
android/app/src/main/java/com/reactnativenavigation/params/parsers/ContextualMenuButtonParamsParser.java
android/app/src/main/java/com/reactnativenavigation/params/parsers/FabActionParamsParser.java
android/app/src/main/java/com/reactnativenavigation/params/parsers/Parser.java
android/app/src/main/java/com/reactnativenavigation/params/parsers/StyleParamsParser.java
android/app/src/main/java/com/reactnativenavigation/views/ContentView.java
src/deprecated/platformSpecificDeprecated.android.js

Add Support for all common color formats on Android

---

example/src/screens/FirstTabScreen.js

example "show single screen app" now will show the side menu (drawer)

Fix example

---

android/app/src/main/AndroidManifest.xml
android/app/src/main/java/com/reactnativenavigation/bridge/NavigationReactModule.java
android/app/src/main/java/com/reactnativenavigation/controllers/LandscapeNavigationActivity.java
android/app/src/main/java/com/reactnativenavigation/controllers/NavigationCommandsHandler.java

Implemented this for a tablet layout, thoughts?

Landscape only

---

android/app/src/main/java/com/reactnativenavigation/screens/CollapsingSingleScreen.java

Fix TitleBar hide on scroll when screen is drawn under TopBar

TitleBar hide on scroll

---

android/app/src/main/java/com/reactnativenavigation/params/StyleParams.java
android/app/src/main/java/com/reactnativenavigation/params/parsers/StyleParamsParser.java
android/app/src/main/java/com/reactnativenavigation/views/TopBar.java
src/deprecated/platformSpecificDeprecated.android.js

Add topBarElevationShadowEnabled style property

---

ios/RCCTabBarController.m

Fixed tab bar layout animation. When first time each tab selected and the layout animation weirdly and defaultly happend.

Bugfix - layout animation on tabBar

---

android/app/src/main/java/com/reactnativenavigation/bridge/NavigationReactModule.java
android/app/src/main/java/com/reactnativenavigation/controllers/NavigationActivity.java
android/app/src/main/java/com/reactnativenavigation/controllers/NavigationCommandsHandler.java
android/app/src/main/java/com/reactnativenavigation/events/FabSetEvent.java
android/app/src/main/java/com/reactnativenavigation/layouts/BottomTabsLayout.java
android/app/src/main/java/com/reactnativenavigation/layouts/Layout.java
android/app/src/main/java/com/reactnativenavigation/layouts/SingleScreenLayout.java
android/app/src/main/java/com/reactnativenavigation/params/FabParams.java
android/app/src/main/java/com/reactnativenavigation/screens/Screen.java
android/app/src/main/java/com/reactnativenavigation/screens/ScreenStack.java
android/app/src/main/java/com/reactnativenavigation/views/FloatingActionButtonCoordinator.java
android/app/src/main/java/com/reactnativenavigation/views/SnackbarAndFabContainer.java
src/deprecated/platformSpecificDeprecated.android.js
src/platformSpecific.android.js

call setButtons with empty fab object to remove it

Remove Fab when when calling setButtons

---

android/app/src/main/java/com/reactnativenavigation/layouts/BottomTabsLayout.java

The event is sent to the top most screen displayed in the current screenStack.

Send bottomTabSelected event

---

android/app/src/main/java/com/reactnativenavigation/params/parsers/ContextualMenuButtonParamsParser.java
src/deprecated/platformSpecificDeprecated.android.js

* Pass showAsAction property to native. It was left out by mistake
* Support textual icons in contextual menu

Minor contextualMenu fixes

---

ios/RCCTabBarController.h

not really needed since RCCTabBarController is already delegate to him self (inheritss from UITabBarController). adding this for the record.

add tabBarDelegate

---

android/app/src/main/java/com/reactnativenavigation/layouts/BottomTabsLayout.java
android/app/src/main/java/com/reactnativenavigation/layouts/SingleScreenLayout.java

Just an effort to get around this: https://github.com/wix/react-native-navigation/issues/616

Sends a nav event whenever the sideMenu button is clicked. (Android)

---

src/deprecated/platformSpecificDeprecated.ios.js

As discussed in https://github.com/wix/react-native-navigation/pull/644

Fixing props in showInAppNotification

---

ios/RCCTabBarController.m

Make tab bar selected event only once (if tab index actually changed)

Fix tab bar selected event

---

android/app/src/main/java/com/reactnativenavigation/params/BaseScreenParams.java
android/app/src/main/java/com/reactnativenavigation/params/ScreenParams.java
android/app/src/main/java/com/reactnativenavigation/params/StyleParams.java
android/app/src/main/java/com/reactnativenavigation/params/parsers/ScreenParamsParser.java
android/app/src/main/java/com/reactnativenavigation/params/parsers/StyleParamsParser.java
android/app/src/main/java/com/reactnativenavigation/params/parsers/TabIconParser.java
android/app/src/main/java/com/reactnativenavigation/params/parsers/TopTabParamsParser.java
android/app/src/main/java/com/reactnativenavigation/screens/ViewPagerScreen.java
android/app/src/main/java/com/reactnativenavigation/views/TopBar.java
android/app/src/main/java/com/reactnativenavigation/views/TopTabs.java
android/app/src/main/java/com/reactnativenavigation/views/utils/TopTabsIconColorHelper.java
src/deprecated/platformSpecificDeprecated.android.js

This commit adds support for icons in TopTabs.
It’s possible to have icons with text, or only icons.
Use `topTabIconColor` and `selectedTopTabIconColor` to color the icons

TopTabs icons

---

android/app/src/main/java/com/reactnativenavigation/animation/PeekingAnimator.java
android/app/src/main/java/com/reactnativenavigation/bridge/NavigationReactModule.java
android/app/src/main/java/com/reactnativenavigation/controllers/NavigationActivity.java
android/app/src/main/java/com/reactnativenavigation/controllers/NavigationCommandsHandler.java
android/app/src/main/java/com/reactnativenavigation/layouts/BottomTabsLayout.java
android/app/src/main/java/com/reactnativenavigation/layouts/Layout.java
android/app/src/main/java/com/reactnativenavigation/layouts/SingleScreenLayout.java
android/app/src/main/java/com/reactnativenavigation/views/slidingOverlay/SlidingOverlay.java
android/app/src/main/java/com/reactnativenavigation/views/slidingOverlay/SlidingOverlaysQueue.java
example/src/screens/InAppNotification.js
src/deprecated/platformSpecificDeprecated.android.js
src/platformSpecific.android.js

Add .dismissInAppNotification on android.
- Separate hide and show animations.
- Implement a little bit of throttling around successive calls to .showInAppNotification

dismissInAppNotification support on android.

---

android/app/src/main/java/com/reactnativenavigation/animation/PeekingAnimator.java
android/app/src/main/java/com/reactnativenavigation/params/SlidingOverlayParams.java
android/app/src/main/java/com/reactnativenavigation/params/parsers/SlidingOverlayParamsParser.java
android/app/src/main/java/com/reactnativenavigation/views/slidingOverlay/SlidingOverlay.java
example/src/screens/SideMenu.js

Allows position parameter to make the notification appear on bottom of Screen. Defaults to `top`.
```javascript
Navigator.showInAppNotification({
screen: "example.InAppNotification",
position: "bottom",
});
```

Add showInAppNotification position param support for Android

---

android/app/src/main/java/com/reactnativenavigation/params/SlidingOverlayParams.java
android/app/src/main/java/com/reactnativenavigation/params/parsers/SlidingOverlayParamsParser.java
android/app/src/main/java/com/reactnativenavigation/views/slidingOverlay/SlidingOverlay.java
android/app/src/main/java/com/reactnativenavigation/views/slidingOverlay/SlidingOverlaysQueue.java
example/src/screens/SideMenu.js
src/deprecated/platformSpecificDeprecated.android.js
src/deprecated/platformSpecificDeprecated.ios.js

[Android] Control the duration of the auto dismiss timer with `autoDismissTimerSec` like on iOS
[Android] Default `autoDismissTimerSec` to 5 like on iOS
[All] Add `autoDismiss` param to enable/disable auto dismiss behaviour. Defaults to `true`

Notification auto dismiss timer

---

android/app/src/main/java/com/reactnativenavigation/params/StyleParams.java
android/app/src/main/java/com/reactnativenavigation/params/parsers/StyleParamsParser.java
android/app/src/main/java/com/reactnativenavigation/views/TopBar.java
android/app/src/main/java/com/reactnativenavigation/views/TopTabs.java
src/deprecated/platformSpecificDeprecated.android.js

Small changes to enable scrollable top tabs in android

[android] Add option for scrollable top tabs

---

android/app/src/main/java/com/reactnativenavigation/params/SnackbarParams.java
android/app/src/main/java/com/reactnativenavigation/params/StyleParams.java
android/app/src/main/java/com/reactnativenavigation/params/parsers/Parser.java
android/app/src/main/java/com/reactnativenavigation/params/parsers/SnackbarParamsParser.java
android/app/src/main/java/com/reactnativenavigation/views/FloatingActionButtonCoordinator.java
android/app/src/main/java/com/reactnativenavigation/views/Snakbar.java
src/deprecated/platformSpecificDeprecated.android.js

Implement backgroundColor and textColor style params

Additional snackbar style params

---

android/app/src/main/java/com/reactnativenavigation/controllers/ActivityCallbacks.java
android/app/src/main/java/com/reactnativenavigation/controllers/NavigationActivity.java

I need it to integrate https://github.com/yamill/react-native-orientation.

Expose onConfigurationChanged in ActivityCallbacks.

---

android/app/src/main/java/com/reactnativenavigation/screens/FragmentScreen.java

Crash description here
http://stackoverflow.com/questions/7575921/illegalstateexception-can-not-perform-this-action-after-onsaveinstancestate-wit

Fix possible IllegalStateException crash 

---

android/app/src/main/java/com/reactnativenavigation/controllers/NavigationActivity.java
android/app/src/main/java/com/reactnativenavigation/react/JsDevReloadHandler.java
android/app/src/main/java/com/reactnativenavigation/react/NavigationReactGateway.java
android/app/src/main/java/com/reactnativenavigation/react/ReactGateway.java

`adb shell am broadcast -a react.native.RELOAD` from terminal to reload the app

Enable reloading from cmd

---

android/app/src/main/java/com/reactnativenavigation/params/parsers/CollapsingTopBarParamsParser.java
android/app/src/main/java/com/reactnativenavigation/views/TitleBar.java
android/app/src/main/java/com/reactnativenavigation/views/TitleBarBackground.java
android/app/src/main/java/com/reactnativenavigation/views/TranslucentDrawable.java
android/app/src/main/java/com/reactnativenavigation/views/TranslucentTitleBarBackground.java
android/app/src/main/java/com/reactnativenavigation/views/collapsingToolbar/CollapsingTitleBar.java

* Change default scrim color to none
* Fade out translucent when collapsingToolBarCollapsedColor is not defined

Fadeout translucent drawable when collapsing

---

ios/RCCLightBox.m
ios/RCCNotification.m
ios/RCCViewController.m

Switch to RCTJavaScriptWillStartLoadingNotification

---

android/app/src/main/java/com/reactnativenavigation/screens/Screen.java

Set LeftButton color from screen

---

android/app/src/main/java/com/reactnativenavigation/bridge/NavigationReactModule.java
android/app/src/main/java/com/reactnativenavigation/controllers/NavigationActivity.java
android/app/src/main/java/com/reactnativenavigation/controllers/NavigationCommandsHandler.java
android/app/src/main/java/com/reactnativenavigation/events/OrientationChangedEvent.java
android/app/src/main/java/com/reactnativenavigation/utils/Orientation.java

Refactor orientation logic to separate class

---

ios/RCCDrawerController/RCCDrawerController.m
ios/RCCDrawerController/RCCTheSideBarManagerViewController.m
ios/RCCNavigationController.m
ios/RCCTabBarController.m
ios/ReactNativeNavigation.xcodeproj/project.pbxproj
ios/UIViewController+Rotation.h
ios/UIViewController+Rotation.m
src/deprecated/platformSpecificDeprecated.ios.js

support orientation change in iOS.
Usage:
* When calling `startSingleScreenApp` or `startTabBasedApp`, pass `appStyle` object with the requested orientation:
```js
Navigation.startTabBasedApp({
tabs: createTabs(),
appStyle: {
orientation: 'portrait' // Available values: portrait, landscape, auto
}
});
```
* When showing a modal, in `navigatorStyle` passed in `showModal`:
```js
this.props.navigator.showModal({
title: "Modal",
screen: "example.ModalScreen",
navigatorStyle: {
orientation: 'landscape'
}
});
```
Any other use cases that aren't mention above will be ignored.

iOS orientation

---

android/app/src/main/java/com/reactnativenavigation/bridge/EventEmitter.java
android/app/src/main/java/com/reactnativenavigation/views/Snakbar.java
src/Navigation.js
src/deprecated/platformSpecificDeprecated.android.js

When snackbar cta is clicked - event is dispatched with the specified eventId

Snackback can be displayed statically from Navigation

---

android/app/src/main/java/com/reactnativenavigation/controllers/Modal.java
android/app/src/main/java/com/reactnativenavigation/controllers/ModalController.java
android/app/src/main/java/com/reactnativenavigation/controllers/NavigationActivity.java

Solves issue reported  in https://github.com/wix/react-native-navigation/issues/672#issuecomment-287020822

Show in app notifications on modals

---

android/app/src/main/java/com/reactnativenavigation/react/NavigationReactGateway.java
android/app/src/main/java/com/reactnativenavigation/screens/CollapsingSingleScreen.java

Add ContentView after TopBar

---

ios/RCCNavigationController.m
ios/RCCViewController.m

This new style will NOT pass between push screens.

iOS - add disabledBackGesture

---

ios/RCCViewController.m

Bugfix - Swiping / pop gesture on root Screen breaks navigation push / touches

---

ios/Helpers/RCCTitleViewHelper.m

Fixes https://github.com/wix/react-native-navigation/issues/113

[iOS] Setting title through navigation item doesn't change the tab bar label

---

.ghp/openSourceIsAwesome.json

Adding the wix mobile open source website config file

Opensourceisawesome

---

android/app/src/main/java/com/reactnativenavigation/views/slidingOverlay/SlidingOverlaysQueue.java

I have experienced this crash in my application and I have added a null check to avoid it.

Fix npe in sliding overlay

---

android/app/src/main/java/com/reactnativenavigation/layouts/BottomTabsLayout.java
ios/RCCTabBarController.m

Added an additional navigation event, 'bottomTabPressed', for the press of an already selected tab.

Added 'bottomTabPressed' navigation event

---

android/app/src/main/java/com/reactnativenavigation/params/StyleParams.java
android/app/src/main/java/com/reactnativenavigation/params/parsers/StyleParamsParser.java
android/app/src/main/java/com/reactnativenavigation/views/BottomTabs.java
docs/styling-the-tab-bar.md
src/deprecated/platformSpecificDeprecated.android.js

in appStyle add attribute
``` javascript
tabFontFamily: 'Avenir-Medium.ttf' // for asset file
```
or
``` javascript
tabFontFamily: 'sans-serif' // for existing fonts in system
```

Add font family support on bottom tabs

---

README.md

I saw some comments online in discussions about RNN that readers didn't understand what RNN was about. This change makes it clearer and removes the technical note about react-native-controllers that isn't really interesting to most people.
P.S. _lede_ is a [word](https://www.merriam-webster.com/dictionary/lede), not a spelling mistake. In case you were wondering.

Easier to understand lede

---

android/app/src/main/java/com/reactnativenavigation/layouts/BottomTabsLayout.java
ios/RCCTabBarController.m

This PR adds bottom tab selected event, useful mostly for bi purposes.
```js
this.eventSubscription = emitter.addListener('bottomTabSelected', (event) => {
// event.selectedTabIndex
// event.unselectedTabIndex
});
```

Bottom tab selected event

---

src/deprecated/platformSpecificDeprecated.android.js

Parse lightbox backgroundColor from style

---

docs/installation-android.md

- compileSdkVersion 25
- buildToolsVersion "25.0.1"

Modify compileSdkVersion, buildToolsVersion

---

android/app/src/main/java/com/reactnativenavigation/views/collapsingToolbar/CollapsingViewPagerContentViewMeasurer.java

Fix BottomTabs check in CollapsingViewPagerContentViewMeasurer

---

docs/_sidebar.md

Corrected typo in the side menu

Typo Fix In Side menu

---

android/app/src/main/java/com/reactnativenavigation/bridge/NavigationReactModule.java
android/app/src/main/java/com/reactnativenavigation/controllers/Modal.java
android/app/src/main/java/com/reactnativenavigation/controllers/ModalController.java
android/app/src/main/java/com/reactnativenavigation/controllers/NavigationActivity.java
android/app/src/main/java/com/reactnativenavigation/controllers/NavigationCommandsHandler.java
android/app/src/main/java/com/reactnativenavigation/layouts/BottomTabsLayout.java
android/app/src/main/java/com/reactnativenavigation/layouts/Layout.java
android/app/src/main/java/com/reactnativenavigation/layouts/SingleScreenLayout.java
android/app/src/main/java/com/reactnativenavigation/screens/Screen.java
android/app/src/main/java/com/reactnativenavigation/screens/ScreenStack.java
android/app/src/main/java/com/reactnativenavigation/screens/ViewPagerScreen.java
src/Screen.js
src/deprecated/platformSpecificDeprecated.android.js
src/platformSpecific.android.js

Usage is identical to switchToTab, closes #842

Implement switchToTopTab method

---

docs/deep-links.md

Documentation of this change #1128

deep-links payload on docs

---

docs/installation-android.md

Docs weren't very clear on how exactly to return additional packages, i.e., as a <ReactPackages> list [Line 65]. 
Also changed MyApplication to MainApplication on line 54 (if that is a default and hasn't been changed by the developer).

Edited how to return additional packages

---

android/app/src/main/java/com/reactnativenavigation/controllers/Modal.java

Send modal lifecycle events only if modal is not destroyed

---

android/app/src/main/java/com/reactnativenavigation/views/TitleBar.java

Set leftButton color when calling setStyle

---

android/app/src/main/java/com/reactnativenavigation/params/TitleBarLeftButtonParams.java
android/app/src/main/java/com/reactnativenavigation/views/LeftButton.java
android/app/src/main/java/com/reactnativenavigation/views/TitleBar.java

Support setting custom left button dynamically [Android]

---

android/app/src/main/java/com/reactnativenavigation/controllers/NavigationActivity.java

Closes out #1144 
Presenter View triggered with willDisappear & didDisappear before showModal
Presenter View triggered with willDisappear & didDisappear after dismissModal

Android modal life cycle screen events added, Fixes #1144

---

android/app/src/main/java/com/reactnativenavigation/views/LeftButton.java
android/app/src/main/java/com/reactnativenavigation/views/TitleBar.java

* navBarButtonColor was not applied to custom initial left button
* Dynamic custom button didn’t work
* Setting default icon (like menu or back button) after a custom icon was used didn’t work

Custom left button fixes

---

docs/screen-api.md

This is readme update of this PR https://github.com/wix/react-native-navigation/pull/1133

add setTabButton instructions

---

android/app/src/main/java/com/reactnativenavigation/screens/CollapsingSingleScreen.java
android/app/src/main/java/com/reactnativenavigation/screens/CollapsingViewPagerScreen.java
android/app/src/main/java/com/reactnativenavigation/views/CollapsingContentView.java
android/app/src/main/java/com/reactnativenavigation/views/collapsingToolbar/CollapseAmount.java
android/app/src/main/java/com/reactnativenavigation/views/collapsingToolbar/CollapseCalculator.java
android/app/src/main/java/com/reactnativenavigation/views/collapsingToolbar/CollapsingTopBar.java
android/app/src/main/java/com/reactnativenavigation/views/collapsingToolbar/CollapsingTopBarReactHeader.java
android/app/src/main/java/com/reactnativenavigation/views/collapsingToolbar/CollapsingView.java
android/app/src/main/java/com/reactnativenavigation/views/collapsingToolbar/CollapsingViewPager.java
android/app/src/main/java/com/reactnativenavigation/views/collapsingToolbar/ViewCollapser.java
android/app/src/main/java/com/reactnativenavigation/views/collapsingToolbar/behaviours/CollapseTopBarBehaviour.java

Reverts wix/react-native-navigation#1213
Still needs further optimizations, perhaps it should be opt in as well.

Revert "Fling collapsing react view screens"

---

android/app/src/main/java/com/reactnativenavigation/screens/CollapsingSingleScreen.java
android/app/src/main/java/com/reactnativenavigation/screens/CollapsingViewPagerScreen.java
android/app/src/main/java/com/reactnativenavigation/views/CollapsingContentView.java
android/app/src/main/java/com/reactnativenavigation/views/collapsingToolbar/CollapseAmount.java
android/app/src/main/java/com/reactnativenavigation/views/collapsingToolbar/CollapseCalculator.java
android/app/src/main/java/com/reactnativenavigation/views/collapsingToolbar/CollapsingTopBar.java
android/app/src/main/java/com/reactnativenavigation/views/collapsingToolbar/CollapsingTopBarReactHeader.java
android/app/src/main/java/com/reactnativenavigation/views/collapsingToolbar/CollapsingView.java
android/app/src/main/java/com/reactnativenavigation/views/collapsingToolbar/CollapsingViewPager.java
android/app/src/main/java/com/reactnativenavigation/views/collapsingToolbar/ViewCollapser.java
android/app/src/main/java/com/reactnativenavigation/views/collapsingToolbar/behaviours/CollapseTopBarBehaviour.java

Cherrypick 53a93d6e4c21e57576eb10c80c8925d54b292ea6 into master

Fling collapsing react header

---

docs/installation-android.md

Forth step of Android Installation guide is about how to update MainActivity.java but sample code is for MainApplication.java

Fix sample code for MainActivity.java in Android Installation guide

---

android/app/src/main/java/com/reactnativenavigation/controllers/Modal.java
android/app/src/main/java/com/reactnativenavigation/controllers/NavigationActivity.java

Orientation was reverted to the app orientation each time modal was dismissed.
fixes #1229 closes #1231

Fix multiple modal orientation issue

---

android/app/build.gradle

android AppCompat & Design libs version Fixing #1227

---

android/app/src/main/java/com/reactnativenavigation/screens/Screen.java
example/src/screens/Actions.js

Also listen to contextualMenuDismissed event in Actions screen

Fix status bar color not changing after dismissing contextual menu

---

android/app/src/main/java/com/reactnativenavigation/views/collapsingToolbar/CollapsingTopBar.java
android/app/src/main/java/com/reactnativenavigation/views/collapsingToolbar/ViewCollapser.java

Handle fling in collapsing header with image view

---

docs/styling-the-tab-bar.md
ios/RCCTabBarController.m

Added different tabbar item label colors (iOS only)

[iOS] Different Tabbar item text colors

---

v1tov2diff.md

Alpha version of docs, feature parity and 'why v2'

docs, feature parity, about - work in progress

---

lib/android/app/src/main/java/com/reactnativenavigation/layout/ReactRootViewController.java
lib/ios/RNNReactRootViewCreator.m
lib/src/containers/ContainerRegistry.test.js
lib/src/containers/ContainerWrapper.js
lib/src/containers/ContainerWrapper.test.js
lib/src/containers/Lifecycle.js
lib/src/containers/Lifecycle.test.js
lib/src/containers/Store.js
lib/src/containers/Store.test.js
lib/src/events/PrivateEventsListener.test.js
playground/src/containers/LifecycleScreen.js
playground/src/containers/ModalScreen.js
playground/src/containers/OptionsScreen.js
playground/src/containers/PushedScreen.js
playground/src/containers/TextScreen.js
playground/src/containers/WelcomeScreen.js

Containers now receive their container id under this.props.containerId instead of this.props.id. 
Note: js tests not passing yet

changed this.props.id to this.props.containerId

---

android/app/src/main/java/com/reactnativenavigation/animation/VisibilityAnimator.java
android/app/src/main/java/com/reactnativenavigation/views/TitleBar.java

Also cleaned up VisibilityAnimator.

Fix title bar not displayed if it was initially hidden

---

android/app/src/main/java/com/reactnativenavigation/animation/VisibilityAnimator.java
android/app/src/main/java/com/reactnativenavigation/views/TitleBar.java

Reverts wix/react-native-navigation#1341

Revert "Fix title bar not displayed if it was initially hidden"

---

android/app/src/main/java/com/reactnativenavigation/views/BottomTabs.java
android/app/src/main/java/com/reactnativenavigation/views/utils/Constants.java

Use hardcoded BottomTabs height in visibility animator constructor

---

ios/RCCDrawerController/MMDrawerController/MMDrawerController.m
ios/RCCDrawerController/RCCDrawerController.m

Resolves a couple of typos in #1347 and improves MMDrawerController handling of nil UIViewControllers.

Fixes for dynamically controlling iOS drawer status

---

android/app/src/main/java/com/reactnativenavigation/react/NavigationReactGateway.java

Can be null if returning from another app and our activity wad destroyed in background

Null check ReactContext in onActivityResult

---

ios/RCCViewController.m

added https://github.com/wix/react-native-navigation/commit/03d380f8a9d2fba5d4baf6815201fcebdcfa18c9 back and also applied this fix https://github.com/wix/react-native-navigation/issues/428#issuecomment-278268928 on top of it

[iOS] Enable back swipe gesture when a navBar is hidden. Resolves this issue: https://github.com/wix/react-native-navigation/issues/930

---

docs/styling-the-navigator.md

added a missing comma in the 'style object format' so to help users who copy/paste this code block

added a missing comma

---

android/app/src/main/java/com/reactnativenavigation/params/LightBoxParams.java
android/app/src/main/java/com/reactnativenavigation/params/parsers/LightBoxParamsParser.java
android/app/src/main/java/com/reactnativenavigation/views/LightBox.java
docs/top-level-api.md
example/src/app.js
ios/RCCLightBox.m
src/deprecated/platformSpecificDeprecated.android.js

Added param tapBackgroundToDismiss to LightBox screens to allow tapping on background views to dismiss the LightBox screen

Added tapBackgroundToDismiss to LightBox screens

---

android/app/src/main/java/com/reactnativenavigation/layouts/BottomTabsLayout.java

[http://imgur.com/a/JTvwm](http://imgur.com/a/JTvwm)

Fixed TabBar from not adopting screen background color

---

ios/RCCLightBox.m

| Before | After |
| ----- | ----- |
|![lightbox-actionsheetios](https://user-images.githubusercontent.com/1051453/27753021-d7c54642-5db1-11e7-9428-434bea455d84.gif) | ![lightbox-actionsheetios-fixed](https://user-images.githubusercontent.com/1051453/27753026-db508704-5db1-11e7-8111-8087737dda32.gif) |
This fixes issues with other React Native views which rely on the view controller hierarchy.

[iOS] Prefer use of view controller hierarchy to display lightbox

---

android/app/src/main/java/com/reactnativenavigation/screens/ScreenAnimator.java
android/app/src/main/java/com/reactnativenavigation/utils/ViewUtils.java
android/app/src/main/java/com/reactnativenavigation/views/TitleBar.java

Screen calculations were not using the entire display for size dimensions vs. the maximum window size

Fixed screen size calculations when in multi-window view

---

CONTRIBUTING.md
README.md

Some updates to the docs, more explanation in the contributing guidelines. To be continued...

Contributing guidelines & docs

---

lib/ios/RNNRootViewController.m
lib/ios/ReactNativeNavigationTests/RNNControllerFactoryTest.m

@bogobogo I started with adding an integration test for the ios styles support, the subsequent styles we should test with unit tests to make sure they all work

statusBarHidden support for ios

---

ios/RCCManagerModule.m

fix iOS crash on showController

---

README.md

The documentation for the android installation of v2 was wrong.

DOCS: Fixed android installation

---

ios/RCCViewController.m

See https://github.com/wix/react-native-navigation/issues/1446#issuecomment-319858633

Fix crash with scrollViewDidEndDecelerating and RCTTextView

---

docs/top-level-api.md

To match the rest of the styling

Improved Deeplink documentation

---

docs/adding-buttons-to-the-navigator.md

This adds documentation about custom navigation buttons add in #1641

Add docs about using custom navigation buttons

---

README.md

just correcting screen event typo's "didDisppear" to "didDisappear"

typo fixes for README

---

android/app/src/main/java/com/reactnativenavigation/params/LightBoxParams.java
android/app/src/main/java/com/reactnativenavigation/params/parsers/LightBoxParamsParser.java
android/app/src/main/java/com/reactnativenavigation/views/LightBox.java
docs/screen-api.md

The window of LightBox is different with the activity，adjust soft input mode in onActivityCreated life cycle callback will have no effect

add adjust soft input optional config for Lightbox on android platform

---

ios/RCCManager.h
ios/RCCManager.m
ios/RCCManagerModule.m
ios/RCCViewController.m
ios/ReactNativeNavigation.xcodeproj/project.pbxproj
src/deprecated/controllers/index.js

Add appStyle support for iOS 🤖

Add appStyle support for iOS 🤖

---

ios/RCCNavigationController.m

Add the ability to choose if relevant styles properties will remember across push or not

keep style across push - iOS only

---

docs/styling-the-navigator.md
ios/RCCNavigationController.m
ios/RCCViewController.m

New Feature: adding disabledSimultaneousGesture flag to manage simultaneous gesture recognition for this ticket #1776.

New Feature: adding disabledSimultaneousGesture flag

---

docs/top-level-api.md
ios/RCCManager.m

in order to custom the default back button arrow image with provided image

[iOS] add backButtonImage to app style 

---

docs/top-level-api.md
ios/RCCNavigationController.m

in order to remove the back button title in the appStyle

add hideBackButtonTitle

---

docs/styling-the-navigator.md
ios/RCCNavigationController.m

in order to set navigation button disabled color

add disabledButtonColor

---

example/src/screens/Actions.js
ios/Helpers/RCCTitleViewHelper.m

now it will set the navigation subtitle color properly without any effect on the title

fix navBarSubtitleColor

---

android/app/src/main/java/com/reactnativenavigation/bridge/NavigationReactModule.java
android/app/src/main/java/com/reactnativenavigation/controllers/Modal.java
android/app/src/main/java/com/reactnativenavigation/controllers/ModalController.java
android/app/src/main/java/com/reactnativenavigation/controllers/NavigationActivity.java
android/app/src/main/java/com/reactnativenavigation/controllers/NavigationCommandsHandler.java
android/app/src/main/java/com/reactnativenavigation/params/parsers/ModalAnimationFactory.java
android/app/src/main/java/com/reactnativenavigation/params/parsers/ScreenParamsParser.java
android/app/src/main/java/com/reactnativenavigation/screens/ScreenAnimator.java
android/app/src/main/res/anim/no_animation.xml
android/app/src/main/res/anim/slide_down.xml
android/app/src/main/res/anim/slide_in_right.xml
android/app/src/main/res/anim/slide_out_right.xml
android/app/src/main/res/anim/slide_up.xml
android/app/src/main/res/values/config.xml
android/app/src/main/res/values/styles.xml
src/deprecated/platformSpecificDeprecated.android.js
src/platformSpecific.android.js

This commit adds support for fade and slide-horizontal animations for modals and a few other animation related changes:
* Support defining animationType when calling dismissModal
* Support fade and slide horizontal animations for modals
* Slightly reworked current screen animations timings
* Fixed slide-horizontal x offset and removed alpha

Modal animations

---

ios/RCCViewController.m

https://github.com/wix/react-native-navigation/issues/1858

fix iOS11 safeArea

---

docs/top-level-api.md
ios/RCCDrawerController/RCCDrawerController.m

support [shouldStretchDrawer](http://cocoadocs.org/docsets/MMDrawerController/0.6.0/Classes/MMDrawerController.html#//api/name/shouldStretchDrawer) of MMDrawerController

add shouldStretchDrawer property to drawerStyle

---

docs/screen-api.md
ios/RCCTabBarController.m
src/deprecated/controllers/index.js
src/deprecated/platformSpecificDeprecated.ios.js

Customize tab badge color

---

docs/styling-the-tab-bar.md

Fix for https://github.com/wix/react-native-navigation/issues/2026

Doc update for tabFontFamily

---

android/app/src/main/java/com/reactnativenavigation/controllers/NavigationActivity.java

Reverts wix/react-native-navigation#2057

Revert "Fix issues with Android BackHandler"

---

ios/RCCTabBarController.m

The fix we were discussing with you recently

Fixes issue with tabbar relative animation

---

docs/installation-ios.md

added some elaborations to make it easier for developers with no ios experience.

elaborations

---

src/Navigation.js
src/deprecated/platformSpecificDeprecated.android.js

Reverts wix/react-native-navigation#2174

Revert "Don't pass custom button props over the bridge"

---

ios/RCCViewController.m

Reverts wix/react-native-navigation#2090

Revert "Support iOS 11 prefersLargeTitles #1643"

---

AndroidE2E/app/src/androidTest/java/com/reactnativenavigation/e2e/androide2e/BackHandlerTest.java
AndroidE2E/app/src/androidTest/java/com/reactnativenavigation/e2e/androide2e/BaseTest.java
docs/docs/usage.md
docs/docs/v1tov2diff.md
lib/android/app/src/main/java/com/reactnativenavigation/NavigationActivity.java
lib/android/app/src/main/java/com/reactnativenavigation/react/ReactGateway.java
package.json
playground/src/containers/BackHandlerScreen.js
playground/src/containers/WelcomeScreen.js
playground/src/containers/index.js

Give precedence to react's BackHandler when hardware back button is pressed

Android back handler

---

lib/android/app/src/main/java/com/reactnativenavigation/parse/BottomTabsOptions.java
lib/android/app/src/main/java/com/reactnativenavigation/parse/LayoutFactory.java
lib/android/app/src/main/java/com/reactnativenavigation/parse/NavigationOptions.java
lib/android/app/src/main/java/com/reactnativenavigation/parse/TopBarOptions.java
lib/android/app/src/main/java/com/reactnativenavigation/react/NavigationModule.java
lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/Navigator.java
lib/android/app/src/test/java/com/reactnativenavigation/parse/NavigationOptionsTest.java
lib/src/Navigation.js
lib/src/adapters/NativeCommandsSender.js
lib/src/commands/Commands.js
lib/src/commands/Commands.test.js

Closes #1072
Usage
```js
Navigation.setDefaultOptions({
topBar: {
backgroundColor: 'red'
}
});
```

Android implementation of Navigation.setDefaultOptions

---

docs/top-level-api.md

Missed Comma throw "unexpected Token" error.

Missed comma

---

android/app/src/main/java/com/reactnativenavigation/params/StyleParams.java
android/app/src/main/java/com/reactnativenavigation/params/parsers/StyleParamsParser.java
android/app/src/main/java/com/reactnativenavigation/views/TopBar.java
android/app/src/main/java/com/reactnativenavigation/views/TopTabs.java
example/src/screens/types/TopTabs.js
src/deprecated/platformSpecificDeprecated.android.js

Added topTabTextFontFamily option so the font family of TopTabs can be set from JS now.
Resolves: #2146, #1784

[Android] TopTabs font family

---

ios/RCCCustomTitleView.h
ios/RCCCustomTitleView.m
ios/RCCViewController.m

Reverts wix/react-native-navigation#2306

Revert "Now allowing the custom nav bar to take up the whole space on iOS"

---

docs/third-party-libraries-support.md

Me and some others(#2267) needed some help integrating third party lib "redux-persist", so I added a Stack Overflow question + answer to the documentation.

Add documentation for third party lib "redux-persist"

---

AndroidE2E/app/src/androidTest/java/com/reactnativenavigation/e2e/androide2e/ModalsTest.java
lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/ModalStack.java
lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/Navigator.java
lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/ViewController.java
lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/NavigatorTest.java
playground/src/containers/ModalScreen.js

Implement push into modal

---

lib/android/app/src/main/java/com/reactnativenavigation/utils/UiUtils.java
lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/Navigator.java
lib/android/app/src/main/java/com/reactnativenavigation/views/ComponentLayout.java
lib/android/app/src/main/java/com/reactnativenavigation/views/touch/OverlayTouchDelegate.java
lib/android/app/src/test/java/com/reactnativenavigation/views/TouchDelegateTest.java

It was handled inappropriately and some touch events were
intercepted unintentionally.

Fix interceptTouchOutside

---

docs/styling-the-navigator.md
ios/RCCViewController.m

Add support for prefersLargeTitles in iOS 11

---

AndroidE2E/app/src/androidTest/java/com/reactnativenavigation/e2e/androide2e/OverlayTest.java

fixed failing unit test

---

docs/styling-the-navigator.md
ios/RCCViewController.m

This reverts commit f7ec9ee8408be2118cb3342fdd93f326d3aabb03.

Revert "[iOS] Large title text attributes (#2112)"

---

ios/RCCManagerModule.m

Added requiresMainQueueSetup to prevent warning and future side-effects in RCCManagerModule

---

ios/RCCViewController.m

Fix double titles when using largeTitle

---

lib/ios/RNNSideMenu/MMDrawerController/MMDrawerController.h
lib/ios/RNNSideMenu/MMDrawerController/MMDrawerController.m
lib/ios/RNNSideMenuOptions.h
lib/ios/RNNSideMenuOptions.m

API will look like this:
```
options: {
sideMenu: {
left: {
enabled: false
}
}
}
```

Side menu gesture enabled

---

lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/ModalStack.java
lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/Navigator.java
lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/modal/Modal.java
lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/modal/ModalCreator.java
lib/android/app/src/test/java/com/reactnativenavigation/mocks/ModalCreatorMock.java
lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/ModalStackTest.java
lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/NavigatorTest.java
lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/StackControllerTest.java
playground/src/screens/TextScreen.js

Find controller by id modal

---

lib/ios/RNNBottomTabsOptions.h
lib/ios/RNNBottomTabsOptions.m
lib/ios/RNNRootViewController.m
lib/ios/RNNTopBarOptions.h
lib/ios/RNNTopBarOptions.m
lib/ios/ReactNativeNavigationTests/RNNRootViewControllerTest.m
playground/src/screens/OptionsScreen.js
playground/src/screens/TextScreen.js

changed hidden prop to visible

---

lib/android/app/src/main/java/com/reactnativenavigation/parse/TopTabsOptions.java
lib/android/app/src/main/java/com/reactnativenavigation/presentation/OptionsPresenter.java
lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/ParentController.java
lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/StackController.java
lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/ViewController.java
lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/toptabs/TopTabsController.java
lib/android/app/src/main/java/com/reactnativenavigation/views/StackLayout.java
lib/android/app/src/main/java/com/reactnativenavigation/views/TopBar.java
lib/android/app/src/main/java/com/reactnativenavigation/views/TopTabs.java
lib/android/app/src/test/java/com/reactnativenavigation/parse/OptionsTest.java
lib/android/app/src/test/java/com/reactnativenavigation/utils/ViewHelper.java
lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/OptionsApplyingTest.java
lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/StackControllerTest.java
lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/TopTabsViewControllerTest.java

Currently only implemented on pop in StackController
* call clearOptions on super
* TopTabs visible

Initial implementation of willAppear and willDisappear

---

lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/StackController.java

Set layout params on views pushed to stack

---

ios/RCCViewController.m

fixes https://github.com/wix/react-native-navigation/issues/1771
Props to @gtRfnkN for finding this here: https://github.com/wix/react-native-navigation/issues/1771#issuecomment-326253684

ScreenVisibilityListener now called on disappear methods

---

docs/docs/Usage.md

Here are a bunch of grammar fixes.

[V2] Update Usage.md

---

docs/android-specific-use-cases.md

Added a missing curly bracket in top tabs example.

Added missing curly bracket

---

docs/README.md

The tables had some issues: the header for contributor column wasn't there (with the contributors still in place). I've re-added the headers where needed.
_(Other fix could be to remove the contributors if that's. Don't know which style you are following.)_

Fix README.md (v2)

---

android/app/src/main/java/com/reactnativenavigation/params/parsers/ScreenParamsParser.java

Fix crash when calling dismissModal before app was launched

---

docs/docs/top-level-api.md

I clarified some of the language here so that it is easier for the beginner to understand. (It was a little bit awkward before)

Improved the clarity of the top-level API doc

---

docs/docs/top-level-api.md

Further clarification of some of the top level API stuff.

Update top-level-api.md ... more copyediting.

---

docs/docs/styling.md

Was Halvetica meant to be Helvetica? Submitting a fix for review.

Fix font name in styling.md

---

docs/docs/styling.md

`styling.md`, changes
sideMenu: {
leftSideVisible: false,
rightSideVisible: false,
rightSideEnabled: true,
leftSideEnabled: true
}
to
sideMenu: {
left: {
visible: false,
enabled: true
},
right: {
visible: false,
enabled: true
}
}

More fixes to styling.md

---

lib/android/app/src/main/java/com/reactnativenavigation/parse/Options.java
lib/android/app/src/main/java/com/reactnativenavigation/presentation/ComponentOptionsPresenter.java
lib/android/app/src/test/java/com/reactnativenavigation/parse/OptionsTest.java

This matches property on the iOS V2 branch.
closes #3007

Added "screenBackgroundColor" setting

---

docs/README.md

The following  https://github.com/wix/react-native-navigation/pull/3006 implemented this functionality

Update doc since PR was accepted

---

docs/docs/Usage.md

I made the text a little more punchy and easy to read.

Copyediting for Usage.md

---

docs/screen-api.md
docs/top-level-api.md
src/Navigation.js
src/Screen.js
src/deprecated/platformSpecificDeprecated.ios.js

remove unused param from function

---

android/app/src/main/java/com/reactnativenavigation/controllers/NavigationActivity.java
android/app/src/main/java/com/reactnativenavigation/params/StyleParams.java
docs/styling-the-navigator.md
src/deprecated/platformSpecificDeprecated.android.js

Add Android support for rootBackgroundImageName

Add Android support for rootBackgroundImageName

---

android/app/src/main/java/com/reactnativenavigation/params/parsers/StyleParamsParser.java

fix https://github.com/wix/react-native-navigation/pull/3051

fix android rooBackgroundImage support

---

lib/android/app/src/main/java/com/reactnativenavigation/presentation/BottomTabsOptionsPresenter.java

Simplified commit for easier review

Fix iioobe bottom tab

---

lib/android/app/src/test/java/com/reactnativenavigation/react/ReactGatewayTest.java

Will help make sure the constructor is not made private by mistake

Implemented test for public constructor

---

src/deprecated/platformSpecificDeprecated.ios.js

Fixes objects contained on `passProps` getting frozen on iOS

Fixes freeze of passProps on iOS

---

src/deprecated/platformSpecificDeprecated.ios.js

Reverts wix/react-native-navigation#3220

Revert "Fixes freeze of passProps on iOS"

---

example/README.md

Fix broken link and mention the new [redux example project](https://github.com/junedomingo/movieapp).

Update docs for example project

---

docs/docs/topBar-buttons.md

Changed the property named tintColor to color

Update topBar-buttons.md changed the property named tintColor to color

---

lib/android/app/src/main/java/com/reactnativenavigation/NavigationActivity.java
lib/android/app/src/main/java/com/reactnativenavigation/NavigationApplication.java

added PermissionAwareActivity interface to NavigationActivity so it would play along with other libs that require permissions.

v2 proper permission handling (closes #3376)

---

docs/docs/layout-types.md

Fixed a little typo in the documentation.

Fixed typo in code snippet

---

ios/RCCViewController.m

Reverts wix/react-native-navigation#3405

Revert "Fix/rootview bounds iphone x"

---

docs/docs/Installing.md

Correct minor spelling mistake

---

docs/docs/styling.md

Fix spelling mistake

---

android/app/src/main/java/com/reactnativenavigation/views/LightBox.java

Due to a race condition, the height and width of the Lightbox screen
may be read too early, resulting in a zero-width or height lightbox.
Addresses Content of lightbox not displayed #2288

Android: Fix an issue with incorrect Lightbox measurments.

---

docs/docs/Installing.md

- Added missing step: Ignoring the build variants that we don't use.
-- Related issues: https://github.com/wix/react-native-navigation/issues/3388 and https://github.com/wix/react-native-navigation/issues/3505
- Converged Step 2 and 3 into one step since they both required tweaking according to the React-Native version a project uses.
Regression possibility: I might have broken a link to the docs?

Update Installing docs

---

lib/src/Navigation.ts
lib/src/components/ComponentRegistry.ts
lib/src/components/ComponentWrapper.test.tsx
lib/src/components/ComponentWrapper.tsx

Official redux support

---

docs/android-specific-use-cases.md

Changed "assums" to "assumes".

[v2] [docs] Fixed a typo.

---

docs/docs/Installing.md

Target react-native 0.56 version
Fix `MainActivity.java` and `MainApplication.java` with a working solution

[v2][doc] Update Installing.md

---

docs/docs/Installing.md

The diff does not render properly on [the website](https://wix.github.io/react-native-navigation/v2/#/docs/Installing?id=you-can-use-react-native-navigation-o). I believe the proposed change should fix this.

Fix diff not rendering properly

---

docs/docs/Installing.md

Some extra help concerning a common issue that occurs with fresh install of Xcode + react native 0.56. https://github.com/react-community/create-react-native-app/issues/316#issuecomment-351371080
Both myself and a colleague encountered this same issue on fresh installs following the steps in the documentation, so I think it is worth a note here.

Add helpful 3a step to Installing.md for ios

---

lib/ios/RNNReactRootView.m

Closes #3545

---

docs/README.md
docs/docs/options-migration.md
lib/ios/RNNBackgroundOptions.h
lib/ios/RNNRootViewController.m
lib/ios/ReactNativeNavigationTests/RNNRootViewControllerTest.m
lib/src/interfaces/Options.ts

[V2] Allow TopBar -> Background -> Clip To Bounds option

---

lib/ios/Bool.h
lib/ios/Bool.m
lib/ios/RNNSideMenu/MMDrawerController/MMDrawerController.h
lib/ios/RNNSideMenu/MMDrawerController/MMDrawerController.m
lib/ios/RNNSideMenuController.m
lib/ios/RNNSideMenuOptions.h
lib/ios/RNNSideMenuOptions.m
lib/ios/RNNSideMenuPresenter.m
lib/ios/RNNSideMenuSideOptions.h
lib/ios/RNNSideMenuSideOptions.m
lib/ios/ReactNativeNavigation.xcodeproj/project.pbxproj
lib/ios/ReactNativeNavigationTests/RNNSideMenuPresenterTest.m

```js
{
options: {
sideMenu: {
left: {
shouldStretchDrawer: true,
animationVelocity: 840.0
},
right: {
shouldStretchDrawer: false,
animationVelocity: 840.0
}
}
}
}
```

Fix side menu options

---

lib/ios/RNNBridgeManager.m
lib/ios/RNNCommandsHandler.h
lib/ios/RNNCommandsHandler.m
lib/ios/RNNControllerFactory.h
lib/ios/RNNControllerFactory.m
lib/ios/RNNOverlayOptions.m
lib/ios/RNNViewControllerPresenter.m
lib/ios/ReactNativeNavigationTests/RNNCommandsHandlerTest.m
lib/ios/ReactNativeNavigationTests/RNNControllerFactoryTest.m
lib/ios/ReactNativeNavigationTests/RNNViewControllerPresenterTest.m
lib/ios/ReactNativeNavigationTests/UIViewController+RNNOptionsTest.m
lib/ios/UIViewController+RNNOptions.h
lib/ios/UIViewController+RNNOptions.m

Fixes detached overlays on setRoot

---

e2e/ScreenStyle.test.js

Enabled set searchBar and handle onSearchUpdated e2e test

---

lib/ios/RNNNavigationController.m
lib/ios/RNNNavigationControllerPresenter.h
lib/ios/RNNNavigationControllerPresenter.m
lib/ios/ReactNativeNavigationTests/RNNNavigationControllerPresenterTest.m
lib/ios/ReactNativeNavigationTests/RNNNavigationControllerTest.m

Fix topBar.title.color on popping

---

lib/ios/UIViewController+RNNOptions.m

Fix iOS 9 setBadgeColor exception

---

lib/ios/RNNSideMenuController.m
lib/ios/RNNSideMenuPresenter.m
lib/ios/ReactNativeNavigationTests/RNNSideMenuPresenterTest.m

sideMenu.width should be initialized on viewController init

---

package.json

I needed to update the package in order to build the playground project.

Update detox package

---

docs/docs/top-level-api-migration.md

I believe there is a type in the docs. The title prop in bottomTab should be text.

Fix docs. Change bottomTab title to text.

---

README.md
docs/README.md

updated broken docs links in READMEs

---

lib/android/app/src/main/java/com/reactnativenavigation/react/NavigationModule.java
lib/android/app/src/main/java/com/reactnativenavigation/utils/CollectionUtils.java
lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/IdStack.java
lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/navigator/Navigator.java
lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/stack/StackController.java
lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/IdStackTest.java
lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/navigator/NavigatorTest.java
lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/stack/StackControllerTest.java
lib/ios/RNNBridgeModule.m
lib/ios/RNNCommandsHandler.h
lib/ios/RNNCommandsHandler.m
lib/ios/RNNControllerFactory.h
lib/ios/RNNControllerFactory.m
lib/ios/RNNNavigationStackManager.h
lib/ios/RNNNavigationStackManager.m
lib/ios/ReactNativeNavigationTests/RNNCommandsHandlerTest.m
lib/ios/ReactNativeNavigationTests/RNNNavigationStackManagerTest.m
lib/src/Navigation.ts
lib/src/commands/Commands.test.ts
lib/src/commands/Commands.ts
playground/src/screens/PushedScreen.js

This PR adds support for setting stack root with multiple children, which is to be expected as stack can be initialised with multiple children.

Set stack root refactor

---

playground/src/screens/CustomTopBar.js

Reverts wix/react-native-navigation#4554

Revert "scrollview is not scrollable when using overlay in android"

---

lib/android/app/src/main/java/com/reactnativenavigation/views/touch/OverlayTouchDelegate.java
playground/src/app.js
playground/src/screens/ComplexLayout.js
playground/src/screens/OptionsScreen.js
playground/src/screens/complexlayouts/CustomDialogWithScroll.js

Fixes an issue with ScrollView inside an Overlay. While down events were propagated to the view, move events were consumed by the overlay preventing scroll components from functioning correctly.

Overlay with scroll view

---

docs/docs/events.md

Add registerModalDismissedListener to events list in doc.

Add Modal Dismissed Event Listener to doc

---

docs/docs/Usage.md

Link to layout-types.md in Usage.md is broken.

Fixed link to layout-types.md

---

lib/android/app/src/main/java/com/reactnativenavigation/views/titlebar/TitleBar.java

fixes https://github.com/wix/react-native-navigation/issues/4659

[v2] [Android] Fix Android title centering bug

---

docs/docs/styling.md

via: https://github.com/wix/react-native-navigation/issues/4626

[Fixing: #4626] Update styling.md

---

lib/ios/RNNSplashScreen.h
lib/ios/RNNSplashScreen.m

This fixed the rest of the problem with the launch process in iOS. (Reference #4515)

Improved RNNSplashScreen status bar styling

---

lib/ios/RNNCommandsHandler.m

Fix peek and pop preview on iOS

---

docs/docs/showcases.md

[V2] Fix: typo in documentation: Stater kits

---

lib/android/app/src/main/java/com/reactnativenavigation/views/titlebar/TitleBar.java
lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/TitleBarTest.java

React button components now support overflow: visible. This property is especially useful when displaying buttons with a badge
which exceeds the button bounds.

Fix overflow visible for react button components in TopBar

---

docs/docs/layout-types.md

Add curly braces around the visible property

[v2][Documentation] Fix code sample in the documentation for layouts bottomTabs

---

lib/android/app/build.gradle

Match android dependencies to app configuration

---

package.json
playground/android/app/build.gradle
playground/android/app/src/androidTest/java/com/reactnativenavigation/playground/DetoxTest.java
playground/android/build.gradle
scripts/test-e2e.js

CI stopped supporting Detox 9.x `¯\_(ツ)_/¯`

Migrate to Detox 12

---

lib/ios/RNNBasePresenter.h
lib/ios/RNNBasePresenter.m
lib/ios/RNNTabBarController.m
lib/ios/RNNTabBarPresenter.m
lib/ios/ReactNativeNavigationTests/RNNTabBarPresenterTest.m

Apply bottomTabs options after children added

---

lib/ios/RNNSideMenuChildVC.m
lib/ios/RNNSideMenuController.m

Fix sideMenu orientation options

---

lib/ios/RNNViewControllerPresenter.m

Reset navigationItem.titleView before applying new one, Fix topBar.titleView calculation on props change

Fix topBar.titleView calculation on props change

---

lib/ios/RNNBasePresenter.h
lib/ios/RNNBasePresenter.m
lib/ios/RNNNavigationController.m
lib/ios/RNNNavigationControllerPresenter.m

Fix topBar.background.component render behind title

---

lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/sidemenu/SideMenuController.java
lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/sidemenu/SideMenuControllerTest.java

Emit SideMenu visibility events

---

playground/android/app/build.gradle

Fixes the startup crashes on android when releasing.
https://github.com/wix/react-native-navigation/issues/4724

fix_4724: Fixes android crashes on startup

---

lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/ChildController.java
lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/ChildControllersRegistry.java
lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/ViewController.java
lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/stack/StackController.java
lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/child/ChildControllerTest.java
lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/child/ChildControllersRegistryTest.java
lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/stack/StackControllerTest.java

Address race conditions around ViewController.destroy

---

lib/android/app/src/main/java/com/reactnativenavigation/parse/TitleOptions.java
lib/android/app/src/main/java/com/reactnativenavigation/presentation/StackPresenter.java
lib/android/app/src/main/java/com/reactnativenavigation/views/titlebar/TitleBar.java
lib/android/app/src/main/java/com/reactnativenavigation/views/topbar/TopBar.java

Useful for aligning the title when TopBar height is changed.

Add title.topMargin option

---

lib/android/app/src/main/java/com/reactnativenavigation/views/BottomTabs.java
lib/android/app/src/main/java/com/reactnativenavigation/views/ComponentLayout.java
lib/android/app/src/main/java/com/reactnativenavigation/views/ExternalComponentLayout.java
lib/android/app/src/main/java/com/reactnativenavigation/views/StackLayout.java
lib/android/app/src/main/java/com/reactnativenavigation/views/titlebar/TitleBar.java
lib/android/app/src/main/java/com/reactnativenavigation/views/topbar/TopBar.java

Remove setContentDescription calls (#3984)

---

lib/src/interfaces/Options.ts

Document topBar options for Android's showAsAction

---

docs/docs/options-migration.md

Corrected 
Controls he behavior of screens displayed modally. 
to this
Controls the behavior of screens displayed modally.

Typo correction 

---

lib/ios/Constants.m

Fixed constants bug

---

lib/android/app/src/main/java/com/reactnativenavigation/presentation/BottomTabPresenter.java
lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/bottomtabs/AttachMode.java
lib/android/app/src/main/java/com/reactnativenavigation/views/SideMenu.java
lib/android/app/src/test/java/com/reactnativenavigation/EnvironmentTest.java
lib/android/app/src/test/java/com/reactnativenavigation/utils/TypefaceLoaderTest.java

Remove android * imports for support

---

lib/src/interfaces/Options.ts

Closes https://github.com/wix/react-native-navigation/issues/5231

Add width and height attributes to SideMenuSide type

---

lib/ios/Constants.m
lib/ios/RNNLayoutProtocol.h
lib/ios/RNNNavigationController.m
lib/ios/RNNRootViewController.m
lib/ios/RNNSideMenuController.m
lib/ios/RNNTabBarController.m
lib/ios/UIViewController+LayoutProtocol.m
playground/src/services/Navigation.js

This approach is still not ideal as it assumes there's a visible stack somewhere in the Hierarchy.
It's better than the current implementation so I'm pushing it and will reiterate in the future if needed.

Fix Constants.topBarHeight

---

lib/ios/RNNUIBarButtonItem.m

Hides react view button until its size get's calculated in order to prevent it from flickering.

Fix custom react view button flickering

---

docs/docs/showcases.md

I mentioned in #4669 that I created a starter kit. Here is a link in the docs to it (only a few months after the fact)

[V2] [Docs] Add alexwasner/RNMFS starter kit

---

lib/ios/RNNNavigationController.m
lib/ios/ReactNativeNavigationTests/RNNNavigationControllerTest.m

• Fix the transition between transparent background color to colorized background.
• Remove storing topBar background image.

Fix transparent topBar background color transition

---

lib/android/app/build.gradle

Removing the legacy support library from build.gradle

Removed the legacy support lib

---

lib/ios/RNNComponentPresenter.m
lib/ios/RNNStackPresenter.m
lib/ios/RNNTitleViewHelper.m

Fix topBar title alignment on iOS

---

lib/android/app/src/main/java/com/reactnativenavigation/react/EventEmitter.java
lib/android/app/src/main/java/com/reactnativenavigation/react/NavigationModule.java
lib/android/app/src/main/java/com/reactnativenavigation/utils/NativeCommandListener.java
lib/android/app/src/test/java/com/reactnativenavigation/utils/NativeCommandListenerTest.java
lib/src/interfaces/Events.ts

Add missing commandName field

---

lib/ios/RNNReactView.m

React view title layout didn't recalculated it size on orientation change which caused it to look bad on iPads.

Fix react view title fill alignment

---

lib/ios/RNNBridgeManager.m
lib/ios/RNNCommandsHandler.m
lib/ios/RNNModalManager.h
lib/ios/RNNModalManager.m
lib/ios/RNNOverlayManager.h
lib/ios/RNNOverlayManager.m
lib/ios/ReactNativeNavigationTests/RNNModalManagerTest.m
playground/src/screens/NavigationScreen.js

This fix a leak reproduce on reloading react-native on iOS.

Dismiss presented modals and clear the component store on reloading

---

lib/ios/RNNComponentPresenter.m
lib/ios/RNNStackPresenter.m
lib/ios/UINavigationBar+utils.h
lib/ios/UINavigationBar+utils.m
lib/ios/UINavigationController+RNNOptions.h
lib/ios/UINavigationController+RNNOptions.m
lib/ios/UIViewController+RNNOptions.h
lib/ios/UIViewController+RNNOptions.m
playground/ios/NavigationTests/RNNComponentPresenterTest.m
playground/ios/NavigationTests/RNNStackPresenterTest.m
playground/ios/NavigationTests/UINavigationController+RNNOptionsTest.m
playground/ios/NavigationTests/UIViewController+LayoutProtocolTest.m

Closes https://github.com/wix/react-native-navigation/issues/5697

Fix back button on iOS 13

---

lib/ios/UINavigationBar+utils.h
lib/ios/UINavigationBar+utils.m
playground/ios/NavigationTests/RNNNavigationControllerTest.m
playground/ios/NavigationTests/RNNRootViewControllerTest.m

Closes https://github.com/wix/react-native-navigation/issues/5691

Fix transparent topBar option

---

lib/ios/UINavigationBar+utils.h
lib/ios/UINavigationBar+utils.m
lib/ios/UINavigationController+RNNOptions.m
playground/ios/NavigationTests/RNNRootViewControllerTest.m

Addresses https://github.com/wix/react-native-navigation/issues/5696

Fix topBar.noBorder option on iOS 13

---

lib/ios/RNNComponentPresenter.m
lib/ios/RNNComponentViewController.m
lib/ios/RNNStackPresenter.m
playground/ios/NavigationTests/RNNComponentPresenterTest.m

Fix topBar component setDefaultOptions issue

---

lib/ios/RNNComponentPresenter.m
lib/ios/RNNFontAttributesCreator.h
lib/ios/RNNFontAttributesCreator.m
lib/ios/RNNTabBarItemCreator.m
lib/ios/UINavigationBar+utils.h
lib/ios/UINavigationBar+utils.m
lib/ios/UINavigationController+RNNOptions.m
playground/ios/NavigationTests/RNNFontAttributesCreatorTest.m
playground/ios/NavigationTests/RNNRootViewControllerTest.m

Fix largeTitle behaviour on iOS 13

---

lib/ios/RNNStackPresenter.m
lib/ios/UINavigationBar+utils.m

Fix black topBar background color

---

lib/android/app/src/main/java/com/reactnativenavigation/react/NavigationModule.java
lib/ios/RNNBridgeModule.m
lib/src/adapters/Constants.ts

Rename internal getConstants method to prevent conflicts with RN's getConstants method

---

lib/ios/Constants.m
lib/ios/RNNStackController.m
lib/ios/UINavigationController+RNNOptions.m

Fix topBarHeight with UIModalPresentationPageSheet

---

lib/ios/RNNFontAttributesCreator.m

Fix default font size regression

---

lib/ios/RNNOverlayManager.m

Fix crash when reload with overlays presented

---

lib/ios/RNNFontAttributesCreator.m
lib/ios/RNNLayoutProtocol.h
lib/ios/RNNModalManager.m
lib/ios/UIViewController+LayoutProtocol.h
lib/ios/UIViewController+LayoutProtocol.m
playground/ios/NavigationTests/RNNModalManagerTest.m

Fix modal dismissed event emits wrong componentId

---

playground/src/screens/SideMenuLeftScreen.js

Motivation: Try to reproduce #5833

Change SideMenuLeftScreen to functional component

---

lib/android/app/src/main/java/com/reactnativenavigation/parse/BackButton.java
lib/android/app/src/main/java/com/reactnativenavigation/parse/params/Button.java
lib/android/app/src/main/java/com/reactnativenavigation/parse/parsers/TextParser.java
lib/android/app/src/main/java/com/reactnativenavigation/utils/ObjectUtils.java
lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/TitleBarButtonController.java

* Text buttons use the button's text by default as accessibility label for screen readers.
* Added default 'Navigate Up' label to back button

Add accessibilityLabel option to button

---

lib/android/app/src/main/java/com/reactnativenavigation/views/topbar/TopBar.java
lib/android/app/src/test/java/com/reactnativenavigation/views/TopBarTest.java

Disable TopBar scroll when nestedScrollEnabled is enabled

---

docs/docs/styling.md

Moved FAB configuration from common to android since it isn't cross
platform.

moved FAB configuration

---

lib/ios/RNNBasePresenter.h
lib/ios/RNNBasePresenter.m
lib/ios/RNNComponentPresenter.h
lib/ios/RNNComponentPresenter.m
lib/ios/RNNControllerFactory.m
lib/ios/ReactNativeNavigation.xcodeproj/project.pbxproj
lib/ios/TopBarTitlePresenter.h
lib/ios/TopBarTitlePresenter.m
playground/ios/NavigationIOS12Tests/RNNRootViewControllerTest.m
playground/ios/NavigationTests/RNNCommandsHandlerTest.m
playground/ios/NavigationTests/RNNComponentPresenterTest.m
playground/ios/NavigationTests/RNNRootViewControllerTest.m

•Move topBar.title options handling to topBarTitlePresenter
• Fix topBar.title default system behavior
Closes #5431, #4374

Move all topBar.title options to topBarTitlePresenter

---

lib/src/interfaces/Options.ts

Move selectTabOnPress prop to correct interface

---

lib/ios/RNNBasePresenter.m
lib/ios/RNNNavigationOptions.h
lib/ios/RNNNavigationOptions.m
lib/ios/ReactNativeNavigation.xcodeproj/project.pbxproj
lib/ios/WindowOptions.h
lib/ios/WindowOptions.m

This PR adds a new option which allow controlling the window color on iOS.
```js
window: {
backgroundColor: 'white'
}
```

Add window.backgroundColor option

---

lib/android/app/src/main/java/com/reactnativenavigation/anim/NavigationAnimator.java
lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/stack/StackController.java
lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/stack/StackControllerTest.java
playground/src/commons/Options.js

Custom push animations broke after refactoring Shared Element Transition.
Fixes #5943

Fix custom push animations

---

lib/ios/BottomTabAppearancePresenter.h
lib/ios/BottomTabAppearancePresenter.m
lib/ios/BottomTabPresenter.h
lib/ios/BottomTabPresenter.m
lib/ios/BottomTabPresenterCreator.h
lib/ios/BottomTabPresenterCreator.m
lib/ios/BottomTabsAppearancePresenter.h
lib/ios/BottomTabsAppearancePresenter.m
lib/ios/BottomTabsPresenterCreator.h
lib/ios/BottomTabsPresenterCreator.m
lib/ios/RNNBasePresenter.m
lib/ios/RNNBottomTabOptions.h
lib/ios/RNNBottomTabOptions.m
lib/ios/RNNBottomTabsPresenter.h
lib/ios/RNNBottomTabsPresenter.m
lib/ios/RNNControllerFactory.m
lib/ios/RNNTabBarItemCreator.h
lib/ios/RNNTabBarItemCreator.m
lib/ios/ReactNativeNavigation.xcodeproj/project.pbxproj
lib/ios/TabBarItemAppearanceCreator.h
lib/ios/TabBarItemAppearanceCreator.m
lib/ios/UITabBarController+RNNOptions.h
lib/ios/UITabBarController+RNNOptions.m
playground/ios/NavigationIOS12Tests/RNNBottomTabsPresenterTest.m
playground/ios/NavigationTests/RNNBasePresenterTest.m
playground/ios/NavigationTests/RNNBottomTabsAppearancePresenterTest.m
playground/ios/NavigationTests/RNNDotIndicatorPresenterTest.m
playground/ios/NavigationTests/UITabBarController+RNNOptionsTest.m
playground/ios/playground.xcodeproj/project.pbxproj

Closes #5952
closes #5728
closes #5701

Bottom tabs appearance iOS 13 support

---

lib/android/app/src/main/java/com/reactnativenavigation/parse/LayoutFactory.java
lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/externalcomponent/ExternalComponentViewController.java
lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/ExternalComponentViewControllerTest.java

This commit fixes a long lasting tech debt - ExternalViewController now extends ChildController.

ExternalViewController extends ChildController

---

.github/stale.yml
lib/ios/RNNStackController.m
lib/ios/RNNStackPresenter.m
lib/ios/TopBarPresenter.m
lib/ios/UINavigationController+RNNOptions.h
lib/ios/UINavigationController+RNNOptions.m
playground/ios/NavigationTests/RNNStackControllerTest.m
playground/ios/NavigationTests/RNNStackPresenterTest.m
playground/ios/playground.xcodeproj/project.pbxproj

Fix large title presentation

---

lib/ios/Color+Interpolation.h
lib/ios/Color+Interpolation.m
lib/ios/RNNInterpolator.m

Fix symbol collision with react-native-keyboard-input

---

lib/ios/RNNBottomTabsController.m
playground/ios/NavigationTests/RNNCommandsHandlerTest.m
playground/ios/NavigationTests/RNNLayoutManagerTest.m
playground/ios/NavigationTests/utils/RNNComponentViewController+Utils.h
playground/ios/NavigationTests/utils/RNNComponentViewController+Utils.m
playground/ios/playground.xcodeproj/project.pbxproj

Merge bottomTabs options with correct child

---

lib/ios/BottomTabsPresenterCreator.h
lib/ios/BottomTabsPresenterCreator.m
lib/ios/ElementFrameTransition.h
lib/ios/RNNBridgeModule.m
lib/ios/RNNCommandsHandler.m
lib/ios/RNNControllerFactory.m
lib/ios/RNNModalManager.h
lib/ios/RNNModalManager.m
lib/ios/RNNSideMenuPresenter.m
lib/ios/RNNSplitViewControllerPresenter.m
lib/ios/RNNStackPresenter.m

* Fix possible retain cycles in commands handler
* Fix compiler build warnings

Fix build warnings on iOS

---

docs/docs/top-level-api.md

Show transparent overlay option in docs

Show transparent overlay option in docs

---

website/api/layout-BottomTabs.mdx
website/docs/docs-bottomTabs.mdx
website/docs/docs-root.mdx
website/docs/style-theme.mdx

A stack, as any layout, needs to be an object.

Fix child layouts in documentation

---

website/docs/third-party-mobx.mdx
website/docs/third-party-react-context.mdx
website/sidebars.js

This PR is a continuation of #6064, as the `docusarus` branch got merged into the master I couldn't rebase the branch properly so just decided to create a new PR with a fresh branch (I'm bad with Git 😅).
What's changed:
- Added a new side bar, `Third party integration` and to that added `React Context API` and `MobX` documentation. 
- Added a limitation of using React Context API with RNN so people are informed of such caveat.
- Informed the readers that if they wish to trigger re-renders across all screens, they need to use the alternatives such as MobX or Redux.

React Context API & MobX integration doc

---

lib/ios/RNNStackPresenter.m
lib/ios/TopBarPresenter.m
lib/ios/UINavigationController+RNNOptions.h
lib/ios/UINavigationController+RNNOptions.m
playground/ios/NavigationTests/RNNStackPresenterTest.m

Fix backButton.color change on mergeOptions

---

lib/ios/TabBarItemAppearanceCreator.m

Fix bottomTab colors in landscape orientation

---

lib/android/app/src/main/java/com/reactnativenavigation/parse/LayoutFactory.java
lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/bottomtabs/BottomTabsAttacher.java
lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/bottomtabs/BottomTabsAttacherTest.java
lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/bottomtabs/BottomTabsControllerTest.java
lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/navigator/NavigatorTest.java

Default options were not taken into account when resolving tabsAttachMode property.

Resolve tabsAttachMode from default options

---

.grenrc.js
package.json
scripts/release.js

This PR will create a new release note on each version release.
It's the first step towards adding auto generated change log.

Create github release note in CI

---

lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/navigator/Navigator.java
lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/navigator/NavigatorTest.java

Support for the react-native-youtube package was added in #5999 but due to a faulty merge it wasn't complete.
Fixes #6214

Fix react-native-youtube support

---

lib/src/index.ts

It was left out of ec7f324 by mistake

Export NavigationComponentListener

---

e2e/BottomTabs.test.js
lib/ios/RNNBasePresenter.m
playground/src/screens/SecondBottomTabScreen.js

Fix tabBar visibility

---

lib/android/app/src/main/java/com/reactnativenavigation/NavigationActivity.java

…and handle missing navigator in onDestroy
resolves #6281

Skip creating navigator in case isFinishing in onCreate

---

lib/ios/RNNComponentPresenter.m

This PR fixes #4443 
The problem was that `withDefault.topBar.searchBar.hasValue` was true when setting `topBar.searchBar = false`.

Fix SearchBar false render

---

lib/android/app/src/main/java/com/reactnativenavigation/views/bottomtabs/BottomTabs.java
lib/android/app/src/test/java/com/reactnativenavigation/views/bottomtabs/BottomTabsTest.kt

Fix flickering BottomTabs when pushing a screen with waitForRender

---

lib/src/Navigation.ts
lib/src/commands/Deprecations.ts
lib/src/commands/LayoutTreeCrawler.test.ts
lib/src/commands/LayoutTreeCrawler.ts
lib/src/commands/OptionsProcessor.test.ts
lib/src/commands/OptionsProcessor.ts
lib/src/interfaces/Processors.ts
lib/src/processors/LayoutProcessor.test.ts
lib/src/processors/LayoutProcessor.ts

* Fix option processors
* Change `commandName` type to `CommandName`

Fix option processors

---

lib/ios/RNNSideMenuPresenter.m
playground/ios/NavigationTests/RNNSideMenuPresenterTest.m
website/api/options-sideMenu.mdx

Change sideMenu.openGestureMode default to entireScreen

---

website/docs/style-theme.mdx

Document the two new API's: `registerOptionsProcessor` and `registerLayoutProcessor`

Document new apis

---

lib/android/app/src/main/java/com/reactnativenavigation/utils/ViewUtils.java
lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/stack/FabPresenter.java
lib/src/interfaces/Options.ts
playground/src/screens/ScrollViewScreen.tsx

When updating FAB options with mergeOptions, id must be passed as well.

Fab id is mandatory

---

website/api/api-options.mdx
website/docs/style-screens.mdx
website/sidebars.js

Document the various methods which can be used to style screens with options.

Document Options usage

---

lib/android/app/src/main/java/com/reactnativenavigation/utils/AnimationListener.kt
lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/modal/ModalAnimator.java
lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/modal/ModalPresenter.java
lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/modal/ModalAnimatorMock.java
lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/modal/ModalAnimatorTest.kt

Cancel showModal animation if back was pressed during animation

---

lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/stack/StackPresenter.java
lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/stack/StackPresenterTest.java

This commit fixes an issue where buttons added with mergeOptions were not unmounted.

Unmount merged right buttons

---

lib/ios/RNNComponentViewController.m
lib/ios/Utils/UIView+Utils.h
lib/ios/Utils/UIView+Utils.m

Fix momentum scroll bug on iOS

---

website/docs/docs-Installing.mdx

Copied over from playground app.
Sets the version only once and then reuses the variable

Updated android install instructions

---

lib/ios/ColorParser.m
playground/ios/NavigationTests/ColorParserTest.m
playground/ios/playground.xcodeproj/project.pbxproj

Return `NoColor` object when `NoColor` string is passed as the color from JS.

Fix color parser

---

lib/ios/RCTConvert+SideMenuOpenGestureMode.h
lib/ios/RCTConvert+SideMenuOpenGestureMode.m
lib/ios/RCTConvert+UIFontWeight.h
lib/ios/RCTConvert+UIFontWeight.m
lib/ios/ReactNativeNavigation.xcodeproj/project.pbxproj

Prevents linker warnings as described in https://github.com/wix/react-native-navigation/pull/6476

Moved @implementation to .m files

---

playground/ios/playground.xcodeproj/project.pbxproj

@yogevbd Wasn't sure if this is supposed to be committed. I've run `yarn pod-install` and this file got updated.

iOS Pod install uncommitted file

---

lib/ios/RNNComponentPresenter.m
lib/ios/UIViewController+RNNOptions.h
lib/ios/UIViewController+RNNOptions.m

Fix searchBarHiddenWhenScrolling not working when searchBar should be displayed on the root screen

---

lib/ios/BaseAnimator.m

Fix animations last tick

---

website/docs/docs/meta-contributing.mdx

I've added steps to follow for contributing to the project (iOS for now).

Add steps to follow for contributing to the project

---

lib/ios/LayerBoundsTransition.h
lib/ios/LayerBoundsTransition.m
lib/ios/RNNInterpolator.h
lib/ios/RNNInterpolator.m
lib/ios/ReactNativeNavigation.xcodeproj/project.pbxproj
lib/ios/RectTransition.m
lib/ios/SharedElementAnimator.m
lib/ios/TransformRectTransition.h
lib/ios/TransformRectTransition.m

* Move layer bounds animation to designated transition object
* Move resolve transform transition to RNNInterpolator

Refactor shared element transitions

---

playground/ios/playground/AppDelegate.m

This change aligns the app delegate a bit more with the current rn hello world template.

Added UIWindow init to playground to demonstrate usage

---

lib/ios/UIViewController+RNNOptions.h

This removes warnings in XCode 12.

Added _Nullable modifier to UIViewController category methods

---

playground/src/screens/Screens.ts
playground/src/screens/index.tsx
playground/src/screens/sharedElementCarDealer/CarStoryScreen.tsx
playground/src/screens/sharedElementCarDealer/CarsListScreen.tsx
playground/src/screens/sharedElementCarDealer/Constants.ts
playground/src/screens/sharedElementCarDealer/DismissableView.tsx

Repro for the Text Scale issue on Android. 
How to reproduce:
1. Change `SET_DURATION` in `playground/src/screens/sharedElementCarDealer/Constants.ts` to something high like `5000`
2. (In playground app) go to Navigation > Shared Element (Car Dealer)
3. Press one of the blue circles at the top (should represent stories)
4. Swipe down to dismiss story, notice how Car name (title) and first letter of car (`L`: should represent some icon of some sort) initially start with incorrect scale

Set text scale repro

---

lib/ios/RNNBasePresenter.m
playground/src/screens/ModalScreen.tsx

Fixes #5888 Cannot change swipeToDismiss through mergeOptions

---

lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/component/ComponentViewController.java
lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/component/ComponentViewControllerTest.java

Fix statusBar.drawBehind not respected when defined in default options

---

website/docs/docs/docs-Installing.mdx

Added pod install to docs

---

lib/src/interfaces/Options.ts
website/docs/api/options-migration.mdx
website/docs/api/options-statusBar.mdx

* `animated`
* `hideWithTopBar`
* `blur`

Fix statusbar typings and docs

---

lib/ios/BottomTabsTogetherAttacher.m
lib/ios/UIViewController+LayoutProtocol.m

Propagate waitForRender to bottom tabs children

---

lib/ios/TabBarItemAppearanceCreator.m

Reverts wix/react-native-navigation#6690

Revert "fix for truncated tab item names on ios14"

---

lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/bottomtabs/attacher/modes/AttachMode.java
lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/bottomtabs/attacher/modes/OnSwitchToTab.java
lib/ios/BottomTabsBasePresenter.m

Apply bottomTabs.currentTabId on init

---

lib/android/app/src/main/java/com/reactnativenavigation/options/parsers/TypefaceLoader.kt
lib/android/app/src/main/java/com/reactnativenavigation/utils/ReactTypefaceUtils.java

Copy ReactTypefaceUtils to provide backwards compatibilty for rn < 0.62

---

lib/ios/RNNSideMenuChildVC.m

Render child vc first before attaching it to the view hierarchy

---

lib/android/app/src/main/java/com/reactnativenavigation/options/parsers/InterpolationParser.java
lib/ios/Interpolators/FastOutSlowIn.h
lib/ios/Interpolators/FastOutSlowIn.m
lib/ios/RCTConvert+Interpolation.m
lib/src/interfaces/Options.ts

This interpolator starts fast and slows down as the animation ends. Implementation on iOS is copied from Android.

Add FastOutSlowIn interpolator

---

lib/ios/RNNSideMenu/MMDrawerController/MMDrawerController.m

Fix stack popGesture in sideMenu

---

lib/ios/Bool.h
lib/ios/Bool.m
lib/ios/TopBarAppearancePresenter.h
lib/ios/TopBarAppearancePresenter.m
lib/ios/TopBarPresenter.h
playground/ios/NavigationTests/BottomTabsControllerTest.m
playground/ios/NavigationTests/RNNBasePresenterTest.m
playground/ios/NavigationTests/RNNNavigationStackManagerTest.m
playground/ios/NavigationTests/RNNSideMenuControllerTest.m
playground/ios/NavigationTests/RNNStackControllerTest.m
playground/ios/NavigationTests/TopBarAppearancePresenterTest.m

Fix toggling topBar border visibility

---

website/docs/docs/docs-stack.mdx

Multiple left buttons as well as textual and component buttons are now supported on Android.

Update buttons documentation

---

lib/ios/RNNBridgeManager.mm
lib/ios/RNNSearchBarOptions.m
playground/ios/NavigationTests/RNNSearchBarOptionsTest.m
playground/ios/playground.xcodeproj/project.pbxproj

Fixes wrong `topBar.searchBar.hideOnScroll` parsing on iOS which broke this feature.
Closes #6848

Fix searchBar.hideOnScroll

---

lib/ios/TopBarAppearancePresenter.m
playground/ios/NavigationTests/TopBarAppearancePresenterTest.m

Fix title flashes during transition between small and large title while scrolling.
Closes #6847

Fix title flashes during transition between small and large title while scrolling

---

autolink/postlink/gradleLinker.js
website/docs/docs/docs-Installing.mdx
website/versioned_docs/version-7.0.0/docs/docs-Installing.mdx

Fix auto-link wrong minSdkVersion

---

lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/stack/StackPresenter.java
lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/stack/StackPresenterTest.java

Fix top bar flickering at first render with an empty title

---

lib/ios/RNNBackButtonOptions.h
lib/ios/RNNBackButtonOptions.m
lib/ios/RNNUIBarBackButtonItem.h
lib/ios/RNNUIBarBackButtonItem.m
lib/ios/ReactNativeNavigation.xcodeproj/project.pbxproj
lib/ios/TopBarPresenter.m
lib/src/interfaces/Options.ts
playground/src/screens/PushedScreen.tsx
website/docs/api/options-backButton.mdx

Allow disabling iOS 14 long back button menu

---

lib/android/build.gradle
lib/android/gradle.properties
lib/android/gradle/wrapper/gradle-wrapper.properties
playground/android/gradle.properties

Fix flaky e2e tests caused by [this PR](https://github.com/wix/react-native-navigation/pull/6762).

Fix flaky e2e tests in CI

---

website/docs/docs/docs-before-you-start.mdx
website/versioned_docs/version-6.12.2/docs/docs-before-you-start.mdx
website/versioned_docs/version-7.7.0/docs/docs-before-you-start.mdx
website/versioned_docs/version-7.8.1/docs/docs-before-you-start.mdx

It should be "bear in mind", not "bare in mind", fixed that everywhere my IDE found it.

One particular typo fixed

---

website/docs/docs/third-party-react-native-vector-icons.mdx
website/docs/docs/third-party-react-native-vector-icons/ExampleComponent.tsx
website/docs/docs/third-party-react-native-vector-icons/MyIcon.tsx
website/docs/docs/third-party-react-native-vector-icons/NavIcons.tsx
website/docs/docs/third-party-react-native-vector-icons/index.ts

As requested, a small writeup detailing how I incorporated react-native-vector-icons into my React Native Navigation project.

Initial documentation for integration with react-native-vector-icons

---

website/versioned_docs/version-7.8.1/docs/docs-basic-navigation.mdx

Hi all!
I'm submitting this really minor PR with some fixes for the docs. Just stuff I see as a I go along reviewing the docs (I have to go through it every single time I'm starting a new project 😂 )
- Minor grammar/wording changes.
- Added a few missing spaces here and there in the examples.

(docs) Update Basic Navigation docs

---

lib/src/interfaces/Options.ts

Exports the `Interpolation` and `SystemItemIcon` types

Export Interpolation and SystemItemIcon types

---

lib/ios/RNNComponentViewController.m

Fix momentum scroll bug

---

lib/ios/Utils/UIView+Utils.m

Improves #7000 to add support for nested scroll views. (Currently it only works with the main scroll view)

Fix momentum scroll bug with nested scroll views

---

autolink/postlink/appDelegateLinker.js

Fix rnn-link script for react-native 0.64

---

website/src/pages/showcase/index.jsx

Fix copy paste mistake in showcase section in the docs

---

lib/ios/RNNAnimationsOptions.m
lib/ios/ViewAnimationOptions.m

Fix disabling modal animations on iOS

---

lib/android/app/src/reactNative51/java/com/reactnativenavigation/react/ReactGateway.java
lib/android/app/src/reactNative55/java/com/reactnativenavigation/react/ReactGateway.java
lib/android/app/src/reactNative56/java/com/reactnativenavigation/react/ReactGateway.java
lib/android/app/src/reactNative57/java/com/reactnativenavigation/react/ReactGateway.java
lib/android/app/src/reactNative57_5/java/com/reactnativenavigation/react/ReactGateway.java
lib/android/app/src/reactNative60/java/com/reactnativenavigation/react/ReactGateway.java
lib/android/app/src/reactNative62/java/com/reactnativenavigation/react/ReactGateway.java

Broken by #7059. Resolves #7098.

Make react-native-navigation compile again (Android, reactNative < 63)

---

lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/viewcontroller/Presenter.java

Leaving statusBar.style undefined leads to iOS inferring the status bar text style. This change applies the same behavior to android by analysing the status bar background color (like already done for the navigation bar).

Align statusBar.style behavior with iOS

---

website/versioned_docs/version-7.16.0/docs/docs-showcases.mdx

I have improved `rnn-starter` by adding RN UI lib as a design system with dark mode support, improved project structure, added help methods that simplify work with RNN, and much more.

[docs] showcases info updated

---

website/docs/api/options-bottomTab.mdx

update `bottomTab` options documentation and add `selectTabOnPress`

update bottomTab option documentation

---

e2e/AndroidUtils.js
e2e/ApplicationLifecycleTest.test.js
e2e/config.json
e2e/global-setup.js
e2e/global-teardown.js
e2e/init.js
package.json
scripts/test-e2e.js
scripts/test-snapshot.js
scripts/test-unit.js

Improves our Android e2e test suite execution time by almost 50%.

Run e2e on genymotion device

---

lib/ios/UIViewController+RNNOptions.m
playground/ios/NavigationTests/RNNRootViewControllerTest.m

Fix statusBar.blur option on iOS

---

lib/ios/RNNAnimationsOptions.h
lib/ios/RNNAnimationsOptions.m
lib/ios/RNNCommandsHandler.m
lib/ios/TransitionOptions.h
lib/ios/TransitionOptions.m
lib/ios/ViewAnimationOptions.m

Fix modals waitForRender

---

playground/src/screens/sharedElementCarDealer/CarDetailsScreen.tsx
playground/src/screens/sharedElementCarDealer/CarStoryScreen.tsx
playground/src/screens/sharedElementCarDealer/CarsListScreen.tsx

fix shared element demo colours, was broken during dark mode changes

fix shared element demo colors

---

lib/android/app/src/main/java/com/reactnativenavigation/views/element/animators/ReactImageMatrixAnimator.kt

Fixes issue: #7204, see for more details

Null Safety on ReactImageMatrixAnimator Kotlin

---

lib/ios/TopBarAppearancePresenter.m

Apply back button icon changes to scroll edge appearance

---

lib/src/components/Modal.tsx

Should be hot fixed since it leads to a crash

Use View from React Native

---

lib/android/app/src/main/java/com/reactnativenavigation/react/modal/ModalLayoutController.kt

This should be hot fixed since production build fails.
Fixes: #7285

Fix nullable dispatcher of modals on Android

---

e2e/Keyboard.test.js
lib/android/app/src/main/java/com/reactnativenavigation/options/parsers/TypefaceLoader.kt
lib/android/app/src/test/java/com/reactnativenavigation/mocks/TypefaceLoaderMock.kt
lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/stack/TopBarControllerTest.kt
scripts/documentation.test.js
scripts/test-unit.js

- Mock default typeface.
- fix buttons adding and removing tests.

Fix Android unit tests

---

website/versioned_docs/version-7.16.0/api/options-imageResource.mdx

adding curly bracket leftButtons

Docs : Fix missing curly bracket leftButtons

---

lib/ios/RNNBridgeManager.mm
lib/ios/RNNModalManager.h
lib/ios/RNNModalManager.m

Fix fast refresh crash

---

website/docs/api/options-stack.mdx

Update noBorder documentation

---

lib/android/app/build.gradle
lib/android/app/src/test/java/com/reactnativenavigation/TestActivity.java
lib/android/app/src/test/java/com/reactnativenavigation/mocks/ImageLoaderMock.kt
lib/android/app/src/test/java/com/reactnativenavigation/mocks/Mocks.kt
lib/android/app/src/test/java/com/reactnativenavigation/mocks/TypefaceLoaderMock.kt
lib/android/app/src/test/java/com/reactnativenavigation/options/TransitionAnimationOptionsTest.kt
lib/android/app/src/test/java/com/reactnativenavigation/utils/MotionEventTest.kt
lib/android/app/src/test/java/com/reactnativenavigation/utils/UiThreadTest.java
lib/android/app/src/test/java/com/reactnativenavigation/utils/UiUtilsTest.java
lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/bottomtabs/BottomTabsPresenterTest.kt
lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/component/ComponentViewControllerTest.java
lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/fakes/FakeParentController.kt
lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/modal/ModalAnimatorTest.kt
lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/modal/ModalPresenterTest.java
lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/modal/ModalStackTest.java
lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/navigator/RootPresenterTest.kt
lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/stack/StackAnimatorTest.kt
lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/stack/StackControllerTest.kt
lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/stack/StackPresenterTest.kt
lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/stack/TopBarControllerTest.kt
lib/android/app/src/test/java/com/reactnativenavigation/views/TitleAndButtonsContainerTest.kt
lib/android/app/src/test/java/com/reactnativenavigation/views/animations/BaseViewAnimatorTest.kt
lib/android/app/src/test/java/com/reactnativenavigation/views/bottomtabs/BottomTabsContainerTest.kt
lib/android/app/src/test/java/com/reactnativenavigation/views/bottomtabs/BottomTabsTest.kt
playground/android/gradle.properties

Take advantage of the new features of the testing libraries to better mock Kotlin and static functions and compatibility with new android APIs.

Upgrade Android unit tests tools

---

website/docs/docs/docs-Installing.mdx

Updating Kotlin version to be aligned with actual code

Update Kotlin 1.5.31 version in docs

---

lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/stack/topbar/button/ButtonPresenter.kt

Fix for https://github.com/wix/react-native-navigation/issues/7437

Fix font not applied to topbar btn

---

lib/android/app/src/main/java/com/reactnativenavigation/react/NavigationModule.java

Wrapped onHostPause and  onHostResume with runOnMainThread by advice of @guyca in #7419

Make onHostPause and  onHostResume running on main thread (#7419)

---

website/docs/docs/docs-customBackNavigation.mdx

the link is broken - this PR fixes it

fix navigationButtonPress link

---

website/docusaurus.config.js
website/src/components/CustomLayout.js
website/src/components/StandWithUkraine.js
website/src/components/StandWithUkraine.module.css

Add StandWithUkraine banner on website

---

lib/ios/RNNBaseIconCreator.h
lib/ios/RNNBaseIconCreator.m
lib/ios/RNNButtonBuilder.m
lib/ios/RNNDynamicIconCreator.h
lib/ios/RNNDynamicIconCreator.m
lib/ios/RNNIconCreator.h
lib/ios/RNNIconCreator.m
lib/ios/ReactNativeNavigation.xcodeproj/project.pbxproj

Buttons with icon dark mode support didn't work on iOS.

Fix dark mode buttons support on iOS

---

lib/ios/RNNDynamicIconCreator.m

Fix button background dark mode colors

---

lib/android/app/build.gradle
playground/android/app/build.gradle

Downgrade library java version

---

lib/Mock/Components/LayoutComponent.tsx

This is helpful to troubleshoot test issues

Mock: Catch and log render errors

---

.github/workflows/documentation.yml
lib/android/app/src/main/java/com/reactnativenavigation/NavigationActivity.java
website/package.json

Fixed back button handling on Android

---

autolink/fixtures/rn71/AppDelegate.mm.template
autolink/fixtures/rn71/MainActivity.java.template
autolink/postlink/__snapshots__/activityLinker.test.js.snap
autolink/postlink/__snapshots__/appDelegateLinker.test.js.snap
autolink/postlink/activityLinker.js
autolink/postlink/activityLinker.test.js
autolink/postlink/appDelegateLinker.js
autolink/postlink/appDelegateLinker.test.js
autolink/postlink/gradleLinker.js

This PR fix `npx rnn-link` in react-native-navigation's installation process.
Closes #7695

Fix linking on react-native 0.71

---

lib/src/components/ComponentWrapper.test.tsx
lib/src/components/ComponentWrapper.tsx
lib/src/interfaces/NavigationComponentProps.ts

Reverts wix/react-native-navigation#7732

Revert "pass componentName prop to screens"

---

autolink/postlink/applicationLinker.js
autolink/postlink/gradleLinker.js

Fix auto link for RN72 on Android

---

lib/android/app/build.gradle

Addresses https://github.com/wix/react-native-navigation/issues/7748

Fix android build on RN72 and gradle 8

---

lib/ios/RNNComponentRootView.m

Fix white screen on push

---

react-native.config.js

Fix react-native.config.js

---

website/versioned_docs/version-7.37.0/docs/stack-buttons.mdx

Fix typo alowed -> allowed

---

lib/android/app/src/main/java/com/reactnativenavigation/NavigationActivity.java

Related - https://github.com/facebook/react-native/pull/42478
This change is needed in order to receive results on activity.registerForActivityResult

Call NavigationActivity super.onRequestPermissionsResult

---

lib/android/app/build.gradle
lib/android/app/src/main/AndroidManifest.xml

We need these changes to support RN 73 on Android

RN 73 - Android fixes

---

lib/ios/ReactNativeNavigation.xcodeproj/project.pbxproj

Removed broken references from the iOS project

chore: Cleanup iOS project broken references

---

lib/android/app/src/main/java/com/reactnativenavigation/FeatureToggles.kt
lib/android/app/src/main/java/com/reactnativenavigation/NavigationActivity.java
lib/android/app/src/main/java/com/reactnativenavigation/utils/ColorUtils.java
lib/android/app/src/main/java/com/reactnativenavigation/utils/SystemUiUtils.kt
lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/bottomtabs/BottomTabPresenter.java
lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/bottomtabs/BottomTabsController.java
lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/component/ComponentPresenter.java
lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/component/ComponentViewController.java
lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/stack/StackController.java
lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/stack/StackPresenter.java
lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/stack/statusbar/StatusBarController.kt
lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/stack/statusbar/StatusBarPresenter.kt
lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/stack/topbar/TopBarController.kt
lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/statusbar/StatusBarPresenter.kt
lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/viewcontroller/Presenter.java
lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/viewcontroller/StatusBarColorAnimator.kt
lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/viewcontroller/ViewController.java
lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/viewcontroller/ViewControllerVisibilityInfo.kt
lib/android/app/src/test/java/com/reactnativenavigation/BaseTest.kt
lib/android/app/src/test/java/com/reactnativenavigation/mocks/TitleBarReactViewCreatorMock.java
lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/bottomtabs/BottomTabsControllerTest.kt
lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/stack/TopBarControllerTest.kt
playground/android/app/src/main/java/com/reactnativenavigation/playground/MainApplication.java
playground/src/screens/NavigationScreen.tsx

Apply color animations on tab-switching (Android-only) (Merge from #7975)

---

.npmrc
package-lock.json

Fix npm registry (lock on public)

---

lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/bottomtabs/BottomTabsController.java

Fix SDK35 Bottom-tab positioning

---

lib/android/app/src/main/java/com/reactnativenavigation/options/LayoutFactory.java
lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/stack/StackController.java
lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/stack/StackPresenter.java
lib/android/app/src/test/java/com/reactnativenavigation/TestUtils.java
lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/OptionsApplyingTest.java
lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/stack/StackControllerTest.kt
lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/stack/StackPresenterTest.kt

```
java.lang.NullPointerException: Attempt to invoke virtual method 'void com.reactnativenavigation.viewcontrollers.stack.topbar.TopBarController.bindNewViewController(com.reactnativenavigation.viewcontrollers.viewcontroller.ViewController, com.reactnativenavigation.viewcontrollers.viewcontroller.ViewController)' on a null object reference
at com.reactnativenavigation.viewcontrollers.stack.StackPresenter.bindNewViewController(StackPresenter.java:197)
at com.reactnativenavigation.viewcontrollers.stack.StackController.onSelected(StackController.java:102)
at com.reactnativenavigation.viewcontrollers.bottomtabs.BottomTabsController.selectTab(BottomTabsController.java:288)
at com.reactnativenavigation.viewcontrollers.bottomtabs.BottomTabsController.selectTab(BottomTabsController.java:278)
at …
```

Fix crash coming from top-bar color animation
